/**
 * copy-global-ask — 问同学面板（GlobalAskPanel / 书桌 / 我的上下文）的用户面文案
 *
 * 从 copy.ts 拆出来的唯一理由是体积：这一块只有 问同学面板与「我的上下文」 用到，却随 COPY 单体进 /app 首屏 JS（≈5.6 KB gzip）。
 * 口吻审查仍是同一个入口：改文案先看 copy.ts，问同学面板与「我的上下文」看这里。用法：`import { GLOBAL_ASK_COPY } from "@/lib/ui/copy-global-ask"`。
 */

export const GLOBAL_ASK_COPY = {
    title: '问同学',
    subtitle: '相关课堂、资料和你的上下文会自动接上。',
    welcomeEyebrow: '从你正在学的地方继续',
    quickMode: '直接回答',
    deepMode: '陪我学会',
    modeSelectorLabel: '选择问同学的方式',
    quickModeBody: '马上回答，自动接上相关内容',
    deepModeBody: '先理解目标，再陪你走完整过程',
    memoryAction: '我的上下文',
    newConversation: '新对话',
    historyRestored: '已接回上次对话',
    historyLoading: '正在接回上次对话…',
    freshConversation: '新的对话',
    emptyTitle: '此刻，想弄明白什么？',
    emptyBody: '直接说就好。MeetMind 会自己找到相关课堂、材料和你之前留下的线索。',
    deepEmptyTitle: '这次，想真正学会什么？',
    deepEmptyBody: 'MeetMind 会先理解你要达到的结果，再陪你解释、练习和验证；只有必要时才问一个选择。',
    quickExamples: ['帮我解释刚才课堂里最难的概念', '把这份材料和我最近学的内容连起来'] as const,
    deepExamples: ['我想系统学懂这个主题，并检验自己是否真的会了', '围绕期末目标，把相关课堂整理成一条学习路线'] as const,
    composerQuick: '问任何正在学、正在想的事',
    composerDeep: '说说这次想真正学会什么',
    reasoningTitle: '思考过程',
    reasoningStreaming: '同学正在想…',
    startersTitle: '也可以从这里开始',
    send: '发送',
    stop: '停止',
    preparingIntent: '正在接上相关内容…',
    intentEyebrow: '先对齐一件事',
    intentProgress: (current: number, total: number): string => `${current} / ${total}`,
    intentSingle: '选一个就好',
    intentMultiple: '可以多选',
    intentCancel: '直接开始',
    intentBack: '上一步',
    intentContinue: '继续',
    intentResolve: '继续',
    intentStart: '开始学习',
    intentFirstStep: '先从这里开始',
    approachUnderstand: '理解清楚',
    approachPractice: '练到会用',
    approachSynthesize: '串成体系',
    approachCreate: '做出结果',
    contextPersonal: '用长期上下文',
    contextCurrent: '用当前内容',
    contextMixed: '两边一起看',
    contextStatus: '已接入',
    contextAction: '参考范围',
    contextSummary: (current: number, recent: number, memory: number): string => {
      const parts = [
        current > 0 ? `${current} 份当前内容` : '',
        recent > 0 ? `${recent} 条最近学习` : '',
        memory > 0 ? `${memory} 条长期理解` : '',
      ].filter(Boolean);
      return parts.length > 0 ? `会参考 ${parts.join('、')}` : '这次先从你的问题开始';
    },
    /** 只有一份当前材料时点名它（2026-09-08）：比"1 份当前内容"像人话 */
    contextSummaryNamed: (title: string, recent: number, memory: number): string => {
      const extra = [
        recent > 0 ? `${recent} 条最近学习` : '',
        memory > 0 ? `${memory} 条长期理解` : '',
      ].filter(Boolean);
      return `会带上《${title}》${extra.length > 0 ? `，还有 ${extra.join('、')}` : ''}`;
    },
    /** 空态建议入口（2026-09-08）：从这个人正在学的地方接话，不再是谁看都一样的通用句 */
    starters: {
      quickFromCurrentLesson: '帮我讲清这节课里最难的地方',
      quickFromMaterial: (title: string): string => `帮我讲清《${title}》里最难的地方`,
      quickFromLesson: (title: string): string => `接着《${title}》，我哪里还没懂？`,
      quickFromChallenge: (title: string): string => `再讲一遍「${title}」，上次没弄明白`,
      deepFromLesson: (title: string): string => `围绕《${title}》，帮我系统学懂并检验是否真的会了`,
      deepFromMaterial: (title: string): string => `围绕《${title}》，帮我系统学懂并检验是否真的会了`,
    },
    /**
     * 空态「书桌」（2026-09-08）：同桌此刻在读什么、记得你什么，摆成可见可点的实物；
     * 点一件就变成一句指向具体位置的问题。全是学生自己留下的事实，不推断。
     */
    desk: {
      eyebrow: '同学正在读',
      readingTitle: '正在读',
      momentsTitle: '你标的',
      unstableTitle: '还没稳',
      recentTitle: '最近',
      memoryTitle: '记得',
      currentLesson: '这节课的转录',
      currentLessonMeta: '这节课',
      overflow: (count: number): string => `+${count}`,
      anchorType: {
        confusion: '没跟上',
        important: '重点',
        question: '有疑问',
      } as Record<'confusion' | 'important' | 'question', string>,
      memoryChallenge: '上次没弄明白',
      memoryTopic: '在学',
      emptyTitle: '桌上还是空的。',
      emptyBody: '上一节课、收一份材料，或者先试听一节示例课——同学读过什么，就会摆在这里。',
      /** 登录用户没有试听入口（示例课只在访客态自动灌入），不提示它 */
      emptyBodyNoDemo: '上一节课，或收一份材料——同学读过什么，就会摆在这里。',
      emptyDemo: '先试听示例课',
      promptFromCurrentLesson: '帮我讲清这节课里最难的地方',
      promptFromLesson: (title: string): string => `帮我讲清《${title}》里最难的地方`,
      promptFromMaterial: (title: string): string => `帮我讲清《${title}》里最难的地方`,
      promptFromMoment: (time: string): string => `${time} 那里我没跟上，从这讲一下`,
      /** 时刻有名字（老师原话）时带上 */
      promptFromNamedMoment: (time: string, title: string): string => `${time}「${title}」那里我没跟上，从这讲一下`,
      promptFromNotedMoment: (time: string, note: string): string => `${time} 那里我写了「${note}」，帮我把这段讲清楚`,
      promptFromImportant: (time: string): string => `${time} 那里老师强调的是什么？帮我讲透`,
      promptFromUnstable: (concept: string): string => `再讲一遍「${concept}」，换一个新的例子`,
      promptFromImproving: (concept: string): string => `「${concept}」我刚记住，考考我是不是真会了`,
      promptFromRecent: (title: string): string => `接着《${title}》，我哪里还没懂？`,
      promptFromChallenge: (title: string): string => `再讲一遍「${title}」，上次没弄明白`,
      promptFromTopic: (title: string): string => `围绕「${title}」，我现在该学什么？`,
    },
    contextCurrentCount: (count: number): string => `${count} 份当前材料`,
    contextRecentCount: (count: number): string => `${count} 条最近学习`,
    contextMemoryCount: (count: number): string => `${count} 条长期记忆`,
    contextEmpty: '这次先从你的问题开始',
    contextRailEyebrow: '上下文已就位',
    contextRailTitle: '这次会用到什么',
    contextRailBody: '只展示实际接入的内容。回答仍以你此刻的问题为准。',
    contextDrawerCurrent: '当前内容',
    contextDrawerRecent: '最近学习现场',
    contextDrawerRecentBody: '用来接续你刚才做到的地方',
    contextDrawerMemory: '长期学习理解',
    contextDrawerMemoryBody: '只使用你已确认或可随时纠正的内容',
    contextConnected: '已接入这次对话',
    contextWaiting: '有内容后自动接入',
    contextActiveThread: '正在继续的学习',
    progressEyebrow: 'MeetMind 更新了对你的理解',
    progressHint: '这些理解会随着之后的学习继续调整。',
    progressDismiss: '这次不记',
    progressSave: '记住确认的',
    progressSaved: '已经记下，也可以随时纠正',
    memoryTitle: '我的上下文',
    memoryBack: '返回',
    contextLibraryNavigation: '浏览上下文',
    contextCoursesOverviewTitle: '课程与考试',
    contextCoursesOverviewBody: '查看课堂如何归入课程、纠正课程边界，或跨课程选择考试范围。',
    memoryUnderstandingTab: '对我的理解',
    memoryCoursesTab: '课堂上下文',
    memoryRecentTab: '客观记录',
    memoryUnderstandingTitle: 'MeetMind 记得的你',
    courseContextTitle: '我的课程',
    courseContextEmpty: '录下一节课后，课程会自动在这里出现。',
    courseContextLessons: (count: number): string => `${count} 节课`,
    courseContextMinutes: (count: number): string => `${count} 分钟`,
    courseContextActive: '正在参考',
    courseContextPaused: '已暂停参考',
    courseContextSuggested: '待确认',
    courseContextUnclassified: '单节课堂',
    courseContextDetached: '已移出',
    courseContextRename: '改课程名',
    courseContextRenameHint: '例如：线性代数',
    courseContextTags: '课程标签',
    courseContextTagsHint: '例如：专业课、期末重点',
    courseContextSave: '确认',
    courseContextCancel: '取消',
    courseContextPause: '暂不参考这门课',
    courseContextResume: '重新参考这门课',
    courseContextDetails: '查看课堂',
    courseContextCollapse: '收起课堂',
    courseContextConfirm: '确认属于同一门课',
    courseContextDetach: '移出',
    courseContextDetachTitle: (title: string): string => `将“${title}”移出这门课`,
    courseContextRestore: '放回原课程',
    courseContextCheatsheet: '单元速查表',
    courseCheatsheetEntryEyebrow: '跨课与考试',
    courseCheatsheetEntryTitle: '考试速查表',
    courseCheatsheetEntryBody: '从多门课程、课堂录音和上传材料中直接勾选考试范围，整理成可编辑、可打印的高密度参考表。',
    courseCheatsheetEntryAction: '选择考试范围',
    courseCheatsheetEntryCourseAction: '从这门课开始',
    courseCheatsheetEntryEmpty: '至少保留两节有原文的课堂后，就可以直接组合考试范围。',
    courseCheatsheetEntryAvailable: (courses: number, lessons: number): string => `${courses} 门课程 · ${lessons} 节课堂可选`,
    courseCheatsheetScopeEyebrow: '多课程范围',
    courseCheatsheetScopeHint: '课程只是帮你快速定位，不是限制。可以跨课程勾选，也可以精确到某一节课堂。',
    courseCheatsheetCoursesLabel: '课程',
    courseCheatsheetClear: '清空',
    courseCheatsheetSelectionSummary: (courses: number, lessons: number): string => `已选 ${courses} 门 · ${lessons} 节`,
    courseCheatsheetCourseSelection: (selected: number, total: number): string => `${selected}/${total} 节已选`,
    courseCheatsheetEmptySelectionTitle: '先选择课程',
    courseCheatsheetEmptySelectionBody: '选中课程后，可以继续精确到具体课堂。',
    courseCheatsheetMinimumHint: '至少选择两节有原文的课堂',
    courseContextCombinedScope: (count: number): string => `${count} 门课程的考试范围`,
    courseContextBackToCourse: '返回课程',
    courseContextCheatsheetNeedsTranscript: (count: number): string => count === 0
      ? '这些课堂还没有可用原文。'
      : `目前只有 ${count} 节课有可用原文，至少需要两节。`,
    courseContextChooseLessons: '这次要带上哪些课？',
    courseContextChooseLessonsHint: '先选同一单元或同一考试范围；最近四节已替你选好。',
    courseContextSelectAll: '全选',
    courseContextBeginCheatsheet: (count: number): string => `用这 ${count} 节课整理`,
    courseContextCheatsheetLoading: '正在把这几节课压成一份纸面速查表',
    courseContextCheatsheetNotReady: '所选内容里还没有足够稳定的学科知识，暂时做不出可靠的考试速查表。课堂原文已经保留，可以返回课程后换一组范围。',
    courseContextRecording: '录音',
    courseContextUpload: '上传',
    courseContextVideo: '视频',
    courseContextUntitled: '待命名课程',
    courseContextRecordingLesson: '课堂录音',
    courseContextUploadLesson: '上传课堂',
    courseContextVideoLesson: '视频课堂',
    courseContextFallbackTitle: (month: number, day: number): string => `${month} 月 ${day} 日的课`,
    courseContextLessonFallbackTitle: (month: number, day: number, time: string): string => `${month} 月 ${day} 日 ${time} 的课`,
    courseContextScheduleTitle: (weekday: string): string => `${weekday}的课`,
    courseContextRecurring: (weekday: string, time: string): string => `常在${weekday} ${time} 上课`,
    courseAssessmentAdd: '这门课有考试',
    courseAssessmentEditTitle: '考试',
    courseAssessmentDefaultName: (courseTitle: string): string => `${courseTitle}考试`,
    courseAssessmentName: '考试名称',
    courseAssessmentNameHint: '例如：期末考试',
    courseAssessmentDate: '考试日期',
    courseAssessmentMode: '考试方式',
    courseAssessmentUnknown: '还不确定',
    courseAssessmentClosedBook: '闭卷',
    courseAssessmentOpenBook: '开卷',
    courseAssessmentScope: '考试范围',
    courseAssessmentScopeHint: '可选：粘贴老师公布的范围或大纲',
    courseAssessmentHasScope: '已有范围',
    courseAssessmentSave: '记下',
    courseAssessmentStop: '不再准备',
    courseAssessmentEdit: '修改考试信息',
    courseAssessmentPrepare: '做速查表',
    courseAssessmentChooseScope: '哪些课在考试范围内？',
    memoryKindPreference: '学习方式',
    memoryKindStrength: '正在形成的能力',
    memoryKindChallenge: '还在弄懂',
    memoryKindTopic: '正在关注',
    memoryKindProgress: '最近进展',
    memorySourceUser: '你告诉 MeetMind 的',
    memorySourceAi: '从你的学习互动中理解到的',
    memoryCorrection: '不太准确',
    memoryAddContext: '补充一下',
    memoryCorrectionHint: '换成更准确的说法',
    memoryCorrectionSave: '改好了',
    memoryCorrectionCancel: '取消',
    memoryMore: '更多操作',
    memoryStopUsing: '暂不参考',
    memoryUseAgain: '重新参考',
    memoryForget: '忘记这条',
    memoryTalkPrompt: '关于我，想补充或纠正的是：',
    memoryEmpty: '还没有形成稳定的理解。先正常学习就好，MeetMind 会从真实过程里慢慢认识你。',
    /** 掌握轨迹（2026-09-08）：测验 / 闪卡 / 讲给同桌听留下的事实按概念连成线，让"曾经不稳 → 现在稳"被看见 */
    masteryTrail: {
      eyebrow: '掌握轨迹',
      title: '最近检验过的东西',
      body: '来自测验、闪卡和讲给同桌听的事实，不是判断。',
      statusUnstable: '还没稳',
      statusImproving: '刚记住',
      statusStable: '已经稳了',
      stepLabels: {
        quiz: '测验',
        flashcards: '闪卡',
        'teach-back': '讲给同桌听',
      } as Record<string, string>,
      deviceScopeHint: '这台设备上的记录。登录后会跟着你走。',
      /** 登录用户：轨迹来自服务端事件表，换设备也在 */
      accountScopeHint: '跟着你的账号走，换设备也在。',
    },
    memoryPaused: '已不再参考',
    recentTitle: '最近学习现场',
    recentEmpty: '最近还没有可恢复的学习活动。',
    recentKindConversation: '一次对话',
    recentKindLesson: '一节课堂',
    recentKindApp: '一次练习',
    recentKindCapture: '一份学习材料',
    recentShowAll: (count: number) => `查看全部 ${count} 条学习现场`,
    recentCollapse: '收起较早记录',
    threadTitle: '上次还在继续',
    threadResume: '接着学',
    threadComplete: '这条学完了',
    preparingError: '这次没理解准，先直接回答你。',
    refiningError: '先按目前的理解开始，之后还可以随时调整。',
    responseError: '刚才没有接上，再发一次就好。',
    sourceContext: '刚刚在看的内容',
    sourceCurrentLesson: '当前课堂转录',
    openSource: '打开原内容',
    close: '关闭问同学',
    assistantLabel: 'MeetMind 回答',
    userLabel: '你的问题',
    thinking: '正在把上下文接起来…',
    recentConversation: '问同学的对话',
    recentDeepSession: '一起学的对话',
    recoveryEyebrow: '接回学习现场',
    recoveryTitle: '不用重新开始',
    recoveryBody: 'MeetMind 留住了上次的脉络，回来可以直接接着走。',
    recoveryResume: '接着上次学',
    recoveryRecent: '最近停在这里',
    appActivity: (name: string) => `完成了「${name}」`,
    appResultSummary: (count: number) => `生成了 ${count} 条可继续使用的学习内容`,
  } as const;

export type GlobalAskCopy = typeof GLOBAL_ASK_COPY;
