/**
 * copy-landing — 营销页（Landing / Technology）的用户面文案。
 *
 * 从 copy.ts 拆出来的唯一理由是体积：这两块占 COPY 的 1/5（≈10 KB gzip），而 /app、/share、/settings 都用不到，
 * 却随 COPY 单体进每个页面的首屏 JS。口吻审查仍是同一个入口：改文案先看 copy.ts，营销页看这里。
 * 用法：`import { LANDING_COPY } from "@/lib/ui/copy-landing"` → `LANDING_COPY.landing.hero.title`。
 */

export const LANDING_COPY = {
  landing: {
    media: {
      realProduct: '真实产品画面',
      videoFallback: '你的浏览器暂时无法播放这段产品录屏。',
    },
    navigation: {
      product: '产品',
      philosophy: '为什么是 MeetMind',
      technology: '技术',
      signIn: '登录',
      openProduct: '进入 MeetMind',
    },
    hero: {
      eyebrow: '真正听过这节课的 AI 同学',
      title: '真正听过这节课，\n才知道你哪里没懂。',
      body: '录下课堂，发来资料。MeetMind 记得老师怎么讲，也知道你在哪里卡住，把每一次学习接成一条不会断的线。',
      primaryAction: '先试听一节课',
      secondaryAction: '看看它怎么工作',
      imageAlt: '大学生在真实课堂中听课并记录笔记',
      videoAlt: 'MeetMind 真实试听课正在展示实时转录、课堂脉络和同学',
      demoLabel: '正在听 · 英语听力',
      demoTime: '18:42',
      demoTranscript: '条件概率不是换一个公式，而是缩小我们正在观察的世界。',
      demoContext: '已接上：上节课的贝叶斯公式',
      demoBoard: '板书已收下',
      demoLive: '课堂脉络正在生长',
      filmLabel: 'MeetMind 产品短片',
      filmDuration: '45 秒 · 真实操作短片',
      filmChapters: ['正在听懂这节课', '把问题练到会', '把每次学习接起来', '从一节课，走向一门课'] as const,
      filmClosingTitle: '从听懂这一节课，\n到学会这一门课。',
      filmClosingBody: '真正懂你在学什么的 AI 同学',
      playFilm: '播放产品短片',
      pauseFilm: '暂停产品短片',
      unmuteFilm: '开启产品短片声音',
      muteFilm: '关闭产品短片声音',
      listenFilm: '听产品介绍',
    },
    belief: {
      eyebrow: '学习不该在下课铃响时断掉',
      title: '模型懂世界，还不够。\n它还得懂正在学习的你。',
      body: '一次回答可以很聪明，真正的学习却发生在一节又一节课之间。MeetMind 保留老师的原话、你的困惑和正在靠近的目标，让下一次帮助从你真正停下的地方继续。',
    },
    manifesto: {
      lineA: '不是笔记工具，也不只是课堂转录。',
      lineB: '它真的听过课，也知道你正在学什么。',
    },
    classroomLine: {
      eyebrow: '上课',
      title: '从一节真实的课，\n一直陪到考试。',
      body: '录、问、练、证、考——五个动作发生在同一个现场里，不需要在四个工具之间搬运。',
      previous: '查看上一个阶段',
      next: '查看下一个阶段',
      ariaLabel: '一节课从上课到考试的时间线',
      stages: [
        {
          step: '01', verb: '录', time: '09:02 · 上课中',
          title: '先录下这节课',
          body: '麦克风、电脑声音，或两路都录。原声一直在，转录只是开始。',
          mock: {
            kind: 'live',
            lines: ['条件概率不是换一个公式，', '而是缩小我们正在观察的世界。', '所以先看清楚：我们在哪些人里谈概率。'] as const,
            chips: ['条件概率', '样本空间'] as const,
          },
        },
        {
          step: '02', verb: '问', time: '09:47 · 课中',
          title: '同桌跟上课堂',
          body: 'AI 同学听着同一段话。卡住时直接问，不用举手，也不用等下课。',
          mock: {
            kind: 'ask',
            question: '这里为什么能直接用贝叶斯？',
            answer: '老师先把观察范围缩小到了「检测为阳性」的人。',
            cite: '18:42',
          },
        },
        {
          step: '03', verb: '练', time: '16:20 · 下课',
          title: '从原话出发复习',
          body: '闪卡、测验、思维导图，都从老师真正讲过的内容里长出来。',
          mock: {
            kind: 'card',
            front: '什么是条件概率？',
            back: '已知 B 发生时，A 发生的概率。',
            progress: '3 / 12',
          },
        },
        {
          step: '04', verb: '证', time: '周三 · 复习',
          title: '每个结论都有根',
          body: '回答可以跳回 [MM:SS] 的那一刻。不是听起来对，是真的对。',
          mock: {
            kind: 'evidence',
            answer: '后验，就是把证据算进去之后的判断。',
            evidence: '18:42',
            quote: '缩小我们正在观察的世界',
          },
        },
        {
          step: '05', verb: '考', time: '考前 · 一周',
          title: '多节课连成考试范围',
          body: '几节课成单元，一学期压成一张能带进考场的速查表。',
          mock: {
            kind: 'sheet',
            sheetTitle: '概率论 · 期末一页纸',
            lines: ['P(A|B) = P(AB) / P(B)', '后验 ∝ 似然 × 先验', '易错：混淆 P(A|B) 与 P(B|A)'] as const,
          },
        },
      ] as const,
    },
    appsLine: {
      eyebrow: '下课以后',
      title: '一节课，\n长出七种学法。',
      body: '不是模板生成。每个应用都从老师真正讲过的内容里长出来，练完还能跳回原话对答案。',
      ariaLabel: '七种学习应用，可直接上手试',
      apps: [
        {
          key: 'flashcards',
          name: '闪卡训练',
          tag: '主动回忆',
          flipHint: '点卡片翻面',
          nextLabel: '下一张',
          cards: [
            { front: '什么是条件概率？', back: '已知 B 发生时，A 发生的概率：P(A|B) = P(AB) / P(B)。' },
            { front: '先验和后验的区别？', back: '看到证据之前是先验，把证据算进去之后是后验。' },
            { front: '什么是样本空间？', back: '所有可能结果的集合。条件概率就是把它缩小。' },
          ] as const,
        },
        {
          key: 'quiz',
          name: '课堂测验',
          tag: '理解检验',
          question: '老师说的「缩小观察的世界」是指什么？',
          options: ['换用另一个公式', '只在检测阳性的人里重新看概率', '忽略先验概率'] as const,
          answer: 1,
          correctNote: '答对了。这句话出自 18:42。',
          wrongNote: '再想想——老师在 18:42 讲过。',
          evidence: '跳回原话 18:42',
        },
        {
          key: 'mindmap',
          name: '思维导图',
          tag: '结构学习',
          root: '贝叶斯定理',
          expandHint: '点分支展开',
          branches: [
            { name: '条件概率', children: ['样本空间', 'P(A|B) 定义'] as const },
            { name: '先验与后验', children: ['似然', '归一化'] as const },
            { name: '检测悖论', children: ['假阳性', '基数忽略'] as const },
          ] as const,
        },
        {
          key: 'cheatsheet',
          name: '考试速查表',
          tag: '可打印',
          sheetTitle: '概率论 · 期末一页纸',
          lines: ['P(A|B) = P(AB) / P(B)', '后验 ∝ 似然 × 先验', '易错：混淆 P(A|B) 与 P(B|A)'] as const,
        },
        {
          key: 'audio-overview',
          name: '课堂播客',
          tag: '通勤可听',
          episode: '第 3 讲 · 贝叶斯定理',
          duration: '90 秒试听',
          chapters: ['开场 · 缩小观察的世界', '中段 · 检测悖论', '结尾 · 考前一句话'] as const,
        },
        {
          key: 'infographic',
          name: '课堂信息图',
          tag: '一张图带走',
          course: '概率论与数理统计',
          quote: '条件概率不是换公式，是缩小我们正在观察的世界。',
          summary: '先定样本空间，再谈概率。',
        },
        {
          key: 'teach-back',
          name: '讲给同桌听',
          tag: '费曼检验',
          topic: '讲一遍：贝叶斯公式怎么来的',
          passed: ['条件概率', '先验与后验'] as const,
          blind: '归一化常数',
          blindNote: '「似然 × 先验」之后还要除以证据总和，这一步跳过去了。',
        },
      ] as const,
    },
    collectionLine: {
      eyebrow: '随手收',
      title: '像发消息一样，\n先把它收下。',
      body: '在微信公众号里，像发给朋友一样发给它——好文章、板书照片、一闪而过的想法。不用分类，不用打标签，收藏就这么自然地发生了。',
      silentNote: '模型在后台判断它属于哪门课、哪个目标、哪个问题，再悄悄回流到课堂和你的长期上下文。',
      sinkLabel: '先收下',
      statusLabel: '都已收下 · 后台正在判断归属',
      wechatHeader: 'MeetMind',
      wechatThread: [
        { kind: 'link', inbound: '贝叶斯定理的直觉解释', reply: '已收下这篇网页，归到「概率论 · 第 3 讲」' },
        { kind: 'image', inbound: '黑板照片', reply: '板书已收下，认出 4 个公式，接回今天的课堂' },
        { kind: 'text', inbound: '贝叶斯那里我还是没懂', reply: '你上节课卡在条件空间的变化——先沿板书把样本空间重新圈一遍' },
      ] as const,
      sideChannels: [
        { channel: '桌面端', kind: 'image', text: '热键截下这一页', reply: '截图已收下，接回当前课堂' },
        { channel: '随手记', kind: 'voice', text: '0:18', reply: '语音已转成文字，标记为一个疑问' },
      ] as const,
      channelNote: '桌面端和网页也能收——但大多数时候，顺手一发就够了。',
    },
    bridge: {
      eyebrow: '两条线，不会成为数据孤岛',
      lead: '好的回答，来自三样东西',
      parts: ['个人上下文', '场景上下文', '模型智能'] as const,
      partNotes: ['目标 · 阶段 · 长期困惑', '这节课 · 这份材料 · 此刻意图', '解释 · 定位 · 验证 · 克制'] as const,
    },
    journey: {
      eyebrow: '从现场开始，一直陪到学会',
      title: '把一节真实的课，\n变成一条不会断的学习线。',
      body: '课堂、课后、考试与长期目标，不再是四个互不认识的工具。',
      tabsLabel: '选择学习场景',
      previousScene: '查看上一个学习场景',
      nextScene: '查看下一个学习场景',
      classroomImageAlt: '课堂录音与实时理解',
      scenes: [
        {
          id: 'classroom',
          label: '上课',
          kicker: '听懂现场',
          title: '不只转成文字，还在跟上这节课。',
          body: '原话、板书和课堂脉络按时间排在一起。需要回来的地方先替你留住，听课时不用低头整理。',
          detail: '原话 · 板书 · 课堂脉络',
          metric: '课中',
          imageAlt: '真实试听课中的实时转录、课堂脉络和同学三栏界面',
          proofs: ['实时转录与双语理解', '课堂脉络随音频推进', '卡住时在同一现场直接问同学'] as const,
        },
        {
          id: 'capture',
          label: '放资料',
          kicker: '连起材料',
          title: '课件、网页和随手拍，不再各自孤立。',
          body: '像发消息一样把资料放进来。MeetMind 自动辨认它与哪门课、哪个问题和哪个目标有关。',
          detail: '文件 · 链接 · 图片 · 想法',
          metric: '随手',
          imageAlt: 'MeetMind 真实收集流与文件上传入口',
          proofs: ['文字、链接、图片和文件都能收下', '材料自动接回相关课堂', '需要时直接带着材料问同学'] as const,
        },
        {
          id: 'review',
          label: '课后',
          kicker: '练到会用',
          title: '从老师的原话出发，解释、练习、再验证。',
          body: '闪卡、测验和思维导图不是模板生成，而是从这节课真实讲过的内容里长出来。',
          detail: '解释 · 闪卡 · 测验 · 思维导图',
          metric: '有根',
          imageAlt: '真实课后复习三栏中的原声证据、闪卡训练和 AI 同学',
          proofs: ['左侧保留原声和转录证据', '中间完成闪卡、测验与思维导图', '右侧同学始终知道正在练什么'] as const,
        },
        {
          id: 'exam',
          label: '备考',
          kicker: '跨课整理',
          title: '几节课连成单元，一学期压成考试范围。',
          body: '自由选择课程与课次，生成可编辑、可打印、能真正带进考场的高密度速查表。',
          detail: '多课范围 · 薄弱点 · 可打印速查表',
          metric: '跨课',
          imageAlt: '真实考试速查表跨课程与课堂范围选择界面',
          proofs: ['跨课程勾选真实课堂', '精确选择考试覆盖的课次', '整理成可编辑、可打印的高密度参考表'] as const,
        },
        {
          id: 'context',
          label: '越用越懂',
          kicker: '个人上下文',
          title: '它逐渐知道你会什么，也知道你正在努力什么。',
          body: '客观学习现场与长期理解分开保存。你能看见、纠正、暂停或忘记，掌控权始终在你手里。',
          detail: '目标 · 掌握情况 · 学习方式 · 最近现场',
          metric: '长期',
          imageAlt: 'MeetMind 真实个人上下文中的长期理解、课程考试和最近学习现场',
          proofs: ['最近学习现场保持客观', '长期理解只保留有证据的内容', '随时可以纠正、暂停或忘记'] as const,
        },
      ] as const,
    },
    featureRail: {
      eyebrow: '真实操作 · 连续场景',
      title: '不是功能清单，\n是一条完整的学习路径。',
      body: '左右滑动，每个短片都来自 MeetMind 的真实操作。你看到的不只是结果，还有从课堂现场到理解验证的完整过程。',
      ariaLabel: 'MeetMind 产品功能场景',
      previous: '查看上一个产品场景',
      next: '查看下一个产品场景',
      scenes: [
        {
          id: 'live-class',
          step: '01',
          title: '正在听课',
          body: '原话、课堂脉络和同学一起跟上现场。',
          videoAlt: 'MeetMind 正在实时理解课堂内容',
        },
        {
          id: 'end-class',
          step: '02',
          title: '结束课堂',
          body: '一次点击，把现场收束成可以继续学习的完整证据。',
          videoAlt: '结束 MeetMind 课堂并进入课后整理',
        },
        {
          id: 'evidence-review',
          step: '03',
          title: '从证据开始复习',
          body: '原声和时间点留在左边，练习从老师真正讲过的内容开始。',
          videoAlt: 'MeetMind 课后复习保留原声和转录证据',
        },
        {
          id: 'quiz-submit',
          step: '04',
          title: '选择并提交答案',
          body: '测验不是结果页，而是一次对理解的真实验证。',
          videoAlt: '在 MeetMind 课堂测验中选择并提交答案',
        },
        {
          id: 'evidence-jump',
          step: '05',
          title: '从解释跳回原话',
          body: '每个结论都能回到老师讲过的那一刻。',
          videoAlt: '从测验解释跳回对应的课堂原话',
        },
        {
          id: 'learning-methods',
          step: '06',
          title: '六种学习方式',
          body: '按这节课的内容，继续闪卡、测验、导图或其他练习。',
          videoAlt: 'MeetMind 展示六种基于课堂的学习方式',
        },
        {
          id: 'complete-mindmap',
          step: '07',
          title: '展开完整导图',
          body: '根节点、3 个分支和 9 个节点一次看全，没有裁切。',
          videoAlt: '完整展示根节点、三个分支和九个节点的课堂思维导图',
        },
      ] as const,
    },
    livePreview: {
      status: '可交互试听',
      eyebrow: '一节真的能听、能问、能复习的课',
      title: '现在就坐进这节课里。',
      body: '播放试听课，看看 MeetMind 如何跟着老师往前走；卡住时直接问，下课后继续复习。',
      action: '开始试听',
      frameTitle: 'MeetMind 试听课堂',
    },
    difference: {
      eyebrow: '同一个问题，答案为什么不一样',
      title: '好的回答，来自它知道你为什么现在问。',
      prompt: '“为什么这里可以直接用贝叶斯公式？”',
      genericLabel: '只看见这个问题',
      genericAnswer: '贝叶斯公式描述了条件概率之间的关系。套用公式即可计算后验概率。',
      meetmindLabel: 'MeetMind 还看见',
      contextItems: ['18:42 的老师原话', '刚拍下的板书', '上节课标记的困惑', '两周后的期末目标'],
      meetmindAnswer: '老师这里先把观察范围缩小到了“检测为阳性”的人。你上节课卡住的正是这个条件空间变化，所以这次先不代数，沿着板书把样本空间重新圈一遍。',
    },
    outcomes: {
      eyebrow: '回来时，比发出去的更好',
      title: '一节课、一个单元、一场考试，都有真正能带走的结果。',
      items: [
        {
          number: '01',
          scope: '一节课后',
          title: '知道讲了什么，也知道自己哪里没懂。',
          body: '课堂整理、原话证据、困惑解释和即时练习。',
        },
        {
          number: '02',
          scope: '几节课后',
          title: '零散知识开始连成一个可以调用的结构。',
          body: '单元关系、重复出现的难点和薄弱点复练。',
        },
        {
          number: '03',
          scope: '考试之前',
          title: '把一学期真正压缩成自己带得走的东西。',
          body: '考试范围、复习路线、模拟检验和可打印速查表。',
        },
      ] as const,
    },
    context: {
      eyebrow: '上下文属于你',
      title: '它记住的，你都能改。',
      body: '不用维护标签，也不用管理数据库。它记住的每一条都来自真实的课堂和收藏，你随时看得见，也改得动。',
      panelTitle: '它现在记得',
      memories: [
        { kind: '困惑', text: '条件空间的变化', source: '概率论 · 第 3 讲 18:42' },
        { kind: '目标', text: '期末 85+', source: '概率论与数理统计' },
        { kind: '收藏', text: '贝叶斯定理的直觉解释', source: '来自网页 · 已接回第 3 讲' },
        { kind: '习惯', text: '先听一遍原声，再看整理', source: '最近 4 节课' },
      ] as const,
      actions: { correct: '纠正', pause: '暂停', resume: '恢复', forget: '忘掉' },
      pausedLabel: '已暂停',
      note: '每一条都可以纠正、暂停，或者彻底忘掉。',
    },
    finalCta: {
      eyebrow: '从一节真实的课开始',
      title: '下一次下课，\n别再从头整理。',
      body: '先试听一节完整课堂，看看 MeetMind 如何从听课一直陪到复习。',
      primaryAction: '先试听一节课',
      secondaryAction: '登录 MeetMind',
    },
    desktop: {
      eyebrow: '桌面端',
      title: '装到电脑上，\n它就能听见你在上的课。',
      body: '桌面端让 MeetMind 常驻在屏幕角落：录网课时直接收电脑里的声音，不用带机器人入会；任何画面按一下热键，就截图收进你的学习上下文。',
      macAction: '下载 macOS 版',
      macNote: 'Apple Silicon 芯片',
      macIntelNote: 'Intel 芯片版',
      windowsAction: '下载 Windows 版',
      windowsNote: 'Windows 10 及以上 · 64 位',
      hotkeyHint: '截图热键 Ctrl/Cmd + Shift + M',
      guideAction: '桌面端与桌宠使用说明 →',
      unsignedNote: '安装包暂未签名：macOS 请「右键 → 打开」，Windows 请在 SmartScreen 提示中选「仍要运行」。',
    },
    footer: {
      tagline: '真正懂你在学什么的 AI 同学',
      product: '产品',
      technology: '技术',
      login: '登录',
      copyright: '© 2026 MeetMind',
    },
  },

  technology: {
    label: 'Technology',
    imageAlt: '大学课堂中的 MeetMind 技术现场',
    navigation: {
      product: '回到产品',
      gap: '技术缺口',
      perception: 'MM-Perception',
      memory: 'MM-Memory',
      teacher: 'MM-Teacher',
      roadmap: '路线图',
      openProduct: '体验 MeetMind',
    },
    hero: {
      eyebrow: 'MeetMind Technology',
      title: '师者智能',
      sub: '从理解知识，到理解学习知识的人。',
      punch: '为机器立师者之心。',
      stackLabel: 'MeetMind 师者智能技术栈',
      primaryAction: '了解这条赛道',
      statusLabel: '当前系统',
      statusValue: '课堂场景 · 持续迭代',
    },
    track: {
      eyebrow: '定义赛道',
      title: '大模型能生成答案，\n却还不是老师。',
      body: '成为老师需要的三种基础能力，通用模型三者皆缺。',
      abilities: [
        { title: '连续感知', body: '对真实学习现场的连续感知。' },
        { title: '长期建模', body: '对一个人的长期动态建模。' },
        { title: '教学决策', body: '面向长期成长的教学决策。' },
      ] as const,
      stackLabel: 'MeetMind 正在构建完整的师者智能技术栈',
      stack: [
        { en: 'Perception', cn: '全息多模态理解' },
        { en: 'Memory', cn: '教育记忆模型' },
        { en: 'Teaching Policy', cn: '师者智能大模型' },
      ] as const,
    },
    gap: {
      eyebrow: '技术缺口',
      title: '大模型拥有世界知识，\n但没有学生状态。',
      traditionalLabel: '传统大模型链路',
      traditional: ['问题', '大模型', '回答'] as const,
      oursLabel: 'MeetMind 师者智能链路',
      loop: ['课堂现场', '多模态状态理解', '个体长期记忆', '教学策略选择', '学习结果反馈', '更新对人的理解'] as const,
      loopBack: '回到课堂现场——每一圈，都更懂这个人一点。',
      missCol: '当前大模型缺失',
      oursCol: 'MeetMind 技术',
      rows: [
        { miss: '无法完整感知课堂中的人', ours: '全息多模态理解（视觉 · 听觉）' },
        { miss: '无法跨时间形成个体模型', ours: '教育记忆模型' },
        { miss: '优化回答，不优化人的成长', ours: '师者智能大模型' },
      ] as const,
    },
    perception: {
      eyebrow: 'MM-Perception · 全息多模态理解',
      title: '把课堂还原为可计算的\n"人—知识—情境"状态。',
      inputLabel: '输入',
      inputs: ['语音', '语言', '语调', '视频', '板书', '课件', '提问', '停顿', '标记', '作答行为'] as const,
      techLabel: '核心技术',
      tech: [
        '长时课堂多模态时序对齐',
        '语义、声学、视觉与交互信号联合建模',
        '开放词汇情感理解',
        '多模态证据定位与自然语言解释',
        '课中低延迟实时转写，开口即定稿',
      ] as const,
      outputLabel: '输出',
      outputName: 'Classroom State Representation',
      outputParts: ['知识状态', '认知状态', '情感状态', '证据位置'] as const,
      award: 'ACM Multimedia 2025 · MER2025',
      awardDetail: 'MER-DES 描述式多模态情感理解赛道 · 第一名',
      awardNote: '验证了团队在多模态情感证据提取与开放式情感推理上的领先能力。',
    },
    memory: {
      eyebrow: 'MM-Memory · 教育记忆模型',
      title: '从学习事件流中，形成\n可更新的个体模型。',
      inputLabel: '输入',
      input: '课堂状态 + 提问 + 错误 + 练习结果 + 用户反馈',
      layersLabel: '记忆架构',
      layers: [
        { en: 'Episodic Memory', cn: '情节记忆', body: '保留某节课、某次错误的完整现场。' },
        { en: 'Semantic Memory', cn: '语义记忆', body: '提炼知识掌握与概念关系。' },
        { en: 'Cognitive Memory', cn: '认知记忆', body: '建模长期困惑、推理习惯与理解方式。' },
        { en: 'Affective Memory', cn: '情感记忆', body: '建模情感状态随场景和时间的变化。' },
        { en: 'Evidence Layer', cn: '证据层', body: '每条长期理解，都可以回到原始证据。' },
      ] as const,
      questionsLabel: '记忆要回答的五个问题',
      questions: ['什么值得写入？', '什么时候应该更新？', '发生冲突相信什么？', '什么已经过期？', '当前任务应该读取什么？'] as const,
      note: '教育记忆不是"记得越多越好"。',
      outputLabel: '输出',
      outputName: 'Dynamic Learner Model',
      outputBody: '可追溯、可更新、可纠正的学习者状态。',
    },
    teacher: {
      eyebrow: 'MM-Teacher · 师者智能大模型',
      title: '从"生成回答"，升级为\n"选择教学行动"。',
      inputLabel: '输入',
      inputs: ['当前课堂状态', '个体长期记忆', '学习目标', '历史教学结果'] as const,
      actionsLabel: '在多个教学行动中，选择此刻最合适的一种',
      actions: ['解释', '举例', '追问', '诊断', '练习', '提示', '挑战', '鼓励', '等待', '回放', '连接过去经验'] as const,
      objectivesLabel: '优化目标',
      objectives: [
        { label: '传统语言模型', formula: 'maximize P(next token)' },
        { label: '传统任务型 Agent', formula: 'maximize task completion' },
        { label: '师者智能模型', formula: 'maximize long-horizon learner development' },
      ] as const,
      objectivesNote: '同时优化：知识掌握、迁移能力、学习效率、情感状态、自主学习能力与长期成长结果。',
      outputLabel: '输出',
      outputName: 'Teaching Policy',
      outputBody: '对这个人，此刻最合适的下一步行动。',
      punch: '这才是"师者智能大模型"的技术含义——\n而不是一个更温暖的聊天模型。',
    },
    flywheel: {
      eyebrow: '训练闭环',
      title: '最稀缺的数据结构：\n状态—干预—结果。',
      steps: ['老师讲了什么', '学生当时处于什么状态', 'AI 采取了什么教学行动', '学生之后是否真正学会', '更新模型与个体记忆'] as const,
      center: '状态\n干预\n结果',
      body: '互联网语料只有"问题—答案"；真实课堂给出更稀缺的"状态—干预—结果"。',
      punch: '值钱的不是录音，是教学行动与学习结果之间的反馈信号。',
    },
    product: {
      eyebrow: '产品入口',
      title: '师者智能的\n第一个产品现场。',
      userLabel: '用户今天获得',
      userItems: ['真正听过课的 AI 同学', '基于课堂原话与板书的回答', '困惑定位、时间回跳与证据引用', '基于真实课堂生成的练习和复习', '跨课堂持续积累的个人学习上下文'] as const,
      systemLabel: '技术系统今天获得',
      systemItems: ['连续多模态课堂输入', '真实学习行为', '个体状态变化', '教学干预反馈', '长期学习结果'] as const,
      punch: 'MeetMind 是师者智能的产品入口、数据闭环与真实评测场。',
    },
    moat: {
      eyebrow: '技术壁垒',
      title: '三层技术，\n共同形成壁垒。',
      formula: ['多模态感知能力', '教育长期记忆', '教学决策闭环'] as const,
      formulaResult: '师者智能',
      items: [
        { title: '算法壁垒', body: '多模态情感推理、教育记忆与教学策略模型。' },
        { title: '数据结构壁垒', body: '不是普通内容数据，而是"状态—干预—结果"的长期序列。' },
        { title: '评测壁垒', body: '能够同时评估感知、记忆、教学行动和长期学习效果。' },
        { title: '产品闭环壁垒', body: '真实课堂中持续产生输入、反馈与验证结果。' },
      ] as const,
    },
    roadmap: {
      eyebrow: '路线图',
      title: '从师者智能，\n到人格智能平台。',
      phases: [
        { phase: 'Phase 1', title: '全息多模态理解' },
        { phase: 'Phase 2', title: '教育记忆模型' },
        { phase: 'Phase 3', title: '师者智能大模型' },
        { phase: 'Phase 4', title: '人格智能平台' },
      ] as const,
      punch: '情感智能理解一个人的当下；人格智能理解一个人的连续性；师者智能让这种理解产生有益于人的行动。',
    },
    finalCta: {
      title: '想看真实链路\n或合作方案？',
      body: '我们愿意讨论技术，而不是只展示一张架构图。',
      productAction: '先体验产品',
      contactAction: '联系 MeetMind',
      contactHref: 'mailto:originedu@meetmind.online',
    },
    footer: {
      label: 'MeetMind Technology',
      product: '产品首页',
      app: '打开产品',
      copyright: '© 2026 MeetMind',
    },
  },
} as const;

export type LandingCopy = typeof LANDING_COPY;
