/**
 * copy.ts — 用户面可见文案的单一真相源。
 *
 * 为什么要有这个文件：
 *   过去散在 10+ 个组件里的字符串里夹带了"回声卡 / 酿 / 预知气泡 / 工坊"
 *   这类内部术语，被用户看到时跳戏。把所有用户可见的文案汇总在这里，
 *   才能以"顶级 UI/UX 设计师"的视角一次性审过口吻、去掉行业黑话。
 *
 * 口吻原则（M8-agent-native）：
 *   - 角色：一个叫"同学"的 AI 同桌。像朋友，不像老师，不像客服
 *   - 说话方式：安静、直接、克制
 *   - 禁用词：回声卡 / 酿 / 预知气泡 / 工坊 / 研判 / 引擎 / 引导
 *   - 首选词：收藏 / 整理 / 情报 / 应用 / 同学
 *
 * 使用约定：
 *   - 所有出现在用户界面（非日志/埋点）的字符串必须 import { COPY }
 *   - 新增字符串时先找有没有相近语义的键可以复用，避免二次碎片化
 *   - 复杂占位符用函数而非模板字符串，便于测试
 */

export const COPY = {
  identity: {
    productName: 'MeetMind',
    name: '同学',
    tagline: '真正懂你在学什么的 AI 同学',
    subtagline: '理解你的课堂、资料和目标，陪你学懂当下，也发现下一步值得看的内容。',
  },

  cta: {
    demo: '看一节示例课',
    record: '开始一节课',
    ask: '问同学',
  },

  navigation: {
    back: '返回',
    classroom: '课堂',
    collection: '收集',
    search: '问同学',
    allCollections: '全部收集',
  },

  globalAsk: {
    title: '问同学',
    subtitle: '相关课堂、资料和你的上下文会自动接上。',
    quickMode: '直接问',
    deepMode: '一起学',
    memoryAction: '我的上下文',
    newConversation: '新对话',
    historyRestored: '已接回上次对话',
    historyLoading: '正在接回上次对话…',
    freshConversation: '新的对话',
    emptyTitle: '想问什么，直接说。',
    emptyBody: '相关课堂、资料和你的上下文会自动接上。',
    composerQuick: '问任何正在学、正在想的事',
    composerDeep: '说说这次想真正学会什么',
    send: '发送',
    stop: '停止',
    preparingIntent: '正在接上相关内容…',
    intentEyebrow: '先对齐一件事',
    intentProgress: (current: number, total: number): string => `${current} / ${total}`,
    intentSingle: '选一个就好',
    intentMultiple: '可以多选',
    intentCancel: '直接开始',
    intentBack: '上一步',
    intentContinue: '继续',
    intentResolve: '继续',
    intentStart: '开始学习',
    intentFirstStep: '先从这里开始',
    approachUnderstand: '理解清楚',
    approachPractice: '练到会用',
    approachSynthesize: '串成体系',
    approachCreate: '做出结果',
    contextPersonal: '用长期上下文',
    contextCurrent: '用当前内容',
    contextMixed: '两边一起看',
    contextStatus: '已接入',
    contextCurrentCount: (count: number): string => `${count} 份当前材料`,
    contextRecentCount: (count: number): string => `${count} 条最近学习`,
    contextMemoryCount: (count: number): string => `${count} 条长期记忆`,
    contextEmpty: '这次先从你的问题开始',
    progressEyebrow: 'MeetMind 更新了对你的理解',
    progressHint: '这些理解会随着之后的学习继续调整。',
    progressDismiss: '这次不记',
    progressSave: '记住确认的',
    progressSaved: '已经记下，也可以随时纠正',
    memoryTitle: '我的上下文',
    memoryBack: '返回',
    memoryUnderstandingTab: '对我的理解',
    memoryCoursesTab: '课堂上下文',
    memoryRecentTab: '客观记录',
    memoryUnderstandingTitle: 'MeetMind 记得的你',
    courseContextTitle: '我的课程',
    courseContextEmpty: '录下一节课后，课程会自动在这里出现。',
    courseContextLessons: (count: number): string => `${count} 节课`,
    courseContextMinutes: (count: number): string => `${count} 分钟`,
    courseContextActive: '正在参考',
    courseContextPaused: '已暂停参考',
    courseContextSuggested: '待确认',
    courseContextUnclassified: '单节课堂',
    courseContextDetached: '已移出',
    courseContextRename: '改课程名',
    courseContextRenameHint: '例如：线性代数',
    courseContextSave: '确认',
    courseContextCancel: '取消',
    courseContextPause: '暂不参考这门课',
    courseContextResume: '重新参考这门课',
    courseContextDetails: '查看课堂',
    courseContextCollapse: '收起课堂',
    courseContextConfirm: '确认属于同一门课',
    courseContextDetach: '移出',
    courseContextDetachTitle: (title: string): string => `将“${title}”移出这门课`,
    courseContextRestore: '放回原课程',
    courseContextCheatsheet: '单元速查表',
    courseContextBackToCourse: '返回课程',
    courseContextCheatsheetNeedsTranscript: (count: number): string => count === 0
      ? '这些课堂还没有可用原文。'
      : `目前只有 ${count} 节课有可用原文，至少需要两节。`,
    courseContextChooseLessons: '这次要带上哪些课？',
    courseContextChooseLessonsHint: '先选同一单元或同一考试范围；最近四节已替你选好。',
    courseContextSelectAll: '全选',
    courseContextBeginCheatsheet: (count: number): string => `用这 ${count} 节课整理`,
    courseContextCheatsheetLoading: '正在把这几节课压成一份纸面速查表',
    courseContextCheatsheetNotReady: '这些课堂原文还太少，暂时做不出可靠的考试速查表。原始课堂已经保留，之后可以再把更多课一起选进来。',
    courseContextRecording: '录音',
    courseContextUpload: '上传',
    courseContextVideo: '视频',
    courseContextFallbackTitle: (month: number, day: number): string => `${month} 月 ${day} 日的课`,
    courseContextLessonFallbackTitle: (month: number, day: number, time: string): string => `${month} 月 ${day} 日 ${time} 的课`,
    courseContextScheduleTitle: (weekday: string): string => `${weekday}的课`,
    courseContextRecurring: (weekday: string, time: string): string => `常在${weekday} ${time} 上课`,
    courseAssessmentAdd: '这门课有考试',
    courseAssessmentEditTitle: '考试',
    courseAssessmentDefaultName: (courseTitle: string): string => `${courseTitle}考试`,
    courseAssessmentName: '考试名称',
    courseAssessmentNameHint: '例如：期末考试',
    courseAssessmentDate: '考试日期',
    courseAssessmentMode: '考试方式',
    courseAssessmentUnknown: '还不确定',
    courseAssessmentClosedBook: '闭卷',
    courseAssessmentOpenBook: '开卷',
    courseAssessmentScope: '考试范围',
    courseAssessmentScopeHint: '可选：粘贴老师公布的范围或大纲',
    courseAssessmentHasScope: '已有范围',
    courseAssessmentSave: '记下',
    courseAssessmentStop: '不再准备',
    courseAssessmentEdit: '修改考试信息',
    courseAssessmentPrepare: '做速查表',
    courseAssessmentChooseScope: '哪些课在考试范围内？',
    memoryKindPreference: '学习方式',
    memoryKindStrength: '正在形成的能力',
    memoryKindChallenge: '还在弄懂',
    memoryKindTopic: '正在关注',
    memoryKindProgress: '最近进展',
    memorySourceUser: '你告诉 MeetMind 的',
    memorySourceAi: '从你的学习互动中理解到的',
    memoryCorrection: '不太准确',
    memoryAddContext: '补充一下',
    memoryCorrectionHint: '换成更准确的说法',
    memoryCorrectionSave: '改好了',
    memoryCorrectionCancel: '取消',
    memoryMore: '更多操作',
    memoryStopUsing: '暂不参考',
    memoryUseAgain: '重新参考',
    memoryForget: '忘记这条',
    memoryTalkPrompt: '关于我，想补充或纠正的是：',
    memoryEmpty: '还没有形成稳定的理解。先正常学习就好，MeetMind 会从真实过程里慢慢认识你。',
    memoryPaused: '已不再参考',
    recentTitle: '最近学习现场',
    recentEmpty: '最近还没有可恢复的学习活动。',
    recentKindConversation: '一次对话',
    recentKindLesson: '一节课堂',
    recentKindApp: '一次练习',
    recentKindCapture: '一份学习材料',
    recentShowAll: (count: number) => `查看全部 ${count} 条学习现场`,
    recentCollapse: '收起较早记录',
    threadTitle: '上次还在继续',
    threadResume: '接着学',
    threadComplete: '这条学完了',
    preparingError: '这次没理解准，先直接回答你。',
    refiningError: '先按目前的理解开始，之后还可以随时调整。',
    responseError: '刚才没有接上，再发一次就好。',
    sourceContext: '刚刚在看的内容',
    sourceCurrentLesson: '当前课堂转录',
    openSource: '打开原内容',
    close: '关闭问同学',
    assistantLabel: 'MeetMind 回答',
    userLabel: '你的问题',
    thinking: '正在把上下文接起来…',
    recentConversation: '问同学的对话',
    recentDeepSession: '一起学的对话',
    recoveryEyebrow: '接回学习现场',
    recoveryTitle: '不用重新开始',
    recoveryBody: 'MeetMind 留住了上次的脉络，回来可以直接接着走。',
    recoveryResume: '接着上次学',
    recoveryRecent: '最近停在这里',
    appActivity: (name: string) => `完成了「${name}」`,
    appResultSummary: (count: number) => `生成了 ${count} 条可继续使用的学习内容`,
  },

  tutor: {
    emptyAfterName: '在这里。',
    reviewStarters: ['先讲清这节课的主线', '从我标记的地方开始'] as const,
  },

  actionList: {
    title: '今晚行动清单',
    emptyTitle: '还没有行动项',
    emptyBody: '标记一处困惑后，同学会把下一步放在这里。',
    completedTitle: '今天先到这里',
    completedBody: '行动项已经全部完成。',
    closeHint: '按 ESC 或点击空白处关闭',
  },

  collection: {
    askClassmate: '问同学',
    emptyTitle: '想到什么，就留在这里。',
    deleteMemoryWarning: '删除后，这条内容不会再进入同学的回答、后续情报和个人上下文。',
    permanentDeleteWarning: '彻底删除后，这条内容不会再进入同学的回答、后续情报和个人上下文。',
  },

  login: {
    subtitle: '真正懂你在学什么的 AI 同学',
    guestCta: '先试听一节课',
  },

  loading: {
    preparing: '正在准备课堂空间',
    restoring: '正在接回你的学习现场',
    entering: '马上进入',
    fallback: '正在准备学习空间',
  },

  hero: {
    eyebrow: 'MEETMIND · AI 同学',
    title: '陪你听懂每一节课。',
    subtitle: '老师讲到哪，我就听到哪。卡住时当场问；下课后，每个答案都能回到原话。',
    sideHint: '先听 90 秒示例课',
    evidencePromise: '回答有依据，点击时间就能回到老师原话。',
    proofStatus: '正在一起听',
    proofQuote: 'The exact timing is still up in the air.',
    proofTime: '00:31',
    proofLabel: '同学听懂了',
    proofAnswer: '这里不是“在空中”，而是“具体时间还没有决定”。',
    proofAction: '进入这节示例课',
  },

  lesson: {
    summaryReady: '笔记总结',
    keyPoints: '重点',
    reviewed: '已复习',
    materials: (count: number): string => `${count} 份材料`,
    actionReady: '继续复习',
    actionReviewed: '再看一遍',
    actionProcessing: '整理中',
    actionFailed: '原声已保留',
    actionUpcoming: '准备上课',
  },

  classroomHome: {
    commandEyebrow: '今天',
    title: '今天，继续学懂一件事。',
    outcomeTitle: '内容进来之后',
    outcomeHint: '不只保存，还会继续变成能用的学习结果。',
    today: '今天',
    yesterday: '昨天',
    active: '正在上课',
    launchpadTitle: '补充学习上下文',
    launchpadHint: '材料和问题会自动接到相关课堂',
    actionRecordTitle: '开始一节课',
    actionRecordBody: '录线下课、网课或讨论，边听边形成课堂脉络。',
    actionRecordLabel: '选择声音开始',
    actionMaterialTitle: '放入材料',
    actionMaterialBody: '文档、网页、音视频会自动接到相关课堂和目标。',
    actionMaterialLabel: '选择文件或链接',
    actionSearchTitle: '问课堂和资料',
    actionSearchBody: '带上课堂、资料和目标，直接说你想弄懂什么。',
    actionSearchLabel: '搜索我的内容',
  },

  sourceType: {
    audio: '录音',
    video: '视频',
    image: '图片',
    document: '文章',
    text: '笔记',
  },

  sourceOrigin: {
    quickNote: '速记',
    wechat: '从微信发来',
    wechatArticle: '微信公众号',
    bilibili: '哔哩哔哩',
    youtube: 'YouTube',
  },

  sourceState: {
    extracting: '正在读取正文',
    complete: '正文完整',
    partial: '仅取得摘要',
    linkOnly: '已保存原链接',
    failed: '读取失败，原链接已保留',
  },

  sourceReader: {
    saved: '已收下',
    untitled: '未命名内容',
    openOriginal: '查看原文',
    noBody: '正文暂时没有读取出来，原始内容仍然保留。',
  },

  listening: {
    idle: '我在。',
    hearing: '我在听。',
  },

  classroomFlow: {
    eyebrow: '课堂脉络',
    listeningTitle: '等老师进入正题。',
    understanding: '正在接住刚才这段。',
    refreshing: '正在接住刚才这段',
    now: '正在讲',
    recent: '刚才怎么走到这里',
    recentHint: '只留与当前有关的推进',
    keep: '留到课后',
    mobileFlow: '脉络',
    mobileTranscript: '原话',
    kindDefinition: '定义',
    kindFormula: '公式',
    kindExample: '例子',
    kindQuestion: '待弄清',
    kindContrast: '对比',
    kindConclusion: '结论',
    kindOther: '值得回来',
  },

  stages: {
    /** v3.0：放弃假分阶段叙事，改为 Octo Buddy 听课的诚实表达
     *  app loading 文案根据 appName 动态拼，用 listening 系列 */
    reading: '正在读你的课堂',
    selecting: '正在挑核心',
    composing: '正在排版',
    slow: '稍等一下——内容多的时候我也要再想想',
    /** v3.0 新版 loading 文案 */
    listenStart: (appName: string): string => `在听这节课，给你${appName}`,
    listenSlow: '内容有点多，我多听一会儿',
    listenVerySlow: '还在听——再给我一点时间',
  },

  stop: {
    heard: '这节课我听完了。',
    /**
     * 停止后的总结一句话。
     * 例："共 47 句，标了 2 处你标的困惑。"
     */
    summary: (sentences: number, confusions: number): string => {
      if (sentences <= 0) return '这次只录到很少内容。';
      const base = `共 ${sentences} 句`;
      if (confusions > 0) return `${base}，标了 ${confusions} 处你标的困惑。`;
      return `${base}。`;
    },
    suggestCheatsheet: '要不要我整一张速查表？',
    actionMakeCheatsheet: '整速查表',
    actionViewTranscript: '看文字',
  },

  octoBuddy: {
    idle: '同学在这',
    listening: '陪你听课',
    thinking: '我想一下',
    happy: '接住了',
    surprised: '哎？',
    love: '我在',
    angry: '别一直戳我',
    sleeping: '待命中',
    openHint: '点开一起听',
    openPanel: '打开同学面板',
    dragHint: '单击逗我 · 双击打开同学 · 可拖动',
    hoverLine: '我看到你啦',
    patHappy: '嘿嘿，我在',
    patLove: '今天也一起学',
    patSurprised: '哎？轻一点',
    patAngry: '别一直戳我',
    wakeLine: '醒啦醒啦',
  },

  companion: {
    placeholderIdle: '问问同学…',
    placeholderListening: '老师刚说的那个啥意思？',
    shortcutHint: '有问题？⌘K 问同学',
    newCourseGreet: '我在这里。等你录第一节课，我就开始陪你。',
    defaultLightPrompts: ['刚才那句我没跟上', '这段在讲什么？', '帮我抓一下题眼'] as const,
    quickRecap: '刚才那段',
    quickRecapQuestion: '刚才那段讲了什么？',
    quickCatchUp: '我没跟上',
    quickCatchUpQuestion: '我没跟上，帮我接一下主线。',
    quickMark: '记一下',
    idleStatus: '待命中',
    afterClassStatus: '听完了',
    listeningStarter: '卡住直接问。',
    afterClassStarter: '听完了，换我带你练一下。',
    pending: '正在想…',
    emptyListeningPrimary: '我在听，有问题随时问我。',
    emptyListeningSecondary: '我会把刚才那段记住，你不用急着整理。',
    emptyIdlePrimary: '把第一节课录下来，我们就认识了。',
    actionPrompt: '也可以让我直接整理',
    contentPrompt: '已经有内容？试试',
    foresightCount: (count: number): string => `${count} 个预感`,
    foresightDismiss: '划掉',
    foresightAccept: '就这个 · 问下去',
    errorTitle: '同学刚刚没接上',
    errorBody: '只影响这次对话，你的课堂和复习内容都还在。',
    errorRetry: '重新连接',
  },

  recording: {
    sourcePrompt: '这节课的声音从哪里来？',
    sourceMic: '麦克风',
    sourceSystem: '电脑声音',
    sourceMixed: '两路都录',
    sourceMicHint: '线下课',
    sourceSystemShortHint: '在线课程',
    sourceMixedHint: '网课＋自己提问',
    sourceSystemHint: '开始后，在系统窗口勾选“分享音频”。',
    activeStatus: (source: string): string => `正在听 · ${source} · 点开看实时文字`,
    /** mixed 模式系统音频采集失败、降级为纯麦克风时提示 */
    downgradeFromMixed: '电脑声音没录到，只用麦克风在录',
    startFailedFallback: '没有接上录音设备，请检查麦克风权限后再试。',
    recorderNotReady: '录音组件还没准备好，请再点一次。',
    startFailed: (reason: string): string => `还没有开始录音。${reason}`,
    finished: '这节课收好了',
    finalizingTranscript: (count: number, enhancedCount = 0): string =>
      `实时文字已收下，正在用原声定稿 · ${count} 段${enhancedCount > 0 ? ` · 已优化 ${enhancedCount} 段` : ''}`,
  },

  mobileComposer: {
    placeholder: '发一句想法，贴个链接…',
    attach: '添加文件',
    send: '发送',
    startDictation: '开始语音听写',
    stopDictation: '停止语音听写',
    connecting: '正在连接麦克风…',
    listening: '我在听，说完再点一下',
  },

  mobileHome: {
    commandCenterLabel: '学习控制台',
    eyebrow: '今天，从这里开始',
    contextStatus: (count: number): string => count > 0
      ? `已接上 ${count} 段上下文`
      : '还没有上下文',
    title: '今天，学懂一件事。',
    record: '录一节课',
    recordHint: '实时听懂',
    addMaterial: '放入资料',
    photo: '拍板书',
    search: '问同学',
    livePromise: '课中看见脉络',
    afterClassPromise: '课后继续练习',
    capabilityLabel: '从输入到结果，一条学习链路',
    capabilityFlow: '课堂脉络',
    capabilityQa: '资料问答',
    capabilityFlashcards: '闪卡',
    capabilityQuiz: '测验',
    capabilityMindmap: '思维导图',
    capabilityFeed: '今日发现',
    intelligenceLabel: '今日发现',
    intelligenceFallback: '从最近的学习里，找到一条值得继续的线索',
    intelligenceAction: '查看',
    recentLabel: '最近上下文',
    recentEmpty: '还没有内容',
    emptyRole: '懂你上下文的 AI 同学',
    emptyEyebrow: '先交给我一段真实学习',
    emptyTitle: '陪你听懂每一节课。',
    emptyBody: '录下学习现场，课中理清脉络，课后继续练会。',
    emptyRecordHint: '边听边形成课堂脉络',
    tryDemo: '试听 90 秒',
    demoPlay: '播放声音',
    demoPause: '暂停',
    demoFinished: '试听结束，可以去看课后练习了',
    demoFinish: '结束试听，看课后',
    demoReviewStatus: '试听课',
    demoFailed: '试听还没加载好，再试一次',
    emptyOutcomeTitle: '回来时，你会得到',
    emptyOutcomeFlow: '课堂脉络',
    emptyOutcomeAnswer: '有根解释',
    emptyOutcomePractice: '课后练习',
    emptyBrowse: '先看看完整工作台',
  },

  echoShare: {
    title: '分享这条笔记',
    open: '分享',
    generating: '正在做图片…',
    error: '图片没做出来，再试一次',
    close: '关闭',
    imageAlt: '课堂笔记分享图',
    saveImage: '保存图片',
    nativeShare: '分享给同学',
    sharing: '分享中…',
    copyText: '复制文案',
    saved: '图片已保存',
    copied: '文案已复制',
    copyFailed: '没复制上，请手动保存图片',
    saveFallback: '没保存上，请长按图片保存',
    hint: '也可以长按图片保存',
  },

  flashcardsShare: {
    title: 'MeetMind 试听课闪卡',
    open: '分享试听成果',
    sharing: '分享中…',
    copied: '成果文案已复制',
    failed: '没分享出去，请手动复制',
    summaryTitle: '这节试听课已经变成闪卡',
    summaryBody: (count: number): string => `MeetMind 已经把它整理成 ${count} 张可练习的闪卡。`,
  },

  apps: {
    inlineSource: '已放进对话',
    placeholder: {
      defaultAppName: '应用内容',
      workingElapsed: (seconds: number): string => `同学正在整理 · ${seconds.toString().padStart(2, '0')}s`,
      emptyTitle: (appName: string): string => `还没有${appName}`,
      emptyBody: (appName: string): string => `回到应用目录开始整理${appName}，完成后会直接出现在这里。`,
      remake: '再做一版',
      back: '返回应用',
      failedTitle: (appName: string): string => `${appName}刚才没做好`,
      failedBody: '网络可能有点慢，原课堂内容没有受到影响。',
      retry: '再试一次',
      tryAnother: '看看其他方式',
    },
    matrix: {
      eyebrow: '基于这节课',
      title: '接下来怎么学',
      subtitle: '先选一个当下最需要的动作。同学会在后台做好，你可以留在这里继续看。',
      recommendedTitle: '现在最适合',
      recommendedHint: '根据这节课的内容和你留下的标记排序，不替你做决定。',
      allTitle: '其他学习方式',
      availableTitle: '可以这样继续',
      previewTitle: '其他内容可以这样学',
      readinessLabel: '学习应用判断',
      assessing: '正在判断这段内容适合怎么学',
      recommendedByContent: '这段内容已经足以支撑这个学习动作。',
      insufficientTitle: '先保留这段原话',
      insufficientBody: '内容还太少。继续记录后，合适的学习方式会自然出现。',
      notLearningTitle: '这段内容不用加工',
      notLearningBody: '它更像普通交流，保留原话就够了。',
      unreliableTitle: '先把原话听清',
      unreliableBody: '当前转录还不稳定，暂时不把它整理成学习结论。',
      executeNotReady: '这段内容还不足以形成可靠的学习应用。',
      executeNotSuitable: '这个学习动作不适合当前内容，换一种方式更可靠。',
      executeNeedsMultipleLessons: '至少选择两节属于同一门课的课堂。',
      noContent: '先录下或放入一段课堂内容。',
      generateFailed: '这次没做好，稍后可以再试一次。',
      generated: (appName: string): string => `${appName}做好了`,
      openResult: '打开',
      timeout: '等得有点久，稍后可以再试一次。',
      timeoutFor: (appName: string): string => `${appName}还没做好，稍后可以再试一次`,
      cancelled: '已取消',
      cancelledFor: (appName: string): string => `已取消${appName}`,
      failedFor: (appName: string): string => `${appName}这次没做好`,
      contextBasis: (segments: number, anchors: number, difficulties: number): string => {
        const parts = [`${segments} 段课堂内容`];
        if (anchors > 0) parts.push(`${anchors} 处标记`);
        if (difficulties > 0) parts.push(`${difficulties} 个难点`);
        return parts.join(' · ');
      },
      summary: (total: number, done: number, running: number, failed: number): string => (
        `${total} 种学习方式 · 已做好 ${done}${running > 0 ? ` · 正在做 ${running}` : ''}${failed > 0 ? ` · 待处理 ${failed}` : ''}`
      ),
      recommendedForConfusion: (count: number): string => `你留下了 ${count} 处标记，先检验能不能讲清楚。`,
      recommendedForDifficulty: (count: number): string => `这节课有 ${count} 个难点，先把关键概念练到能回忆。`,
      recommendedForStructure: '这节课内容较长，先看清主干和分支。',
      recommendedDefault: '先把这节课压成一页，最快建立整体印象。',
      start: '先做一版',
      open: '继续使用',
      openImage: '查看图片',
      progress: '查看进度',
      retry: '再试一次',
      tryAnother: '看看其他方式',
      remake: '再做一版',
      ready: '做好了',
      waiting: '待开始',
      notAvailable: '暂不可用',
      failed: '没做好',
      running: '正在做',
      workingOn: (action: string): string => `${action}，可以先返回继续看这节课`,
      failedWithoutLoss: '这次没做好，原课堂内容没有受到影响。',
      recommended: '适合现在',
      taskTray: '学习内容',
      taskPanelTitle: '正在准备与已经做好的内容',
      taskRunning: (count: number): string => `正在做 ${count}`,
      taskDone: (count: number): string => `已做好 ${count}`,
      taskNeedsAttention: (count: number): string => `待处理 ${count}`,
      collapse: '收起',
      cancel: '取消',
      noTasks: '还没有正在准备的内容。',
      infographicPreview: '信息图预览',
      downloadImage: '保存图片',
      closePreview: '关闭',
      imageDownloaded: '图片已保存',
      imageDownloadFailed: '没保存上，请长按图片保存',
      windowUnavailableTitle: '这个学习方式暂时打不开',
      windowUnavailableBody: '回到这节课，其他学习方式仍然可以继续使用。',
      windowLoading: '正在接回这节课',
      windowEmptyTitle: '先选一节课',
      windowEmptyBody: '学习应用需要基于真实课堂内容，才不会生成没有依据的结论。',
      windowBackToClassroom: '回到课堂',
      windowErrorTitle: '这次没有接上',
      windowErrorBody: '课堂原文仍然保留着，回到学习方式后可以再试一次。',
      windowLoadTimeout: '这节课暂时没有接上，请返回后再试一次。',
      windowLoadFailed: '这节课暂时没有接上',
      mobileTitle: '这节课，接下来怎么学',
      mobileSubtitle: '选一种学习动作，同学会直接基于这节课开始。',
      backToMatrix: '所有学习方式',
      workspaceSubtitle: (action: string, bestFor: string): string => `${action} · ${bestFor}`,
      catalogMeta: {
        cheatsheet: { action: '带进考场', bestFor: '多节课已组成单元，或正在准备允许携带资料的考试', time: '排版约 10–20 分钟' },
        quiz: { action: '检验理解', bestFor: '想知道自己是真懂，还是只是看懂了', time: '作答约 5–8 分钟' },
        flashcards: { action: '记住核心', bestFor: '概念、术语和公式需要反复回忆', time: '练习约 5 分钟' },
        mindmap: { action: '看清结构', bestFor: '内容较多，想分清主干、关系和层次', time: '浏览约 2 分钟' },
        'audio-overview': { action: '换种方式再听', bestFor: '通勤或走路时，想用对话重新理解', time: '收听约 6–10 分钟' },
        infographic: { action: '做成一张图', bestFor: '想分享、展示，或用视觉方式记住', time: '查看约 2 分钟' },
      },
    },
    infographic: {
      appName: '课堂信息图',
      preparing: '正在把这节课变成一张图',
      preparingHint: '完成后会直接显示成品。',
      finished: '做好了',
      fit: '看全图',
      full: '看细节',
      save: '保存图片',
      adjust: '调整',
      createTitle: '把这节课变成一张图',
      createHint: '选尺寸和感觉，其他交给同学。',
      adjustTitle: '想换一种呈现？',
      adjustHint: '只改你在意的部分，其余交给同学。',
      orientation: '尺寸',
      style: '视觉感觉',
      custom: '还想强调什么',
      customPlaceholder: '例如：突出 3 个结论，适合手机查看',
      generate: '生成信息图',
      regenerate: '按这个方向重做',
      serviceUnavailable: '图片服务暂时不可用',
      serviceUnavailableBody: '课堂内容和草案已经保留，稍后再试即可。',
      downloaded: '图片已保存',
      downloadFailed: '没保存上，请长按图片保存',
      missingContext: '当前内容还不足以生成可靠的信息图。',
      generateFailed: '这次没有生成成功，课堂内容仍然保留着。',
      readableReady: '先给你一张可读版',
      readableHint: '图片还没做好，课堂重点不用跟着等。',
      copyReadable: '复制要点',
      readableCopied: '要点已复制',
      readableCopyFailed: '没复制上，可以长按选择文字。',
      retryImage: '再试一次图片',
    },
    mindmap: {
      mobileGestureHint: '拖动查看 · 点 + 放大',
      desktopGestureHint: '滚轮缩放 · 拖拽平移',
    },
    flashcards: {
      appName: '闪卡训练',
      completeTitle: '这一轮完成了',
      roundSummary: (count: number): string => `共回忆 ${count} 张`,
      recallRate: '本轮记住',
      got: '记住了',
      missed: '再来一次',
      gotCount: '记住了',
      missedCount: '还要练',
      reviewMissed: (count: number): string => `只练没记住的 ${count} 张`,
      restart: '重练全部',
      reveal: '想好后翻面',
      answer: '参考答案',
      showHint: '看一点提示',
      recallFirst: '先在心里回答，再翻面看答案',
      keyboardHint: '空格翻面 · 方向键切换',
      previous: '上一张',
      next: '下一张',
      evidenceAt: (time: string): string => `来自课堂 ${time}`,
      returnToEvidenceAt: (time: string): string => `回到课堂 ${time}`,
    },
    quiz: {
      appName: '课堂测验',
      keyboardHint: '方向键切换题目',
      previous: '上一题',
      next: '下一题',
      jumpTo: (index: number): string => `跳到第 ${index} 题`,
      answered: (done: number, total: number): string => `${done} / ${total} 已完成`,
      understood: '答稳了',
      revisit: '再看看',
      subjectivePrompt: '先在心里说出答案，再对照参考。',
      referenceAnswer: '参考答案',
      referenceFallback: '回到原片段核对关键内容。',
      selfRate: '对照后，我：',
      selfCorrect: '答到要点',
      selfWrong: '还没答上',
      correct: '答对了',
      wrong: '再看看',
      correctAnswer: (answer: string): string => `答案：${answer}`,
      revealReference: '对照答案',
      confirmAnswer: '确认答案',
      nextQuestion: '下一题',
      viewResult: '看这一轮',
      completeTitle: '这一轮检验完成',
      completeMeta: (count: number, minutes: string): string => `共 ${count} 题 · 用时 ${minutes} 分钟`,
      recallRate: '本轮答稳',
      solidCount: '答稳了',
      revisitCount: '还要回看',
      missedReview: '需要回看的题',
      reviewMissed: (count: number): string => `只练需要回看的 ${count} 题`,
      restart: '重做全部',
      evidenceAt: (time: string): string => `来自课堂 ${time}`,
      returnToEvidenceAt: (time: string): string => `回到课堂 ${time}`,
    },
    podcast: {
      appName: '课堂播客',
      emptyBody: '开始整理后，会直接得到一版可以播放的课堂播客。',
      scriptCopied: '脚本已复制',
      copyFailed: '复制失败，请手动选择脚本内容',
      details: '脚本与章节',
      script: '播客脚本',
      copyScript: '复制脚本',
      chapter: (index: number): string => `章节 ${index}`,
      chapterEmpty: '这一章暂时没有摘要。',
      seekChapter: '回到课堂片段',
      audioGenerating: '正在准备音频',
      audioRetry: '音频没做好，点这里再试一次',
      audioGeneratingHint: '完成后这里会直接变成播放条。',
      audioRetryHint: '脚本已经保留，不需要重新来过。',
      audioRetryNoScriptHint: '课堂内容仍然保留，稍后可以直接再试。',
      activityAudioReady: '课堂播客已经可以播放，并保留了脚本与章节。',
      activityScriptReady: '音频还没做好，播客脚本与章节已经保留。',
      generating: '正在准备',
      retry: '再试一次',
    },
    cheatsheet: {
      appName: '考试速查表',
      emptyBody: '当前内容还不足以整理成可靠的速查表。继续记录后再回来看看。',
      focus: '重点',
      focusCount: (count: number): string => `重点 ${count}`,
      focusTitle: '课堂、大纲或真题明确强调的内容',
      seekTitle: (time: string): string => `回到课堂 ${time}`,
      hideItem: '暂时移除这条',
      expand: '展开',
      collapse: '收起，不放进打印页',
      removedCount: (count: number): string => `已移除 ${count} 条`,
      removedTitle: (count: number): string => `${count} 条已移除`,
      collapsedCount: (count: number): string => `已收起 · ${count} 条`,
      sectionCount: (sections: number, items: number): string => `${sections} 区 · ${items} 条`,
      density: (value: number): string => `约占一页 ${value}%`,
      overflow: (value: number): string => ` · 超出 ${value}%`,
      overflowHint: '内容超过一页，可以切到紧凑字号，或移除已经掌握的条目。',
      copied: '已复制',
      copyMarkdown: '复制文字',
      print: '打印 / 导出 PDF',
      printLayout: '打印排版',
      copyTitle: '复制文字，便于粘贴到笔记或发给同学',
      printTitle: '按当前纸张与分页设置打印或导出 PDF',
      settingSummary: (settings: {
        paperSize: 'a4' | 'letter';
        orientation: 'landscape' | 'portrait';
        sides: 'single' | 'duplex';
        sheetCount: number;
      }): string => {
        const paper = settings.paperSize === 'a4' ? 'A4' : 'Letter';
        const orientation = settings.orientation === 'landscape' ? '横向' : '纵向';
        const sheets = settings.sides === 'duplex' ? `${settings.sheetCount} 张双面` : `${settings.sheetCount} 页`;
        return `${paper} · ${orientation} · ${sheets}`;
      },
      pageUsage: (current: number, target: number): string => `${current} / ${target} 页`,
      pageOverflow: (count: number): string => `多出 ${count} 页；调小字号、增加纸张或删去已经掌握的内容。`,
      purpose: '用途',
      reviewPurpose: '考前整理',
      openBookPurpose: '带进考场',
      paper: '纸张',
      paperA4: 'A4',
      paperLetter: 'Letter',
      orientation: '方向',
      sheets: '纸张数',
      sheetCount: (count: number): string => `${count} 张`,
      sides: '打印面',
      singleSided: '单面',
      duplex: '双面',
      duplexHint: '导出两页后，在打印对话框中选择双面。',
      colorMode: '颜色',
      color: '彩色',
      mono: '黑白',
      allRemoved: '内容已全部移除，可以恢复后继续整理。',
      pageNumber: (current: number, total: number): string => `${current} / ${total}`,
      page: '页面',
      landscape: '横向',
      portrait: '纵向',
      fontSize: '字号',
      compact: '紧凑',
      standard: '标准',
      comfortable: '舒适',
      restore: '恢复全部',
      editItem: '编辑这条',
      editTerm: '术语',
      editBody: '解释',
      editFormula: '公式（可留空）',
      cancelEdit: '取消',
      saveEdit: '保存',
      syllabusSource: '考试大纲',
      pastPaperSource: (index: number): string => `真题 ${index}`,
    },
  },

  /**
   * 信息流（M15：替换笔记总结）
   * 基于个人上下文的 LLM 驱动信息流——同一节课不同人看到不同的内容。
   */
  feed: {
    /** tab 标签（单课复习态遗留，跨课程信息流改走侧栏抽屉） */
    tabLabel: '信息流',
    /** 侧栏「收集 → 相关信息」子导航文案 */
    relatedInfoLabel: '今日情报',
    /** 抽屉标题——替换原「笔记总结」 */
    drawerTitle: '今日情报',
    drawerSubtitle: '一半照见你正在关心的事，一半把真实的书、论文和新观点带进来。',
    todayBrief: '看见自己',
    internalDiscoveries: '看见自己',
    internalDiscoveriesHint: '从你的收藏、笔记和目标里，找到正在形成的方向。',
    externalDiscoveries: '向外看看',
    externalDiscoveriesHint: '真实来源，可直接打开；既有顺着目标深入，也有不同视角。',
    useful: '有用',
    notRelevant: '不相关',
    feedbackUseful: '已记下，以后多找这类内容',
    feedbackDismissed: '已减少这类推荐',
    refresh: '更新',
    addContext: '补一条线索',
    refreshing: '正在寻找与你有关的新内容',
    notGeneratedYet: '等待第一次发现',
    updatedJustNow: '刚刚更新',
    updatedMinutesAgo: (minutes: number): string => `${minutes} 分钟前更新`,
    updatedAt: (time: string): string => `今日 ${time} 更新`,
    refreshFailedKeepingPrevious: '这次没更新成，先保留上一版。',
    contextBasis: (captures: number, goals: number): string => (
      goals > 0 ? `基于 ${captures} 条收藏 · ${goals} 个当前目标` : `基于 ${captures} 条收藏`
    ),
    sourceCount: (count: number): string => `来自 ${count} 条收藏`,
    goalAlignment: (goal: string): string => `对齐目标「${goal}」`,
    /** 生成中（跨课程） */
    loading: '同学正在查找真实的书、论文和外部资料…',
    /** 空状态（没有收集内容） */
    empty: '还没有收集内容。先去收一节课或一篇文章，同学会自动整理方向。',
    /** 跨课程空态 */
    crossCourseEmptyTitle: '先留下几条你真正关心的内容。',
    crossCourseEmptyBody: '这里会先看见你正在形成的方向，再从外部找到真实可读的书、论文和不同观点。',
    /** 生成失败 */
    error: '没整理出来，再试一次',
    /** 重试按钮 */
    retry: '重新整理',
    /** 条目类型标签 */
    typeSummary: '你最近在意的',
    typeProbeNear: '同主题',
    typeProbeLateral: '相关方向',
    typeProbeBridge: '跨界',
    typeConfusionLink: '你标记的困惑',
    typeWebRecommend: '外部发现',
    typeBiliRecommend: '同学帮你找的',
    typeEcho: '同桌沉淀',
    /** echo 卡分享按钮 */
    shareEcho: '分享',
    /** 动作按钮 */
    actionJumpTimestamp: '跳回去听',
    actionMakeFlashcard: '做成闪卡',
    actionAskTutor: '让同学解释',
    actionReviewPrev: '看上节课',
    actionOpenCapture: '看这条收集',
    actionOpenExternal: '打开原文',
    actionOpenBilibili: '在 B站看',
    /** whyForYou 前缀 */
    whyPrefix: '为什么与你有关',
    differentPerspectivePrefix: '为什么值得换个角度',
    kindWeb: '文章',
    kindPaper: '论文',
    kindBook: '书籍',
    kindReport: '研究报告',
    perspectiveDeepen: '顺着目标深入',
    perspectiveAdjacent: '相邻视角',
    perspectiveCounterpoint: '不同视角',
    unknownAuthor: '作者未标注',
  },

  /**
   * 「聊聊你想要的」—— 用户和 AI 教练对话梳理目标的入口。
   * 是 v3.0 信息流哲学落地的第一个产品入口（替代旧硬编码 LearnerOnboarding 表单）。
   * 设置页常驻 + 首次进入 app 自动弹出。
   */
  intent: {
    /** 主标题（设置页 caption / 首次进入 header） */
    title: '聊聊你想要的',
    /** 副标 */
    subtitle: '不用写好——说就行',
    /** 设置页 description */
    description: '和教练聊一聊，把脑子里的事一起捋清楚——也可以打电话语音聊',
    /** 设置页：还没聊过的提示 */
    emptyHint: '还没聊过。你最近想做的事 / 想去的方向 / 还在纠结的选择，都可以慢慢说。',
    /** 设置页：开始按钮 */
    actionStart: '和教练聊一聊',
    /** 设置页：再聊一次按钮 */
    actionResume: '和教练再聊一会',
    /** IntentDialog header：右上角切换通话 */
    switchToCall: '打电话聊',
    /** 通话视图：切回文字 */
    switchToText: '文字',
    /** 通话视图：标题 */
    callTitle: '在听你说',
    /** 通话视图：底部状态行（基于 useOmniRealtimeCall.status） */
    callStatusListening: '我在听你说…',
    callStatusThinking: '我想一下…',
    callStatusResponding: '我在说…',
    callStatusMuted: '已静音 · 我还在',
    callStatusConnected: '直接说就好',
    callStatusConnecting: '正在接通…',
    callStatusAuthorizing: '点下面按钮开始',
    callStatusError: '没接通，点重连',
    callStatusPreparing: '准备中…',
    /** 输入条：占位符 */
    inputPlaceholder: '说说你最近想做的事',
    inputPlaceholderBusy: '同学正在听…',
    /** 首次进入：跳过文案 */
    firstTimeSkip: '先不聊，下次再说',
    /** 开场提示——已有 N 个目标时 */
    greetingWithGoals: (count: number): string =>
      `欢迎回来。你之前留下了 ${count} 件想做的事——是想聊聊新的，还是更新一下旧的？`,
    /** 开场提示——首次 */
    greetingFirstTime:
      '不急。你现在脑子里有什么想做、想去、想搞清楚的事？哪怕还没完全想明白，也可以慢慢说。',
    /** 卡片：标题（"我听到的是"） */
    summaryEyebrow: '我听到的是',
    /** 卡片：先放放 */
    summaryDismiss: '先放放',
    /** 卡片：就是这样（保存） */
    summaryAccept: '就是这样',
    /** 卡片：保存中 */
    summarySaving: '记着…',
    /** 卡片：已保存 */
    summarySaved: '已记下了',
  },

  realtime: {
    defaultTitle: '语音同桌',
    defaultContext: '整节课',
    disabled: '先收一条课堂内容',
    reconnect: '没接通，点重连',
    connecting: '正在接通…',
    authorizing: '点下面按钮开始',
    muted: '已静音 · 我还在',
    listening: '我在听你说…',
    thinking: '我想一下…',
    responding: '我在说…',
    connected: '已接通 · 直接说',
    preparing: '准备中…',
    transcriptTitle: '本轮对话文字',
    assistantLabel: '同学',
    userLabel: '你',
    emptyTranscript: '还没有对话内容',
    showText: '查看文字',
    reconnectAction: '重连',
    collapse: '收起',
    dialing: '接通中',
    start: '开始',
    unmute: '开麦',
    mute: '静音',
    endCall: '结束通话',
  },

  mobileJourney: {
    playAudio: '播放原声',
    pauseAudio: '暂停原声',
    finishLesson: '结束这节课',
    photoCapturedAt: (timestamp: string): string => `已拍下板书 · ${timestamp}`,
    collapseClassmate: '收起课堂同桌',
    processingEyebrow: '正在整理',
    processingTitleLead: '把这节课',
    processingTitleAccent: '听懂',
    waitingTranscript: '等待转录完成…',
    readingTranscript: '正在读转录原文…',
    buildingNotes: '正在生成分段笔记…',
    processingDone: '整理完成',
    noSpeechStatus: '没有听到可整理的内容',
    processingEstimate: '约 1 分钟',
    waiting: '等待中…',
    done: '完成',
    leaveWhileProcessing: '先回首页',
    openNotes: '笔记整理好了，去看看 →',
    understood: '已理解',
    originalPreserved: '原声已保留',
    restoringTranscript: '正在恢复这节课的转录内容…',
    noSpeechTitle: '这段录音里没有识别到语音',
    noSpeechBody: '可能是录音太短或声音太小。原声已保留，可以返回首页稍后再看。',
    backHome: '返回首页',
  },

  help: {
    classroomRecordingAnswer: '录课中 MeetMind 会实时展示：\n\n- 实时原话：老师说的内容会跟着出现\n- 课堂脉络：告诉你现在讲到哪里、刚才如何推进、什么值得课后回来\n- 同学：有问题随时可以问，它会带着刚才的课堂上下文回答\n\n这些都会自动完成。思维导图、闪卡和测验会在课后应用中生成，不会在上课时抢走注意力。',
  },

  /**
   * v3.0 SharedAgent —— 分享 Agent 的落地页 / 分享卡 / 创建对话框文案
   * 见 roadmap/v3.0-virality-agent.md。
   */
  share: {
    landing: {
      /** 落地页右下角极淡的访问计数 */
      viewCount: (count: number): string => `已被打开 ${count} 次`,
      /** 没登录访问者点"领取到我的工作台"时的引导 */
      claimNeedsLogin: '领取需要先登录，登录后这份内容就在你的工作台里了',
      claimGo: '去登录',
      /** 已登录领取按钮 */
      claimAction: '领取到我的工作台',
      claiming: '正在领取…',
      claimDone: '已领取，去工作台看看',
      claimRedirecting: '正在打开你的工作台…',
      claimAlready: '你之前已经领过这一份',
      /** 也分享给别人 */
      reshareAction: '复制链接',
      reshareFailed: '复制失败，请手动复制地址栏',
      /** 分享态对话输入占位符 */
      chatPlaceholder: '问问这节课…',
      /** 已撤销 / 已过期 */
      notFoundTitle: '这条分享暂时不可用',
      notFoundBody: '可能已被原作者撤回，或者链接打错了。',
      /** 头部副标题：基于分享者昵称 */
      sharedBy: (nickname: string): string => `${nickname} 听完了这节课，留了一份给你`,
      /** 没有昵称兜底 */
      sharedByAnon: '一个同学听完了这节课，留了一份给你',
      /** 转录摘要标题 */
      digestTitle: '这节课讲了什么',
      digestEmpty: '没附转录摘要，可以直接问同学这节课的事。',
      /** 产物预览块标题（按 artifactKind 切换） */
      artifactTitle: (kind: string): string => {
        const map: Record<string, string> = {
          cheatsheet: '考前速查表',
          mindmap: '思维导图',
          quiz: '课堂测验',
          flashcards: '课堂闪卡',
          infographic: '课堂信息图',
          'audio-overview': '课堂播客',
          notes: '同学版笔记',
          'chat-only': '可以直接聊',
        };
        return map[kind] ?? '一份分享';
      },
    },
    creator: {
      /** 录音结束后 Octo Buddy 弹出的标题 */
      title: '今天这节课的结晶',
      subtitle: '挑一个递给同学，也可以丢进班级群',
      /** 选哪种产物（场景层只显示这一组） */
      pickKind: '想送什么过去？',
      pickHint: '挑一个就好。同学会基于这节课在背后陪你回答',
      /** 创建按钮 */
      submit: '生成分享',
      submitting: '正在生成…',
      doneCopy: '复制链接',
      doneCopied: '链接已复制',
      doneLinkCreated: '分享链接已生成',
      doneCopyFailed: '复制失败，请手动复制链接',
      doneCopying: '复制中...',
      fallbackTitle: '分享链接已生成',
      fallbackBody: '浏览器没有允许自动复制，可以直接复制下面的链接。',
      loginRequired: '先登录再分享',
      createFailed: '创建分享失败',
      /** 仪式入口（应用矩阵 / 录课结束页都会用到的「递结晶」模块） */
      crystal: {
        eyebrow: '今天这节课',
        title: '把这节课递给同学',
        subtitle: '挑一个产物，做成一份能对话的分享',
        cta: '递给同学',
        ctaPreparing: '正在准备…',
        cardReady: '已整好，递给同学',
        cardEmpty: '还没整 · 先做一版',
        cardGenerating: '生成中…',
        emptyHint: '做完一个应用，这里就会出现',
        privacyNote: '只带这节课的内容和你挑的这一份，不会带你的私人对话或答题数据',
      },
    },
  },

  /**
   * "被禁用"的词表——供测试脚本 grep 校验，确保面向用户的字符串不退化。
   */
  bannedWords: ['回声卡', '酿', '预知气泡', '工坊', '研判', '引擎'] as const,
};

export type Copy = typeof COPY;
