/**
 * copy-apps — 应用矩阵各产物窗口（测验 / 闪卡 / 讲给同桌听 / 导图 / 信息图 / 播客 / 板书 / 路径 …）的用户面文案
 *
 * 从 copy.ts 拆出来的唯一理由是体积：这一块只有 应用窗口与课后学习路径 用到，却随 COPY 单体进 /app 首屏 JS（≈5.5 KB gzip）。
 * 口吻审查仍是同一个入口：改文案先看 copy.ts，应用窗口与课后学习路径看这里。用法：`import { APPS_COPY } from "@/lib/ui/copy-apps"`。
 */

export const APPS_COPY = {
    inlineSource: '已放进对话',
    /**
     * 应用窗口公共壳（复习页中栏宿主 / 浮窗 / 独立页）。
     * 口吻：动作全是两个字的动词，退成文字，不做 pill；状态只在"正在做 / 没做好"时说话，做好了就不说。
     */
    shell: {
      fullscreen: '全屏',
      exitFullscreen: '退出全屏',
      close: '关闭',
      minimize: '收起',
      back: '返回',
      generating: '正在做…',
      crashed: (appName: string): string => `${appName}这次没显示出来`,
      crashedRetry: '再试一次',
    },
    /**
     * 课后学习页 v2（2026-09-08）：一件事优先 + 学习路径 + 结果跟着人走。
     * 口吻：同桌陈述事实，不下命令；理由必须是学生能核对的（时刻、难点、上一步的结果）。
     */
    path: {
      lessonEyebrow: '这节课',
      lessonMeta: (minutes: number, anchors: number, difficulties: number): string => {
        const parts = [`${minutes} 分钟`];
        if (anchors > 0) parts.push(`你标记了 ${anchors} 处`);
        if (difficulties > 0) parts.push(`${difficulties} 个难点`);
        return parts.join(' · ');
      },
      summaryFallback: '同桌听完了这节课。下面是接着学的几种方式，先从一件开始。',
      nextTitle: '先做这一件',
      nextSwitch: '换一个',
      pathTitle: '这节课的学习路径',
      pathHint: '先暴露问题，再记牢，再讲出来，最后带走。顺序只是建议。',
      stepLabels: {
        quiz: '检验',
        flashcards: '记住',
        'teach-back': '讲出来',
        infographic: '带走',
      } as Record<string, string>,
      quietTitle: '还可以这样学',
      /** 应用完成态里的下一步卡（2026-09-08）：一步做完，同桌接着说 */
      nextInWindowTitle: '接下来',
      nextInWindowAction: (action: string): string => `去${action}`,
      notStarted: '还没开始',
      running: '正在做',
      ready: '做好了',
      failed: '没做好',
      redoWithOutcomes: (count: number): string => `再做一版，带上刚错的 ${count} 处`,
      outcome: {
        quiz: (total: number, correct: number): string => `${total} 题对 ${correct}`,
        flashcards: (total: number, got: number): string => `${total} 张记住 ${got}`,
        teachBack: (mastery: number, weak: number): string => (
          weak > 0 ? `讲透 ${mastery} 个 · ${weak} 个还没讲清` : `${mastery} 个都讲透了`
        ),
      },
      reason: {
        fromAnchors: (count: number, times: string[]): string => (
          `你在 ${times.join('、')} 留了标记${count > times.length ? `（共 ${count} 处）` : ''}。先做几道题，看看那几处跟上了没有。`
        ),
        fromDifficulties: (count: number, names: string[]): string => (
          `这节课有 ${count} 个难点${names.length ? `（${names.join('、')}）` : ''}。先把它们练到看到题就能想起来。`
        ),
        fromLength: (minutes: number): string => `这节课有 ${minutes} 分钟，内容不少。先看清主干和分支，再决定往哪里深挖。`,
        afterQuizWrong: (count: number, names: string[]): string => (
          `测验里错了 ${count} 处${names.length ? `（${names.join('、')}）` : ''}。先把这几处记牢，再往下走。`
        ),
        afterQuizPerfect: (total: number): string => `${total} 题全对。真懂还是看懂，讲一遍给同桌听就知道了。`,
        afterFlashcardsMissed: (count: number): string => `还有 ${count} 张没记住。讲给同桌听最能暴露卡在哪里。`,
        afterTeachBackGaps: (count: number): string => `有 ${count} 个点还没讲清。做成一张图带走，下次回来先看它。`,
        afterTeachBackClear: '都讲透了。做成一张图，这节课就可以带走了。',
        completed: '这节课的四步都走完了。',
        defaultStart: '先从这里开始，几分钟就有结果。',
      },
      wrap: {
        title: '这节课，你走完了',
        body: '检验过、记牢了、讲出来了。结果都在这里，同桌下次会记得。',
      },
      anchorPrefix: {
        quizWrong: '测验答错：',
        flashcardsMissed: '闪卡没记住：',
        teachBackWeak: '讲给同桌听时没讲清：',
      },
    },
    classroomFlowArtifact: {
      sectionTitle: '录课时已经整理好',
      name: '课堂脉络',
      ready: '随录课生成',
      open: '打开复习',
      back: '返回应用矩阵',
      timelineTitle: '这节课怎么走过来',
      keepTitle: '留到课后再看的内容',
      cardSummary: (moments: number, keeps: number): string => `${moments} 个课堂节点 · ${keeps} 个课后保留点`,
      reviewSummary: (moments: number, keeps: number): string => `上课时形成的 ${moments} 个推进节点和 ${keeps} 个保留点都在这里。`,
    },
    placeholder: {
      defaultAppName: '应用内容',
      workingElapsed: (seconds: number): string => `同学正在整理 · ${seconds.toString().padStart(2, '0')}s`,
      emptyTitle: (appName: string): string => `还没有${appName}`,
      emptyBody: (appName: string): string => `回到应用目录开始整理${appName}，完成后会直接出现在这里。`,
      remake: '再做一版',
      back: '返回应用',
      failedTitle: (appName: string): string => `${appName}刚才没做好`,
      failedBody: '网络可能有点慢，原课堂内容没有受到影响。',
      retry: '再试一次',
      tryAnother: '看看其他方式',
    },
    infographic: {
      appName: '课堂信息图',
      preparing: '正在把这节课变成一张图',
      preparingHint: '完成后会直接显示成品。',
      finished: '做好了',
      fit: '看全图',
      full: '看细节',
      save: '保存图片',
      adjust: '调整',
      createTitle: '把这节课变成一张图',
      createHint: '选尺寸和感觉，其他交给同学。',
      adjustTitle: '想换一种呈现？',
      adjustHint: '只改你在意的部分，其余交给同学。',
      orientation: '尺寸',
      style: '视觉感觉',
      custom: '还想强调什么',
      customPlaceholder: '例如：突出 3 个结论，适合手机查看',
      generate: '生成信息图',
      regenerate: '按这个方向重做',
      serviceUnavailable: '图片服务暂时不可用',
      serviceUnavailableBody: '课堂内容和草案已经保留，稍后再试即可。',
      downloaded: '图片已保存',
      downloadFailed: '没保存上，请长按图片保存',
      missingContext: '当前内容还不足以生成可靠的信息图。',
      generateFailed: '这次没有生成成功，课堂内容仍然保留着。',
      readableReady: '先给你一张可读版',
      readableHint: '图片还没做好，课堂重点不用跟着等。',
      copyReadable: '复制要点',
      readableCopied: '要点已复制',
      readableCopyFailed: '没复制上，可以长按选择文字。',
      retryImage: '再试一次图片',
    },
    teachBack: {
      appName: '讲给同桌听',
      targetsTitle: '这节课，挑几点讲出来',
      targetsSubtitle: '能讲出来的，才是真的懂。',
      evidenceLabel: '课堂依据',
      startVoice: '走上讲台',
      voiceHint: '同桌安静听你讲，只在跟不上或你有没讲到的点时开口。',
      textTitle: '把这节课讲给同桌',
      speakPlaceholder: '讲一段，或打字补充……',
      submitSegment: '讲给同桌',
      deskmateListening: '同桌在听',
      finishText: '讲完了',
      evaluating: '同桌正在对照课堂原声核对你讲的……',
      evaluatingStage2: '正在逐条核对你讲的和课堂原声……',
      evaluatingStage3: '就快好了，同桌在写核对结论……',
      evalRateLimited: '刚才操作太频繁了，喝口水，等一小会儿再试。',
      reteachPoint: '就这点再讲一次',
      yourTeachingStats: (chars: number): string => `你讲的约 ${chars} 字都还在，不用重讲。`,
      resultTitle: '讲得怎么样',
      quadrantMastery: '讲透了',
      quadrantStruggle: '挣扎着讲通了',
      quadrantGap: '自己知道卡住了',
      quadrantBlindSpot: '盲区',
      quadrantUncovered: '还没讲到',
      blindSpotHint: '讲的时候很顺，但和课堂内容对不上。',
      backToEvidence: '回到课堂原声',
      retry: '再讲一次',
      backToTargets: '回到目标',
      emptyBody: '这节课的内容还太少，等录得更久一点再来讲。',
      callContextLabel: '讲课中',
      endCall: '讲完了',
      switchToText: '改为打字',
      classroomWaiting: '开始讲吧，我们在听。',
      classroomReconnect: '连接断了，点这里重新进教室',
      evalFailed: '这次没能完成核对，你讲的内容还在，可以再试一次。',
      retryEval: '重新核对',
      textHint: '用嘴讲，同桌听得见；他跟不上时会开口问。',
    },
    mindmap: {
      appName: '思维导图',
      loadingTitle: '正在把这节课理成一张图',
      loadingBody: '同学在读整节课，找主线和分支…',
      mobileGestureHint: '拖动查看 · 点主干只看一支',
      desktopGestureHint: '滚轮缩放 · 拖拽平移 · 点主干只看一支',
      /** 顶栏两个视图词（两个词 + 下划线，不是 pill） */
      viewMap: '导图',
      viewOutline: '大纲',
      stats: (branches: number, nodes: number, depth: number): string => `${branches} 支 · ${nodes} 个节点 · ${depth} 层`,
      fullscreen: '全屏',
      exitFullscreen: '退出全屏',
      copyOutline: '复制大纲',
      copied: '已复制',
      zoomIn: '放大',
      zoomOut: '缩小',
      fit: '适应',
      expandAll: '展开',
      trunkOnly: '主干',
      /** 聚焦一支后，右下角出现的回退 */
      showAll: '看全图',
    },
    flashcards: {
      appName: '闪卡训练',
      completeTitle: '这一轮完成了',
      roundSummary: (count: number): string => `共回忆 ${count} 张`,
      recallRate: '本轮记住',
      got: '记住了',
      missed: '再来一次',
      gotCount: '记住了',
      missedCount: '还要练',
      reviewMissed: (count: number): string => `只练没记住的 ${count} 张`,
      restart: '重练全部',
      reveal: '想好后翻面',
      answer: '参考答案',
      showHint: '看一点提示',
      recallFirst: '先在心里回答，再翻面看答案',
      /** 桌面端一行键盘提示：翻面前 / 翻面后各一句，只在第一张出现 */
      keyboardHint: '空格翻面 · ←→ 换牌',
      keyboardHintFlipped: '1 再来一次 · 2 记住了',
      /** 牌面左上角的小字：正面 / 背面 */
      frontLabel: '问',
      backLabel: '答',
      /** 牌堆下方还剩几张（不含当前） */
      remaining: (count: number): string => `还剩 ${count} 张`,
      missedList: '没记住的',
      previous: '上一张',
      next: '下一张',
      evidenceAt: (time: string): string => `来自课堂 ${time}`,
      returnToEvidenceAt: (time: string): string => `回到课堂 ${time}`,
    },
    quiz: {
      appName: '课堂测验',
      /** 桌面端一行键盘提示，只在第一次进入时出现一次（keyboard-hints 记住） */
      keyboardHint: '1–4 选 · 回车 / 空格确认 · ←→ 翻题',
      /** 「确认答案」还按不了时的原因（title） */
      pickFirst: '先选一个答案',
      /** 从结束页点题号回看后，回到结果 */
      backToReport: '回到结果',
      reviewQuestion: (index: number): string => `回看第 ${index} 题`,
      questionNo: (index: number): string => `第 ${index} 题`,
      explanationLabel: '解析',
      previous: '上一题',
      next: '下一题',
      jumpTo: (index: number): string => `跳到第 ${index} 题`,
      answered: (done: number, total: number): string => `${done} / ${total} 已完成`,
      understood: '答稳了',
      revisit: '再看看',
      subjectivePrompt: '先在心里说出答案，再对照参考。',
      referenceAnswer: '参考答案',
      referenceFallback: '回到原片段核对关键内容。',
      selfRate: '对照后，我：',
      selfCorrect: '答到要点',
      selfWrong: '还没答上',
      correct: '答对了',
      wrong: '再看看',
      correctAnswer: (answer: string): string => `答案：${answer}`,
      revealReference: '对照答案',
      confirmAnswer: '确认答案',
      nextQuestion: '下一题',
      viewResult: '看这一轮',
      /** 最后一题做完但还有跳过的：告诉学生差几题、回到哪一题 */
      backToUnfinished: (remaining: number, questionNo: number): string => `还有 ${remaining} 题没做 · 回到第 ${questionNo} 题`,
      completeTitle: '这一轮检验完成',
      completeMeta: (count: number, minutes: string): string => `共 ${count} 题 · 用时 ${minutes} 分钟`,
      recallRate: '本轮答稳',
      solidCount: '答稳了',
      revisitCount: '还要回看',
      missedReview: '需要回看的题',
      reviewMissed: (count: number): string => `只练需要回看的 ${count} 题`,
      restart: '重做全部',
      evidenceAt: (time: string): string => `来自课堂 ${time}`,
      returnToEvidenceAt: (time: string): string => `回到课堂 ${time}`,
    },
    explainer: {
      appName: '板书精讲',
      quotesVerified: (count: number): string => `${count} 处老师原话已核对`,
      quotesDowngraded: (count: number): string => `${count} 处引用未对上原话，已改为转述`,
      play: '播放',
      pause: '暂停',
      replay: '重新播放',
      pageLabel: (current: number, total: number): string => `第 ${current} / ${total} 页`,
      checkpointKnow: '我会了',
      checkpointHint: '给我提示',
      checkpointAnswer: '看解析',
      inkStart: '板演',
      inkClear: '擦掉重写',
      inkDone: '写完了',
      inkGrading: '老师正在批改你的板演…',
      inkDemoTitle: '老师示范：',
      preparing: '老师正在备课…',
      awaitingGesture: '点一下黑板，听老师开讲',
      finishedCaption: '这节课讲完了。可以重新播放，或者点「板演」自己试试。',
      photoEntry: '拍题开讲',
      photoPick: '选一张题目照片',
      photoStageReading: '老师正在看题…',
      photoStageSolving: '老师正在解题…',
      photoStagePreparing: '老师正在备课…',
      photoErrorNotProblem: '这张照片里好像没有题目，换一张试试',
      photoErrorGeneric: '这次没讲成，再试一次',
      photoChange: '换一道题',
    },
    teach: {
      appName: 'AI 家教',
      emptyBody: '还没有上过课。开一节，老师会从你这节课的内容讲起。',
      lessonStart: '老师，开始上课吧',
      askPlaceholder: '随时提问，当前句讲完就答你…',
      thinking: '老师在想…',
      quoteAsk: '引用提问',
      removeQuote: '移除引用',
      voiceSoon: '语音提问即将上线',
      soundOn: '讲课声音：开',
      soundOff: '讲课声音：关',
      history: '课程',
      newLesson: '新开一课',
      topicPromptTitle: '今天想学什么？',
      topicPromptPlaceholder: '比如：黎曼猜想、勾股定理、英语过去完成时…',
      topicPromptStart: '开课',
      emptyChat: '课马上开始。听懂听不懂，都可以随时在下方问。',
      restored: '已恢复到上次讲到的地方，可以继续提问。',
      toolChip: {
        write: '板书',
        circle: '圈注',
        underline: '下划线',
        arrow: '连线',
        mark: '批改',
        image: '插图',
        flip_page: '新一页',
        ask: '提问',
      } as Record<string, string>,
    },
    podcast: {
      appName: '课堂播客',
      /** 播放条（PodcastPlayerBar）：取代浏览器原生控件 */
      play: '播放',
      pause: '暂停',
      seek: '进度',
      rate: (rate: number): string => `播放速度 ${rate}x`,
      emptyBody: '开始整理后，会直接得到一版可以播放的课堂播客。',
      scriptCopied: '脚本已复制',
      copyFailed: '复制失败，请手动选择脚本内容',
      /** 逐字稿说话人兜底名（模型给的是音色 id 时） */
      hostA: '主持人 A',
      hostB: '主持人 B',
      chapters: '章节',
      script: '逐字稿',
      /** 试听卡上的入口：进完整播客窗口看逐字稿与章节 */
      openScript: '看逐字稿',
      copyScript: '复制',
      chapter: (index: number): string => `章节 ${index}`,
      audioGenerating: '正在准备音频',
      audioRetry: '音频没做好，点这里再试一次',
      audioGeneratingHint: '完成后这里会直接变成播放条。',
      audioRetryHint: '脚本已经保留，不需要重新来过。',
      audioRetryNoScriptHint: '课堂内容仍然保留，稍后可以直接再试。',
      activityAudioReady: '课堂播客已经可以播放，并保留了脚本与章节。',
      activityScriptReady: '音频还没做好，播客脚本与章节已经保留。',
      generating: '正在准备',
      retry: '再试一次',
    },
    /**
     * 考试速查表（2026-09-09 重做：一张真正的纸）。
     * 口吻：工具条上全是动词短语，纸面上只有内容；三色荧光笔用图例自解释，不写"系统"。
     */
    cheatsheet: {
      appName: '考试速查表',
      /** 工具条标题后缀：《课名》· 速查表 */
      paperLabel: '速查表',
      emptyBody: '当前内容还不足以整理成可靠的速查表。继续记录后再回来看看。',
      focus: '重点',
      /** 工具条 */
      generatedAt: (when: string): string => `${when} 生成`,
      pageTotal: (count: number): string => `${count} 页`,
      itemCount: (count: number): string => `${count} 条`,
      restoreHidden: (count: number): string => `已去掉 ${count} 条，全部恢复`,
      layout: '版式',
      columns: '栏数',
      columnsOf: (count: number): string => `${count} 栏`,
      fontSize: '字号',
      fontSmaller: '字号变小',
      fontLarger: '字号变大',
      fontCompressedHint: '为了装进一页，字号已自动压小；关掉「装进一页」恢复。',
      density: '密度',
      densityLabel: { tight: '紧', normal: '标准', loose: '松' } as Record<'tight' | 'normal' | 'loose', string>,
      highlight: '高亮',
      fitOnePage: '装进一页',
      zoomIn: '放大',
      zoomOut: '缩小',
      zoomFit: '适合宽度',
      copyMarkdown: '复制文字',
      copied: '已复制',
      print: '打印 / PDF',
      /** 纸面 */
      legend: { definition: '定义', formula: '公式', pitfall: '易错' },
      footerFrom: (courses: string, lessonCount: number): string => (lessonCount > 1 ? `来自《${courses}》· ${lessonCount} 节课` : `来自《${courses}》`),
      pageNumber: (current: number, total: number): string => `${current} / ${total}`,
      allRemoved: '内容都去掉了，可以在上面恢复。',
      /** 条目 hover 动作 */
      sourceTitle: (source: string): string => `老师原话 · ${source}`,
      editShort: '编辑',
      hideShort: '不打印',
      hideTopic: (title: string): string => `整个「${title}」不打印`,
      editTerm: '术语',
      editBody: '解释',
      editFormula: '公式（LaTeX，可留空）',
      cancelEdit: '取消',
      saveEdit: '保存',
      syllabusSource: '考试大纲',
      pastPaperSource: (index: number): string => `真题 ${index}`,
    },
  } as const;

export type AppsCopy = typeof APPS_COPY;
