/**
 * copy.ts — 用户面可见文案的单一真相源。
 *
 * 为什么要有这个文件：
 *   过去散在 10+ 个组件里的字符串里夹带了"回声卡 / 酿 / 预知气泡 / 工坊"
 *   这类内部术语，被用户看到时跳戏。把所有用户可见的文案汇总在这里，
 *   才能以"顶级 UI/UX 设计师"的视角一次性审过口吻、去掉行业黑话。
 *
 * 口吻原则（M8-agent-native）：
 *   - 角色：一个叫"同学"的 AI 同桌。像朋友，不像老师，不像客服
 *   - 说话方式：安静、直接、克制
 *   - 禁用词：回声卡 / 酿 / 预知气泡 / 工坊 / 研判 / 引擎 / 引导
 *   - 首选词：收藏 / 整理 / 情报 / 应用 / 同学
 *
 * 使用约定：
 *   - 所有出现在用户界面（非日志/埋点）的字符串必须 import { COPY }
 *   - 新增字符串时先找有没有相近语义的键可以复用，避免二次碎片化
 *   - 复杂占位符用函数而非模板字符串，便于测试
 */

export const COPY = {
  identity: {
    productName: 'MeetMind',
    name: '同学',
    tagline: '真正懂你在学什么的 AI 同学',
    subtagline: '理解你的课堂、资料和目标，陪你学懂当下，也发现下一步值得看的内容。',
  },

  landing: {
    media: {
      realProduct: '真实产品画面',
      videoFallback: '你的浏览器暂时无法播放这段产品录屏。',
    },
    navigation: {
      product: '产品',
      philosophy: '为什么是 MeetMind',
      technology: '技术',
      signIn: '登录',
      openProduct: '进入 MeetMind',
    },
    hero: {
      eyebrow: '真正听过这节课的 AI 同学',
      title: '真正听过这节课，\n才知道你哪里没懂。',
      body: '录下课堂，发来资料。MeetMind 记得老师怎么讲，也知道你在哪里卡住，把每一次学习接成一条不会断的线。',
      primaryAction: '先试听一节课',
      secondaryAction: '看看它怎么工作',
      imageAlt: '大学生在真实课堂中听课并记录笔记',
      videoAlt: 'MeetMind 真实试听课正在展示实时转录、课堂脉络和同学',
      demoLabel: '正在听 · 英语听力',
      demoTime: '18:42',
      demoTranscript: '条件概率不是换一个公式，而是缩小我们正在观察的世界。',
      demoContext: '已接上：上节课的贝叶斯公式',
      demoBoard: '板书已收下',
      demoLive: '课堂脉络正在生长',
      filmLabel: 'MeetMind 产品短片',
      filmDuration: '45 秒 · 真实操作短片',
      filmChapters: ['正在听懂这节课', '把问题练到会', '把每次学习接起来', '从一节课，走向一门课'] as const,
      filmClosingTitle: '从听懂这一节课，\n到学会这一门课。',
      filmClosingBody: '真正懂你在学什么的 AI 同学',
      playFilm: '播放产品短片',
      pauseFilm: '暂停产品短片',
      unmuteFilm: '开启产品短片声音',
      muteFilm: '关闭产品短片声音',
      listenFilm: '听产品介绍',
    },
    belief: {
      eyebrow: '学习不该在下课铃响时断掉',
      title: '模型懂世界，还不够。\n它还得懂正在学习的你。',
      body: '一次回答可以很聪明，真正的学习却发生在一节又一节课之间。MeetMind 保留老师的原话、你的困惑和正在靠近的目标，让下一次帮助从你真正停下的地方继续。',
    },
    manifesto: {
      lineA: '不是笔记工具，也不只是课堂转录。',
      lineB: '它真的听过课，也知道你正在学什么。',
    },
    classroomLine: {
      eyebrow: '课堂线',
      title: '从一节真实的课，\n一直陪到考试。',
      body: '录、问、练、证、考——五个动作发生在同一个现场里，不需要在四个工具之间搬运。',
      previous: '查看上一个阶段',
      next: '查看下一个阶段',
      ariaLabel: '一节课从上课到考试的时间线',
      stages: [
        {
          step: '01', verb: '录', time: '09:02 · 上课中',
          title: '先录下这节课',
          body: '麦克风、电脑声音，或两路都录。原声一直在，转录只是开始。',
          mock: {
            kind: 'live',
            lines: ['条件概率不是换一个公式，', '而是缩小我们正在观察的世界。', '所以先看清楚：我们在哪些人里谈概率。'] as const,
            chips: ['条件概率', '样本空间'] as const,
          },
        },
        {
          step: '02', verb: '问', time: '09:47 · 课中',
          title: '同桌跟上课堂',
          body: 'AI 同学听着同一段话。卡住时直接问，不用举手，也不用等下课。',
          mock: {
            kind: 'ask',
            question: '这里为什么能直接用贝叶斯？',
            answer: '老师先把观察范围缩小到了「检测为阳性」的人。',
            cite: '18:42',
          },
        },
        {
          step: '03', verb: '练', time: '16:20 · 下课',
          title: '从原话出发复习',
          body: '闪卡、测验、思维导图，都从老师真正讲过的内容里长出来。',
          mock: {
            kind: 'card',
            front: '什么是条件概率？',
            back: '已知 B 发生时，A 发生的概率。',
            progress: '3 / 12',
          },
        },
        {
          step: '04', verb: '证', time: '周三 · 复习',
          title: '每个结论都有根',
          body: '回答可以跳回 [MM:SS] 的那一刻。不是听起来对，是真的对。',
          mock: {
            kind: 'evidence',
            answer: '后验，就是把证据算进去之后的判断。',
            evidence: '18:42',
            quote: '缩小我们正在观察的世界',
          },
        },
        {
          step: '05', verb: '考', time: '考前 · 一周',
          title: '多节课连成考试范围',
          body: '几节课成单元，一学期压成一张能带进考场的速查表。',
          mock: {
            kind: 'sheet',
            sheetTitle: '概率论 · 期末一页纸',
            lines: ['P(A|B) = P(AB) / P(B)', '后验 ∝ 似然 × 先验', '易错：混淆 P(A|B) 与 P(B|A)'] as const,
          },
        },
      ] as const,
    },
    appsLine: {
      eyebrow: '应用矩阵',
      title: '一节课，\n长出七种学法。',
      body: '不是模板生成。每个应用都从老师真正讲过的内容里长出来，练完还能跳回原话对答案。',
      ariaLabel: '七种学习应用，可直接上手试',
      apps: [
        {
          key: 'flashcards',
          name: '闪卡训练',
          tag: '主动回忆',
          flipHint: '点卡片翻面',
          nextLabel: '下一张',
          cards: [
            { front: '什么是条件概率？', back: '已知 B 发生时，A 发生的概率：P(A|B) = P(AB) / P(B)。' },
            { front: '先验和后验的区别？', back: '看到证据之前是先验，把证据算进去之后是后验。' },
            { front: '什么是样本空间？', back: '所有可能结果的集合。条件概率就是把它缩小。' },
          ] as const,
        },
        {
          key: 'quiz',
          name: '课堂测验',
          tag: '理解检验',
          question: '老师说的「缩小观察的世界」是指什么？',
          options: ['换用另一个公式', '只在检测阳性的人里重新看概率', '忽略先验概率'] as const,
          answer: 1,
          correctNote: '答对了。这句话出自 18:42。',
          wrongNote: '再想想——老师在 18:42 讲过。',
          evidence: '跳回原话 18:42',
        },
        {
          key: 'mindmap',
          name: '思维导图',
          tag: '结构学习',
          root: '贝叶斯定理',
          expandHint: '点分支展开',
          branches: [
            { name: '条件概率', children: ['样本空间', 'P(A|B) 定义'] as const },
            { name: '先验与后验', children: ['似然', '归一化'] as const },
            { name: '检测悖论', children: ['假阳性', '基数忽略'] as const },
          ] as const,
        },
        {
          key: 'cheatsheet',
          name: '考试速查表',
          tag: '可打印',
          sheetTitle: '概率论 · 期末一页纸',
          lines: ['P(A|B) = P(AB) / P(B)', '后验 ∝ 似然 × 先验', '易错：混淆 P(A|B) 与 P(B|A)'] as const,
        },
        {
          key: 'audio-overview',
          name: '课堂播客',
          tag: '通勤可听',
          episode: '第 3 讲 · 贝叶斯定理',
          duration: '90 秒试听',
          chapters: ['开场 · 缩小观察的世界', '中段 · 检测悖论', '结尾 · 考前一句话'] as const,
        },
        {
          key: 'infographic',
          name: '课堂信息图',
          tag: '一张图带走',
          course: '概率论与数理统计',
          quote: '条件概率不是换公式，是缩小我们正在观察的世界。',
          summary: '先定样本空间，再谈概率。',
        },
        {
          key: 'teach-back',
          name: '讲给同桌听',
          tag: '费曼检验',
          topic: '讲一遍：贝叶斯公式怎么来的',
          passed: ['条件概率', '先验与后验'] as const,
          blind: '归一化常数',
          blindNote: '「似然 × 先验」之后还要除以证据总和，这一步跳过去了。',
        },
      ] as const,
    },
    collectionLine: {
      eyebrow: '收集线',
      title: '像发消息一样，\n先把它收下。',
      body: '在微信公众号里，像发给朋友一样发给它——好文章、板书照片、一闪而过的想法。不用分类，不用打标签，收藏就这么自然地发生了。',
      silentNote: '模型在后台判断它属于哪门课、哪个目标、哪个问题，再悄悄回流到课堂和你的长期上下文。',
      sinkLabel: '先收下',
      statusLabel: '都已收下 · 后台正在判断归属',
      wechatHeader: 'MeetMind',
      wechatThread: [
        { kind: 'link', inbound: '贝叶斯定理的直觉解释', reply: '已收下这篇网页，归到「概率论 · 第 3 讲」' },
        { kind: 'image', inbound: '黑板照片', reply: '板书已收下，认出 4 个公式，接回今天的课堂' },
        { kind: 'text', inbound: '贝叶斯那里我还是没懂', reply: '你上节课卡在条件空间的变化——先沿板书把样本空间重新圈一遍' },
      ] as const,
      sideChannels: [
        { channel: '桌面端', kind: 'image', text: '热键截下这一页', reply: '截图已收下，接回当前课堂' },
        { channel: '随手记', kind: 'voice', text: '0:18', reply: '语音已转成文字，标记为一个疑问' },
      ] as const,
      channelNote: '桌面端和网页也能收——但大多数时候，顺手一发就够了。',
    },
    bridge: {
      eyebrow: '两条线，不会成为数据孤岛',
      lead: '好的回答，来自三样东西',
      parts: ['个人上下文', '场景上下文', '模型智能'] as const,
      partNotes: ['目标 · 阶段 · 长期困惑', '这节课 · 这份材料 · 此刻意图', '解释 · 定位 · 验证 · 克制'] as const,
    },
    journey: {
      eyebrow: '从现场开始，一直陪到学会',
      title: '把一节真实的课，\n变成一条不会断的学习线。',
      body: '课堂、课后、考试与长期目标，不再是四个互不认识的工具。',
      tabsLabel: '选择学习场景',
      previousScene: '查看上一个学习场景',
      nextScene: '查看下一个学习场景',
      classroomImageAlt: '课堂录音与实时理解',
      scenes: [
        {
          id: 'classroom',
          label: '上课',
          kicker: '听懂现场',
          title: '不只转成文字，还在跟上这节课。',
          body: '原话、板书和课堂脉络按时间排在一起。需要回来的地方先替你留住，听课时不用低头整理。',
          detail: '原话 · 板书 · 课堂脉络',
          metric: '课中',
          imageAlt: '真实试听课中的实时转录、课堂脉络和同学三栏界面',
          proofs: ['实时转录与双语理解', '课堂脉络随音频推进', '卡住时在同一现场直接问同学'] as const,
        },
        {
          id: 'capture',
          label: '放资料',
          kicker: '连起材料',
          title: '课件、网页和随手拍，不再各自孤立。',
          body: '像发消息一样把资料放进来。MeetMind 自动辨认它与哪门课、哪个问题和哪个目标有关。',
          detail: '文件 · 链接 · 图片 · 想法',
          metric: '随手',
          imageAlt: 'MeetMind 真实收集流与文件上传入口',
          proofs: ['文字、链接、图片和文件都能收下', '材料自动接回相关课堂', '需要时直接带着材料问同学'] as const,
        },
        {
          id: 'review',
          label: '课后',
          kicker: '练到会用',
          title: '从老师的原话出发，解释、练习、再验证。',
          body: '闪卡、测验和思维导图不是模板生成，而是从这节课真实讲过的内容里长出来。',
          detail: '解释 · 闪卡 · 测验 · 思维导图',
          metric: '有根',
          imageAlt: '真实课后复习三栏中的原声证据、闪卡训练和 AI 同学',
          proofs: ['左侧保留原声和转录证据', '中间完成闪卡、测验与思维导图', '右侧同学始终知道正在练什么'] as const,
        },
        {
          id: 'exam',
          label: '备考',
          kicker: '跨课整理',
          title: '几节课连成单元，一学期压成考试范围。',
          body: '自由选择课程与课次，生成可编辑、可打印、能真正带进考场的高密度速查表。',
          detail: '多课范围 · 薄弱点 · 可打印速查表',
          metric: '跨课',
          imageAlt: '真实考试速查表跨课程与课堂范围选择界面',
          proofs: ['跨课程勾选真实课堂', '精确选择考试覆盖的课次', '整理成可编辑、可打印的高密度参考表'] as const,
        },
        {
          id: 'context',
          label: '越用越懂',
          kicker: '个人上下文',
          title: '它逐渐知道你会什么，也知道你正在努力什么。',
          body: '客观学习现场与长期理解分开保存。你能看见、纠正、暂停或忘记，掌控权始终在你手里。',
          detail: '目标 · 掌握情况 · 学习方式 · 最近现场',
          metric: '长期',
          imageAlt: 'MeetMind 真实个人上下文中的长期理解、课程考试和最近学习现场',
          proofs: ['最近学习现场保持客观', '长期理解只保留有证据的内容', '随时可以纠正、暂停或忘记'] as const,
        },
      ] as const,
    },
    featureRail: {
      eyebrow: '真实操作 · 连续场景',
      title: '不是功能清单，\n是一条完整的学习路径。',
      body: '左右滑动，每个短片都来自 MeetMind 的真实操作。你看到的不只是结果，还有从课堂现场到理解验证的完整过程。',
      ariaLabel: 'MeetMind 产品功能场景',
      previous: '查看上一个产品场景',
      next: '查看下一个产品场景',
      scenes: [
        {
          id: 'live-class',
          step: '01',
          title: '正在听课',
          body: '原话、课堂脉络和同学一起跟上现场。',
          videoAlt: 'MeetMind 正在实时理解课堂内容',
        },
        {
          id: 'end-class',
          step: '02',
          title: '结束课堂',
          body: '一次点击，把现场收束成可以继续学习的完整证据。',
          videoAlt: '结束 MeetMind 课堂并进入课后整理',
        },
        {
          id: 'evidence-review',
          step: '03',
          title: '从证据开始复习',
          body: '原声和时间点留在左边，练习从老师真正讲过的内容开始。',
          videoAlt: 'MeetMind 课后复习保留原声和转录证据',
        },
        {
          id: 'quiz-submit',
          step: '04',
          title: '选择并提交答案',
          body: '测验不是结果页，而是一次对理解的真实验证。',
          videoAlt: '在 MeetMind 课堂测验中选择并提交答案',
        },
        {
          id: 'evidence-jump',
          step: '05',
          title: '从解释跳回原话',
          body: '每个结论都能回到老师讲过的那一刻。',
          videoAlt: '从测验解释跳回对应的课堂原话',
        },
        {
          id: 'learning-methods',
          step: '06',
          title: '六种学习方式',
          body: '按这节课的内容，继续闪卡、测验、导图或其他练习。',
          videoAlt: 'MeetMind 展示六种基于课堂的学习方式',
        },
        {
          id: 'complete-mindmap',
          step: '07',
          title: '展开完整导图',
          body: '根节点、3 个分支和 9 个节点一次看全，没有裁切。',
          videoAlt: '完整展示根节点、三个分支和九个节点的课堂思维导图',
        },
      ] as const,
    },
    livePreview: {
      status: '可交互试听',
      eyebrow: '一节真的能听、能问、能复习的课',
      title: '现在就坐进这节课里。',
      body: '播放试听课，看看 MeetMind 如何跟着老师往前走；卡住时直接问，下课后继续复习。',
      action: '开始试听',
      frameTitle: 'MeetMind 试听课堂',
    },
    difference: {
      eyebrow: '同一个问题，答案为什么不一样',
      title: '好的回答，来自它知道你为什么现在问。',
      prompt: '“为什么这里可以直接用贝叶斯公式？”',
      genericLabel: '只看见这个问题',
      genericAnswer: '贝叶斯公式描述了条件概率之间的关系。套用公式即可计算后验概率。',
      meetmindLabel: 'MeetMind 还看见',
      contextItems: ['18:42 的老师原话', '刚拍下的板书', '上节课标记的困惑', '两周后的期末目标'],
      meetmindAnswer: '老师这里先把观察范围缩小到了“检测为阳性”的人。你上节课卡住的正是这个条件空间变化，所以这次先不代数，沿着板书把样本空间重新圈一遍。',
    },
    outcomes: {
      eyebrow: '回来时，比发出去的更好',
      title: '一节课、一个单元、一场考试，都有真正能带走的结果。',
      items: [
        {
          number: '01',
          scope: '一节课后',
          title: '知道讲了什么，也知道自己哪里没懂。',
          body: '课堂整理、原话证据、困惑解释和即时练习。',
        },
        {
          number: '02',
          scope: '几节课后',
          title: '零散知识开始连成一个可以调用的结构。',
          body: '单元关系、重复出现的难点和薄弱点复练。',
        },
        {
          number: '03',
          scope: '考试之前',
          title: '把一学期真正压缩成自己带得走的东西。',
          body: '考试范围、复习路线、模拟检验和可打印速查表。',
        },
      ] as const,
    },
    context: {
      eyebrow: '上下文属于你',
      title: '它记住的，你都能改。',
      body: '不用维护标签，也不用管理数据库。它记住的每一条都来自真实的课堂和收藏，你随时看得见，也改得动。',
      panelTitle: '它现在记得',
      memories: [
        { kind: '困惑', text: '条件空间的变化', source: '概率论 · 第 3 讲 18:42' },
        { kind: '目标', text: '期末 85+', source: '概率论与数理统计' },
        { kind: '收藏', text: '贝叶斯定理的直觉解释', source: '来自网页 · 已接回第 3 讲' },
        { kind: '习惯', text: '先听一遍原声，再看整理', source: '最近 4 节课' },
      ] as const,
      actions: { correct: '纠正', pause: '暂停', resume: '恢复', forget: '忘掉' },
      pausedLabel: '已暂停',
      note: '每一条都可以纠正、暂停，或者彻底忘掉。',
    },
    finalCta: {
      eyebrow: '从一节真实的课开始',
      title: '下一次下课，\n别再从头整理。',
      body: '先试听一节完整课堂，看看 MeetMind 如何从听课一直陪到复习。',
      primaryAction: '先试听一节课',
      secondaryAction: '登录 MeetMind',
    },
    desktop: {
      eyebrow: '桌面端',
      title: '装到电脑上，\n它就能听见你在上的课。',
      body: '桌面端让 MeetMind 常驻在屏幕角落：录网课时直接收电脑里的声音，不用带机器人入会；任何画面按一下热键，就截图收进你的学习上下文。',
      macAction: '下载 macOS 版',
      macNote: 'Apple Silicon 芯片',
      macIntelNote: 'Intel 芯片版',
      windowsAction: '下载 Windows 版',
      windowsNote: 'Windows 10 及以上 · 64 位',
      hotkeyHint: '截图热键 Ctrl/Cmd + Shift + M',
      guideAction: '桌面端与桌宠使用说明 →',
      unsignedNote: '安装包暂未签名：macOS 请「右键 → 打开」，Windows 请在 SmartScreen 提示中选「仍要运行」。',
    },
    footer: {
      tagline: '真正懂你在学什么的 AI 同学',
      product: '产品',
      technology: '技术',
      login: '登录',
      copyright: '© 2026 MeetMind',
    },
  },

  technology: {
    label: 'Technology',
    imageAlt: '大学课堂中的 MeetMind 技术现场',
    navigation: {
      product: '回到产品',
      gap: '技术缺口',
      perception: 'MM-Perception',
      memory: 'MM-Memory',
      teacher: 'MM-Teacher',
      roadmap: '路线图',
      openProduct: '体验 MeetMind',
    },
    hero: {
      eyebrow: 'MeetMind Technology',
      title: '师者智能',
      sub: '从理解知识，到理解学习知识的人。',
      punch: '为机器立师者之心。',
      stackLabel: 'MeetMind 师者智能技术栈',
      primaryAction: '了解这条赛道',
      statusLabel: '当前系统',
      statusValue: '课堂场景 · 持续迭代',
    },
    track: {
      eyebrow: '定义赛道',
      title: '大模型能生成答案，\n却还不是老师。',
      body: '成为老师需要的三种基础能力，通用模型三者皆缺。',
      abilities: [
        { title: '连续感知', body: '对真实学习现场的连续感知。' },
        { title: '长期建模', body: '对一个人的长期动态建模。' },
        { title: '教学决策', body: '面向长期成长的教学决策。' },
      ] as const,
      stackLabel: 'MeetMind 正在构建完整的师者智能技术栈',
      stack: [
        { en: 'Perception', cn: '全息多模态理解' },
        { en: 'Memory', cn: '教育记忆模型' },
        { en: 'Teaching Policy', cn: '师者智能大模型' },
      ] as const,
    },
    gap: {
      eyebrow: '技术缺口',
      title: '大模型拥有世界知识，\n但没有学生状态。',
      traditionalLabel: '传统大模型链路',
      traditional: ['问题', '大模型', '回答'] as const,
      oursLabel: 'MeetMind 师者智能链路',
      loop: ['课堂现场', '多模态状态理解', '个体长期记忆', '教学策略选择', '学习结果反馈', '更新对人的理解'] as const,
      loopBack: '回到课堂现场——每一圈，都更懂这个人一点。',
      missCol: '当前大模型缺失',
      oursCol: 'MeetMind 技术',
      rows: [
        { miss: '无法完整感知课堂中的人', ours: '全息多模态理解（视觉 · 听觉）' },
        { miss: '无法跨时间形成个体模型', ours: '教育记忆模型' },
        { miss: '优化回答，不优化人的成长', ours: '师者智能大模型' },
      ] as const,
    },
    perception: {
      eyebrow: 'MM-Perception · 全息多模态理解',
      title: '把课堂还原为可计算的\n"人—知识—情境"状态。',
      inputLabel: '输入',
      inputs: ['语音', '语言', '语调', '视频', '板书', '课件', '提问', '停顿', '标记', '作答行为'] as const,
      techLabel: '核心技术',
      tech: [
        '长时课堂多模态时序对齐',
        '语义、声学、视觉与交互信号联合建模',
        '开放词汇情感理解',
        '多模态证据定位与自然语言解释',
        '课中低延迟实时转写，开口即定稿',
      ] as const,
      outputLabel: '输出',
      outputName: 'Classroom State Representation',
      outputParts: ['知识状态', '认知状态', '情感状态', '证据位置'] as const,
      award: 'ACM Multimedia 2025 · MER2025',
      awardDetail: 'MER-DES 描述式多模态情感理解赛道 · 第一名',
      awardNote: '验证了团队在多模态情感证据提取与开放式情感推理上的领先能力。',
    },
    memory: {
      eyebrow: 'MM-Memory · 教育记忆模型',
      title: '从学习事件流中，形成\n可更新的个体模型。',
      inputLabel: '输入',
      input: '课堂状态 + 提问 + 错误 + 练习结果 + 用户反馈',
      layersLabel: '记忆架构',
      layers: [
        { en: 'Episodic Memory', cn: '情节记忆', body: '保留某节课、某次错误的完整现场。' },
        { en: 'Semantic Memory', cn: '语义记忆', body: '提炼知识掌握与概念关系。' },
        { en: 'Cognitive Memory', cn: '认知记忆', body: '建模长期困惑、推理习惯与理解方式。' },
        { en: 'Affective Memory', cn: '情感记忆', body: '建模情感状态随场景和时间的变化。' },
        { en: 'Evidence Layer', cn: '证据层', body: '每条长期理解，都可以回到原始证据。' },
      ] as const,
      questionsLabel: '记忆要回答的五个问题',
      questions: ['什么值得写入？', '什么时候应该更新？', '发生冲突相信什么？', '什么已经过期？', '当前任务应该读取什么？'] as const,
      note: '教育记忆不是"记得越多越好"。',
      outputLabel: '输出',
      outputName: 'Dynamic Learner Model',
      outputBody: '可追溯、可更新、可纠正的学习者状态。',
    },
    teacher: {
      eyebrow: 'MM-Teacher · 师者智能大模型',
      title: '从"生成回答"，升级为\n"选择教学行动"。',
      inputLabel: '输入',
      inputs: ['当前课堂状态', '个体长期记忆', '学习目标', '历史教学结果'] as const,
      actionsLabel: '在多个教学行动中，选择此刻最合适的一种',
      actions: ['解释', '举例', '追问', '诊断', '练习', '提示', '挑战', '鼓励', '等待', '回放', '连接过去经验'] as const,
      objectivesLabel: '优化目标',
      objectives: [
        { label: '传统语言模型', formula: 'maximize P(next token)' },
        { label: '传统任务型 Agent', formula: 'maximize task completion' },
        { label: '师者智能模型', formula: 'maximize long-horizon learner development' },
      ] as const,
      objectivesNote: '同时优化：知识掌握、迁移能力、学习效率、情感状态、自主学习能力与长期成长结果。',
      outputLabel: '输出',
      outputName: 'Teaching Policy',
      outputBody: '对这个人，此刻最合适的下一步行动。',
      punch: '这才是"师者智能大模型"的技术含义——\n而不是一个更温暖的聊天模型。',
    },
    flywheel: {
      eyebrow: '训练闭环',
      title: '最稀缺的数据结构：\n状态—干预—结果。',
      steps: ['老师讲了什么', '学生当时处于什么状态', 'AI 采取了什么教学行动', '学生之后是否真正学会', '更新模型与个体记忆'] as const,
      center: '状态\n干预\n结果',
      body: '互联网语料只有"问题—答案"；真实课堂给出更稀缺的"状态—干预—结果"。',
      punch: '值钱的不是录音，是教学行动与学习结果之间的反馈信号。',
    },
    product: {
      eyebrow: '产品入口',
      title: '师者智能的\n第一个产品现场。',
      userLabel: '用户今天获得',
      userItems: ['真正听过课的 AI 同学', '基于课堂原话与板书的回答', '困惑定位、时间回跳与证据引用', '基于真实课堂生成的练习和复习', '跨课堂持续积累的个人学习上下文'] as const,
      systemLabel: '技术系统今天获得',
      systemItems: ['连续多模态课堂输入', '真实学习行为', '个体状态变化', '教学干预反馈', '长期学习结果'] as const,
      punch: 'MeetMind 是师者智能的产品入口、数据闭环与真实评测场。',
    },
    moat: {
      eyebrow: '技术壁垒',
      title: '三层技术，\n共同形成壁垒。',
      formula: ['多模态感知能力', '教育长期记忆', '教学决策闭环'] as const,
      formulaResult: '师者智能',
      items: [
        { title: '算法壁垒', body: '多模态情感推理、教育记忆与教学策略模型。' },
        { title: '数据结构壁垒', body: '不是普通内容数据，而是"状态—干预—结果"的长期序列。' },
        { title: '评测壁垒', body: '能够同时评估感知、记忆、教学行动和长期学习效果。' },
        { title: '产品闭环壁垒', body: '真实课堂中持续产生输入、反馈与验证结果。' },
      ] as const,
    },
    roadmap: {
      eyebrow: '路线图',
      title: '从师者智能，\n到人格智能平台。',
      phases: [
        { phase: 'Phase 1', title: '全息多模态理解' },
        { phase: 'Phase 2', title: '教育记忆模型' },
        { phase: 'Phase 3', title: '师者智能大模型' },
        { phase: 'Phase 4', title: '人格智能平台' },
      ] as const,
      punch: '情感智能理解一个人的当下；人格智能理解一个人的连续性；师者智能让这种理解产生有益于人的行动。',
    },
    finalCta: {
      title: '想看真实链路\n或合作方案？',
      body: '我们愿意讨论技术，而不是只展示一张架构图。',
      productAction: '先体验产品',
      contactAction: '联系 MeetMind',
      contactHref: 'mailto:originedu@meetmind.online',
    },
    footer: {
      label: 'MeetMind Technology',
      product: '产品首页',
      app: '打开产品',
      copyright: '© 2026 MeetMind',
    },
  },

  cta: {
    demo: '看一节示例课',
    record: '开始一节课',
    ask: '问同学',
  },

  navigation: {
    back: '返回',
    classroom: '课堂',
    collection: '收集',
    search: '问同学',
    allCollections: '全部收集',
  },

  globalAsk: {
    title: '问同学',
    subtitle: '相关课堂、资料和你的上下文会自动接上。',
    welcomeEyebrow: '从你正在学的地方继续',
    quickMode: '直接回答',
    deepMode: '陪我学会',
    modeSelectorLabel: '选择问同学的方式',
    quickModeBody: '马上回答，自动接上相关内容',
    deepModeBody: '先理解目标，再陪你走完整过程',
    memoryAction: '我的上下文',
    newConversation: '新对话',
    historyRestored: '已接回上次对话',
    historyLoading: '正在接回上次对话…',
    freshConversation: '新的对话',
    emptyTitle: '此刻，想弄明白什么？',
    emptyBody: '直接说就好。MeetMind 会自己找到相关课堂、材料和你之前留下的线索。',
    deepEmptyTitle: '这次，想真正学会什么？',
    deepEmptyBody: 'MeetMind 会先理解你要达到的结果，再陪你解释、练习和验证；只有必要时才问一个选择。',
    quickExamples: ['帮我解释刚才课堂里最难的概念', '把这份材料和我最近学的内容连起来'] as const,
    deepExamples: ['我想系统学懂这个主题，并检验自己是否真的会了', '围绕期末目标，把相关课堂整理成一条学习路线'] as const,
    composerQuick: '问任何正在学、正在想的事',
    composerDeep: '说说这次想真正学会什么',
    reasoningTitle: '思考过程',
    reasoningStreaming: '同学正在想…',
    startersTitle: '也可以从这里开始',
    send: '发送',
    stop: '停止',
    preparingIntent: '正在接上相关内容…',
    intentEyebrow: '先对齐一件事',
    intentProgress: (current: number, total: number): string => `${current} / ${total}`,
    intentSingle: '选一个就好',
    intentMultiple: '可以多选',
    intentCancel: '直接开始',
    intentBack: '上一步',
    intentContinue: '继续',
    intentResolve: '继续',
    intentStart: '开始学习',
    intentFirstStep: '先从这里开始',
    approachUnderstand: '理解清楚',
    approachPractice: '练到会用',
    approachSynthesize: '串成体系',
    approachCreate: '做出结果',
    contextPersonal: '用长期上下文',
    contextCurrent: '用当前内容',
    contextMixed: '两边一起看',
    contextStatus: '已接入',
    contextAction: '参考范围',
    contextSummary: (current: number, recent: number, memory: number): string => {
      const parts = [
        current > 0 ? `${current} 份当前内容` : '',
        recent > 0 ? `${recent} 条最近学习` : '',
        memory > 0 ? `${memory} 条长期理解` : '',
      ].filter(Boolean);
      return parts.length > 0 ? `会参考 ${parts.join('、')}` : '这次先从你的问题开始';
    },
    contextCurrentCount: (count: number): string => `${count} 份当前材料`,
    contextRecentCount: (count: number): string => `${count} 条最近学习`,
    contextMemoryCount: (count: number): string => `${count} 条长期记忆`,
    contextEmpty: '这次先从你的问题开始',
    contextRailEyebrow: '上下文已就位',
    contextRailTitle: '这次会用到什么',
    contextRailBody: '只展示实际接入的内容。回答仍以你此刻的问题为准。',
    contextDrawerCurrent: '当前内容',
    contextDrawerRecent: '最近学习现场',
    contextDrawerRecentBody: '用来接续你刚才做到的地方',
    contextDrawerMemory: '长期学习理解',
    contextDrawerMemoryBody: '只使用你已确认或可随时纠正的内容',
    contextConnected: '已接入这次对话',
    contextWaiting: '有内容后自动接入',
    contextActiveThread: '正在继续的学习',
    progressEyebrow: 'MeetMind 更新了对你的理解',
    progressHint: '这些理解会随着之后的学习继续调整。',
    progressDismiss: '这次不记',
    progressSave: '记住确认的',
    progressSaved: '已经记下，也可以随时纠正',
    memoryTitle: '我的上下文',
    memoryBack: '返回',
    contextLibraryNavigation: '浏览上下文',
    contextCoursesOverviewTitle: '课程与考试',
    contextCoursesOverviewBody: '查看课堂如何归入课程、纠正课程边界，或跨课程选择考试范围。',
    memoryUnderstandingTab: '对我的理解',
    memoryCoursesTab: '课堂上下文',
    memoryRecentTab: '客观记录',
    memoryUnderstandingTitle: 'MeetMind 记得的你',
    courseContextTitle: '我的课程',
    courseContextEmpty: '录下一节课后，课程会自动在这里出现。',
    courseContextLessons: (count: number): string => `${count} 节课`,
    courseContextMinutes: (count: number): string => `${count} 分钟`,
    courseContextActive: '正在参考',
    courseContextPaused: '已暂停参考',
    courseContextSuggested: '待确认',
    courseContextUnclassified: '单节课堂',
    courseContextDetached: '已移出',
    courseContextRename: '改课程名',
    courseContextRenameHint: '例如：线性代数',
    courseContextTags: '课程标签',
    courseContextTagsHint: '例如：专业课、期末重点',
    courseContextSave: '确认',
    courseContextCancel: '取消',
    courseContextPause: '暂不参考这门课',
    courseContextResume: '重新参考这门课',
    courseContextDetails: '查看课堂',
    courseContextCollapse: '收起课堂',
    courseContextConfirm: '确认属于同一门课',
    courseContextDetach: '移出',
    courseContextDetachTitle: (title: string): string => `将“${title}”移出这门课`,
    courseContextRestore: '放回原课程',
    courseContextCheatsheet: '单元速查表',
    courseCheatsheetEntryEyebrow: '跨课与考试',
    courseCheatsheetEntryTitle: '考试速查表',
    courseCheatsheetEntryBody: '从多门课程、课堂录音和上传材料中直接勾选考试范围，整理成可编辑、可打印的高密度参考表。',
    courseCheatsheetEntryAction: '选择考试范围',
    courseCheatsheetEntryCourseAction: '从这门课开始',
    courseCheatsheetEntryEmpty: '至少保留两节有原文的课堂后，就可以直接组合考试范围。',
    courseCheatsheetEntryAvailable: (courses: number, lessons: number): string => `${courses} 门课程 · ${lessons} 节课堂可选`,
    courseCheatsheetScopeEyebrow: '多课程范围',
    courseCheatsheetScopeHint: '课程只是帮你快速定位，不是限制。可以跨课程勾选，也可以精确到某一节课堂。',
    courseCheatsheetCoursesLabel: '课程',
    courseCheatsheetClear: '清空',
    courseCheatsheetSelectionSummary: (courses: number, lessons: number): string => `已选 ${courses} 门 · ${lessons} 节`,
    courseCheatsheetCourseSelection: (selected: number, total: number): string => `${selected}/${total} 节已选`,
    courseCheatsheetEmptySelectionTitle: '先选择课程',
    courseCheatsheetEmptySelectionBody: '选中课程后，可以继续精确到具体课堂。',
    courseCheatsheetMinimumHint: '至少选择两节有原文的课堂',
    courseContextCombinedScope: (count: number): string => `${count} 门课程的考试范围`,
    courseContextBackToCourse: '返回课程',
    courseContextCheatsheetNeedsTranscript: (count: number): string => count === 0
      ? '这些课堂还没有可用原文。'
      : `目前只有 ${count} 节课有可用原文，至少需要两节。`,
    courseContextChooseLessons: '这次要带上哪些课？',
    courseContextChooseLessonsHint: '先选同一单元或同一考试范围；最近四节已替你选好。',
    courseContextSelectAll: '全选',
    courseContextBeginCheatsheet: (count: number): string => `用这 ${count} 节课整理`,
    courseContextCheatsheetLoading: '正在把这几节课压成一份纸面速查表',
    courseContextCheatsheetNotReady: '所选内容里还没有足够稳定的学科知识，暂时做不出可靠的考试速查表。课堂原文已经保留，可以返回课程后换一组范围。',
    courseContextRecording: '录音',
    courseContextUpload: '上传',
    courseContextVideo: '视频',
    courseContextUntitled: '待命名课程',
    courseContextRecordingLesson: '课堂录音',
    courseContextUploadLesson: '上传课堂',
    courseContextVideoLesson: '视频课堂',
    courseContextFallbackTitle: (month: number, day: number): string => `${month} 月 ${day} 日的课`,
    courseContextLessonFallbackTitle: (month: number, day: number, time: string): string => `${month} 月 ${day} 日 ${time} 的课`,
    courseContextScheduleTitle: (weekday: string): string => `${weekday}的课`,
    courseContextRecurring: (weekday: string, time: string): string => `常在${weekday} ${time} 上课`,
    courseAssessmentAdd: '这门课有考试',
    courseAssessmentEditTitle: '考试',
    courseAssessmentDefaultName: (courseTitle: string): string => `${courseTitle}考试`,
    courseAssessmentName: '考试名称',
    courseAssessmentNameHint: '例如：期末考试',
    courseAssessmentDate: '考试日期',
    courseAssessmentMode: '考试方式',
    courseAssessmentUnknown: '还不确定',
    courseAssessmentClosedBook: '闭卷',
    courseAssessmentOpenBook: '开卷',
    courseAssessmentScope: '考试范围',
    courseAssessmentScopeHint: '可选：粘贴老师公布的范围或大纲',
    courseAssessmentHasScope: '已有范围',
    courseAssessmentSave: '记下',
    courseAssessmentStop: '不再准备',
    courseAssessmentEdit: '修改考试信息',
    courseAssessmentPrepare: '做速查表',
    courseAssessmentChooseScope: '哪些课在考试范围内？',
    memoryKindPreference: '学习方式',
    memoryKindStrength: '正在形成的能力',
    memoryKindChallenge: '还在弄懂',
    memoryKindTopic: '正在关注',
    memoryKindProgress: '最近进展',
    memorySourceUser: '你告诉 MeetMind 的',
    memorySourceAi: '从你的学习互动中理解到的',
    memoryCorrection: '不太准确',
    memoryAddContext: '补充一下',
    memoryCorrectionHint: '换成更准确的说法',
    memoryCorrectionSave: '改好了',
    memoryCorrectionCancel: '取消',
    memoryMore: '更多操作',
    memoryStopUsing: '暂不参考',
    memoryUseAgain: '重新参考',
    memoryForget: '忘记这条',
    memoryTalkPrompt: '关于我，想补充或纠正的是：',
    memoryEmpty: '还没有形成稳定的理解。先正常学习就好，MeetMind 会从真实过程里慢慢认识你。',
    memoryPaused: '已不再参考',
    recentTitle: '最近学习现场',
    recentEmpty: '最近还没有可恢复的学习活动。',
    recentKindConversation: '一次对话',
    recentKindLesson: '一节课堂',
    recentKindApp: '一次练习',
    recentKindCapture: '一份学习材料',
    recentShowAll: (count: number) => `查看全部 ${count} 条学习现场`,
    recentCollapse: '收起较早记录',
    threadTitle: '上次还在继续',
    threadResume: '接着学',
    threadComplete: '这条学完了',
    preparingError: '这次没理解准，先直接回答你。',
    refiningError: '先按目前的理解开始，之后还可以随时调整。',
    responseError: '刚才没有接上，再发一次就好。',
    sourceContext: '刚刚在看的内容',
    sourceCurrentLesson: '当前课堂转录',
    openSource: '打开原内容',
    close: '关闭问同学',
    assistantLabel: 'MeetMind 回答',
    userLabel: '你的问题',
    thinking: '正在把上下文接起来…',
    recentConversation: '问同学的对话',
    recentDeepSession: '一起学的对话',
    recoveryEyebrow: '接回学习现场',
    recoveryTitle: '不用重新开始',
    recoveryBody: 'MeetMind 留住了上次的脉络，回来可以直接接着走。',
    recoveryResume: '接着上次学',
    recoveryRecent: '最近停在这里',
    appActivity: (name: string) => `完成了「${name}」`,
    appResultSummary: (count: number) => `生成了 ${count} 条可继续使用的学习内容`,
  },

  tutor: {
    emptyAfterName: '在这里。',
    reviewStarters: ['先讲清这节课的主线', '从我标记的地方开始'] as const,
  },

  actionList: {
    title: '今晚行动清单',
    emptyTitle: '还没有行动项',
    emptyBody: '标记一处困惑后，同学会把下一步放在这里。',
    completedTitle: '今天先到这里',
    completedBody: '行动项已经全部完成。',
    closeHint: '按 ESC 或点击空白处关闭',
  },

  collection: {
    askClassmate: '问同学',
    emptyTitle: '想到什么，就留在这里。',
    emptyBody: '不用分类，不用打标签。同学会在后台把它接回相关的课堂、目标和问题。',
    /** 空态四张自解释入口卡（上传/链接/写一句/录一段），key 供组件映射图标与动作 */
    emptyEntries: [
      { key: 'upload', label: '上传', hint: '文件、音频、视频、图片' },
      { key: 'link', label: '链接', hint: '贴个网页或视频链接' },
      { key: 'write', label: '写一句', hint: '想法、困惑、随手记' },
      { key: 'voice', label: '录一段', hint: '语音直接留下来' },
    ] as const,
    emptyWechatHint: '也可以从微信直接发给我。',
    deleteMemoryWarning: '删除后，这条内容不会再进入同学的回答、后续情报和个人上下文。',
    permanentDeleteWarning: '彻底删除后，这条内容不会再进入同学的回答、后续情报和个人上下文。',
    today: '今天',
    selecting: '选择中',
    scrollToLatest: '跳转到最新消息',
    historyTitle: '历史收集',
    menuTitle: '收集菜单',
    statusOrganizing: '正在整理',
    statusOrganizingLesson: '正在整理这节课…',
    statusUnderstood: '已理解',
    statusFailed: '失败',
    videoParsed: (count: number): string => `已解析 · ${count}句`,
    videoParseStale: '解析未完成，换个浏览器再试',
    selectedLabel: '已选',
    transcriptShow: '查看文字',
    transcriptHide: '收起文字',
    playAudio: '播放音频',
    pauseAudio: '暂停音频',
    composerPlaceholder: '发一句想法，贴个链接，或者先把这节课丢进来',
    composerPlaceholderQuotedMulti: '继续顺着这几条内容写...',
    composerPlaceholderQuotedSingle: (typeLabel: string): string => `继续顺着这条${typeLabel}写...`,
    filesReceived: (count: number): string => (count > 1 ? `${count} 个文件已收下` : '文件已收下'),
    confusionNudge: '我现在没懂的是：',
    topBarRecordingVoice: '正在收一段语音',
    topBarReceivingFiles: (count: number): string => `正在收进 ${count} 个文件`,
    voiceRecording: '语音录制中',
    voiceIdleHint: '继续说下去，停下后这段语音会直接留在这里。',
    echoUpdatedHint: '今日情报已根据你的收藏更新',
    // ── 收集菜单面板 ──
    menuSummary: (totalCount: number, activeDays: number): string => `已收 ${totalCount} 条 · 活跃 ${activeDays} 天`,
    menuStreakActive: (days: number): string => `已经连续 ${days} 天在收`,
    menuStreakIdle: '先从今天收一点开始',
    menuTopKinds: (kinds: string): string => `最近收得最多的是：${kinds}`,
    menuIdleHint: '一句困惑、一张图、一份讲义或一段录音，都可以先发进来。',
    menuAllCollectionsDesc: '从以前收进来的课、图和材料里继续接着学。',
    menuEchoActiveHint: '同学正在把你的收藏与目标连起来。',
    menuEchoIdleHint: '先继续收集，有根据的情报会自动出现。',
    activityKind: {
      audio: '录音',
      video: '视频',
      image: '图片',
      document: '材料',
      text: '想法',
    } as Record<string, string>,
    // ── 消息操作菜单 / 多选栏 ──
    actionGoReview: '去复习',
    actionQuote: '引用',
    actionSelect: '选择',
    actionDeselect: '取消选择',
    actionEdit: '编辑',
    actionOpenOriginal: '打开原件',
    actionArchive: '先收起',
    actionCancel: '取消',
    actionConfirmDelete: '确认删除',
    actionDelete: '删除',
    actionRemoveFromFlow: '删除这条',
    multiSelected: '已加入多选',
    selectionCount: (count: number): string => `${count} 条`,
    selectionHint: '已加入这次操作',
    selectionDeleteWarning: '再点一次删除，就会彻底移除这些内容。',
    exitSelection: '退出多选',
    // ── 引用上下文预览 ──
    quotedMulti: (count: number): string => `已引用 ${count} 条内容`,
    quotedAudio: '已引用一段录音',
    quotedSingle: (typeLabel: string): string => `已引用${typeLabel || '内容'}`,
    quotedAutoImport: '发送后自动解析',
    clearQuote: '取消引用',
    uploadFiles: '上传文件',
    dictationTitle: '说一段（备忘录式短录音——完整录一节课请到课堂 Tab）',
    dictationLabel: '说一段',
    sendToCollection: '发送到收集流',
    // ── 整理提示（pulse）：一句话 + 最多两个动作，安静出现在收集流顶部 ──
    pulse: {
      chipAudio: (count: number): string => `${count} 段课堂录音`,
      chipDocument: (count: number): string => `${count} 份材料`,
      chipImage: (count: number): string => `${count} 张图片材料`,
      chipText: (count: number): string => `${count} 条你的想法`,
      chipVideo: (count: number): string => `${count} 个视频来源`,
      recording: {
        title: '正在整理',
        body: '这段语音正在和前面的内容接到同一条学习线索里，你不用先整理它。',
      },
      primaryAndSupport: {
        title: '新的整理提示',
        body: '你已经把课堂录音和补充材料放进了同一条线索。后面不需要总结，继续轻轻往里加就行。',
        actions: [
          { key: 'continue-voice', label: '再录一段' },
          { key: 'capture-confusion', label: '补一句困惑' },
        ],
      },
      audioMany: {
        title: '新的整理提示',
        body: '你已经连续留下了几段课堂录音，这节课的主线开始显出来了。',
        actions: [
          { key: 'capture-confusion', label: '记下没懂的点' },
          { key: 'add-material', label: '贴一份讲义' },
        ],
      },
      audioAndText: {
        title: '新的整理提示',
        body: '你不只是在收课堂内容，也已经留下了自己的理解或困惑，这会让后面的同桌更有抓手。',
        actions: [
          { key: 'continue-voice', label: '继续录音' },
          { key: 'add-material', label: '补充材料' },
        ],
      },
      materialAdded: {
        title: '新的整理提示',
        body: '这份材料已经接进来了。后面再补一句当时没懂的地方，同桌会更容易看出联系。',
        actions: [
          { key: 'capture-confusion', label: '记下没懂的点' },
          { key: 'continue-voice', label: '录一段语音' },
        ],
      },
      audioAdded: {
        title: '新的整理提示',
        body: '这段录音已经留下来了。先别急着整理，继续往里丢材料或困惑，会更有价值。',
        actions: [
          { key: 'capture-confusion', label: '补一句困惑' },
          { key: 'add-material', label: '贴一份材料' },
        ],
      },
      fallback: {
        title: '新的整理提示',
        body: '这条收集流已经开始有自己的形状了。继续轻轻追加，不用一次说完整。',
        actions: [
          { key: 'continue-voice', label: '继续录音' },
          { key: 'capture-confusion', label: '写一句想法' },
        ],
      },
    },
  },

  login: {
    subtitle: '真正懂你在学什么的 AI 同学',
    guestCta: '先试听一节课',
    accountTab: '账号登录',
    emailLabel: '邮箱地址',
    emailPlaceholder: '请输入邮箱地址',
    passwordIdentifierLabel: '邮箱或管理员用户名',
    passwordIdentifierPlaceholder: '请输入邮箱或管理员用户名',
  },

  wechatAgent: {
    rateLimited: '今天聊得够多了，明天再接着聊。',
    failed: '这边卡了一下，稍后再跟我说一次。',
  },
  wechatPodcast: {
    /** 小宇宙链接的即时回执（区别于泛视频链接） */
    receipt: '接住了，是小宇宙播客。转写好了我跟你说。',
    importDone: (title: string, minutes: number): string => `《${title}》转写好了，约 ${minutes} 分钟。`,
    importDoneCta: '点这看看',
    importFailed: (reason?: string): string => reason
      ? `这集转写没成功（${reason}），可以再发一次试试。`
      : '这集转写没成功，可以再发一次试试。',
    duplicate: '这集之前收过了，在这 →',
  },
  player: {
    loadingAudio: '加载音频',
    preparingWaveform: '原声已收下，正在准备波形…',
    loadFailed: '音频加载失败',
    loadFailedHint: '这段原声暂时无法播放，刷新页面或重新进入试试',
  },
  wechatQr: {
    loginAction: '微信扫码登录',
    inWechatAction: '微信登录',
    bindAction: '绑定微信',
    loginTitle: '微信扫码登录',
    bindTitle: '绑定微信账号',
    loginBody: '打开微信扫一扫，确认后这里会自动登录。',
    bindBody: '用要绑定的微信扫码，之后也可以直接用它登录。',
    loading: '正在准备二维码…',
    pending: '等待扫码',
    scanned: '已扫码，正在确认…',
    processing: '正在接上你的账号…',
    loginDone: '登录成功，正在进入 MeetMind…',
    bindDone: '微信已经绑定',
    expiresHint: '二维码 5 分钟内有效',
    expired: '二维码已过期，请刷新后再扫。',
    failed: '这次没有接上，请刷新后重试。',
    retry: '刷新二维码',
    close: '关闭',
    imageAlt: '微信扫码登录二维码',
    bindImageAlt: '微信账号绑定二维码',
    boundToast: '微信账号已绑定',
    mpConfirmed: '已确认，请回到电脑继续。',
    mpExpired: '二维码已过期，请回到电脑刷新后再试。',
    unavailable: '微信扫码登录暂时不可用',
    bindRequiresLogin: '请先登录再绑定微信',
    createFailed: '二维码没有生成，请稍后重试',
    tooManyRequests: '二维码刷新太频繁，请稍后再试',
    sessionMissing: '二维码会话不存在',
    pollFailed: '扫码状态没有接上，请重试',
    identityLinkFailed: '微信账号连接失败',
    identityConflict: '该微信已绑定其他账户',
    identityCreateFailed: '创建用户失败',
    bindFailed: '绑定失败，请重试',
    loginFailed: '登录失败，请重试',
  },

  loading: {
    preparing: '正在准备课堂空间',
    restoring: '正在接回你的学习现场',
    entering: '马上进入',
    fallback: '正在准备学习空间',
  },

  hero: {
    eyebrow: 'MEETMIND · AI 同学',
    title: '陪你听懂每一节课。',
    subtitle: '老师讲到哪，我就听到哪。卡住时当场问；下课后，每个答案都能回到原话。',
    sideHint: '先听 90 秒示例课',
    evidencePromise: '回答有依据，点击时间就能回到老师原话。',
    proofStatus: '正在一起听',
    proofQuote: 'The exact timing is still up in the air.',
    proofTime: '00:31',
    proofLabel: '同学听懂了',
    proofAnswer: '这里不是“在空中”，而是“具体时间还没有决定”。',
    proofAction: '进入这节示例课',
  },

  lesson: {
    summaryReady: '笔记总结',
    keyPoints: '重点',
    reviewed: '已复习',
    materials: (count: number): string => `${count} 份材料`,
    actionReady: '继续复习',
    actionReviewed: '再看一遍',
    actionProcessing: '整理中',
    actionFailed: '原声已保留',
    actionUpcoming: '准备上课',
  },

  demo: {
    reviewBannerTitle: '这是示例课',
    reviewBannerBody: '你的课堂会出现在课堂列表里，随时可以录自己的第一节。',
    reviewBannerAction: '去录我自己的课',
    reviewBannerLoginAction: '登录，留住这节课',
    reviewBannerDismiss: '继续看示例课',
  },

  classroomHome: {
    commandEyebrow: '今天',
    title: '今天，继续学懂一件事。',
    outcomeTitle: '内容进来之后',
    outcomeHint: '不只保存，还会继续变成能用的学习结果。',
    today: '今天',
    yesterday: '昨天',
    active: '正在上课',
    launchpadTitle: '补充学习上下文',
    launchpadHint: '材料和问题会自动接到相关课堂',
    actionRecordTitle: '开始一节课',
    actionRecordBody: '录线下课、网课或讨论，边听边形成课堂脉络。',
    actionRecordLabel: '选择声音开始',
    actionMaterialTitle: '放入材料',
    actionMaterialBody: '文档、网页、音视频会自动接到相关课堂和目标。',
    actionMaterialLabel: '选择文件或链接',
    actionSearchTitle: '问课堂和资料',
    actionSearchBody: '带上课堂、资料和目标，直接说你想弄懂什么。',
    actionSearchLabel: '搜索我的内容',
  },

  sourceType: {
    audio: '录音',
    video: '视频',
    image: '图片',
    document: '文章',
    text: '笔记',
  },

  sourceOrigin: {
    quickNote: '速记',
    wechat: '从微信发来',
    wechatArticle: '微信公众号',
    bilibili: '哔哩哔哩',
    youtube: 'YouTube',
  },

  sourceState: {
    extracting: '正在读取正文',
    complete: '正文完整',
    partial: '仅取得摘要',
    linkOnly: '已保存原链接',
    failed: '读取失败，原链接已保留',
  },

  sourceReader: {
    saved: '已收下',
    untitled: '未命名内容',
    openOriginal: '查看原文',
    noBody: '正文暂时没有读取出来，原始内容仍然保留。',
  },

  listening: {
    idle: '我在。',
    hearing: '我在听。',
  },

  classroomFlow: {
    eyebrow: '课堂脉络',
    listeningTitle: '等老师进入正题。',
    understanding: '正在接住刚才这段。',
    refreshing: '正在接住刚才这段',
    now: '正在讲',
    recent: '刚才怎么走到这里',
    recentHint: '只留与当前有关的推进',
    keep: '留到课后',
    mobileFlow: '脉络',
    mobileTranscript: '原话',
    kindDefinition: '定义',
    kindFormula: '公式',
    kindExample: '例子',
    kindQuestion: '待弄清',
    kindContrast: '对比',
    kindConclusion: '结论',
    kindOther: '值得回来',
  },

  stages: {
    /** v3.0：放弃假分阶段叙事，改为 Octo Buddy 听课的诚实表达
     *  app loading 文案根据 appName 动态拼，用 listening 系列 */
    reading: '正在读你的课堂',
    selecting: '正在挑核心',
    composing: '正在排版',
    slow: '稍等一下——内容多的时候我也要再想想',
    /** v3.0 新版 loading 文案 */
    listenStart: (appName: string): string => `在听这节课，给你${appName}`,
    listenSlow: '内容有点多，我多听一会儿',
    listenVerySlow: '还在听——再给我一点时间',
  },

  stop: {
    heard: '这节课我听完了。',
    /**
     * 停止后的总结一句话。
     * 例："共 47 句，标了 2 处你标的困惑。"
     */
    summary: (sentences: number, confusions: number): string => {
      if (sentences <= 0) return '这次只录到很少内容。';
      const base = `共 ${sentences} 句`;
      if (confusions > 0) return `${base}，标了 ${confusions} 处你标的困惑。`;
      return `${base}。`;
    },
    suggestCheatsheet: '要不要我整一张速查表？',
    actionMakeCheatsheet: '整速查表',
    actionViewTranscript: '看文字',
  },

  octoBuddy: {
    idle: '同学在这',
    listening: '陪你听课',
    thinking: '我想一下',
    happy: '接住了',
    surprised: '哎？',
    love: '我在',
    angry: '别一直戳我',
    sleeping: '待命中',
    openHint: '点开一起听',
    openPanel: '打开同学面板',
    dragHint: '单击逗我 · 双击打开同学 · 可拖动',
    hoverLine: '我看到你啦',
    patHappy: '嘿嘿，我在',
    patLove: '今天也一起学',
    patSurprised: '哎？轻一点',
    patAngry: '别一直戳我',
    wakeLine: '醒啦醒啦',
  },

  companion: {
    placeholderIdle: '问问同学…',
    placeholderListening: '老师刚说的那个啥意思？',
    shortcutHint: '有问题？⌘K 问同学',
    newCourseGreet: '我在这里。等你录第一节课，我就开始陪你。',
    defaultLightPrompts: ['刚才那句我没跟上', '这段在讲什么？', '帮我抓一下题眼'] as const,
    quickRecap: '刚才那段',
    quickRecapQuestion: '刚才那段讲了什么？',
    quickCatchUp: '我没跟上',
    quickCatchUpQuestion: '我没跟上，帮我接一下主线。',
    quickMark: '记一下',
    idleStatus: '待命中',
    afterClassStatus: '听完了',
    listeningStarter: '卡住直接问。',
    afterClassStarter: '听完了，换我带你练一下。',
    pending: '正在想…',
    emptyListeningPrimary: '我在听，有问题随时问我。',
    emptyListeningSecondary: '我会把刚才那段记住，你不用急着整理。',
    emptyIdlePrimary: '把第一节课录下来，我们就认识了。',
    actionPrompt: '也可以让我直接整理',
    contentPrompt: '已经有内容？试试',
    foresightCount: (count: number): string => `${count} 个预感`,
    foresightDismiss: '划掉',
    foresightAccept: '就这个 · 问下去',
    errorTitle: '同学刚刚没接上',
    errorBody: '只影响这次对话，你的课堂和复习内容都还在。',
    errorRetry: '重新连接',
  },

  /** 桌面端小窗（/companion）：随手记、随口问，不出小窗完成 */
  desktopPanel: {
    title: 'MeetMind 同学',
    subtitle: '随手记，随口问',
    modeAsk: '问',
    modeNote: '记',
    placeholderAsk: '问点什么，Enter 发送…',
    placeholderNote: '记下这一刻，Enter 收下…',
    send: '发送',
    noteSaved: '收下了',
    noteFailed: '这次没收下，再试一次。',
    askFailed: '这次没答上来，再试一次。',
    thinking: '正在想…',
    loginHint: '先在主窗口登录，小窗就能用了。',
    loginAction: '去登录',
    screenshot: '截图收进来',
    recordClass: '去录课',
    openFull: '打开完整 MeetMind',
    collapse: '收起',
  },

  recording: {
    sourcePrompt: '这节课的声音从哪里来？',
    backToLessons: '返回课程列表',
    sourceMic: '麦克风',
    sourceSystem: '电脑声音',
    sourceMixed: '两路都录',
    sourceMicHint: '线下课',
    sourceSystemShortHint: '在线课程',
    sourceMixedHint: '网课＋自己提问',
    sourceSystemHint: '开始后，在系统窗口勾选“分享音频”。',
    activeStatus: (source: string): string => `正在听 · ${source} · 点开看实时文字`,
    /** mixed 模式系统音频采集失败、降级为纯麦克风时提示 */
    downgradeFromMixed: '电脑声音没录到，只用麦克风在录',
    startFailedFallback: '没有接上录音设备，请检查麦克风权限后再试。',
    recorderNotReady: '录音组件还没准备好，请再点一次。',
    /** 课中「截取这一页」：从屏幕流抓当前帧挂到课堂时间轴 */
    captureFrame: '截取这一页',
    captureFrameSaved: '这一页收下了',
    captureFrameFailed: '没截到，再试一次。',
    startFailed: (reason: string): string => `还没有开始录音。${reason}`,
    finished: '这节课收好了',
    /** 断连缓冲溢出导致音频帧被丢弃时的持续提示（累计秒数） */
    audioGapWarning: (seconds: number): string =>
      `刚才连接不稳，约有 ${seconds} 秒的声音没能转成文字。`,
    /** 重录确认：旧录音会先按正常停录保底落库，再开始新录音 */
    restartConfirm: '确定要重新开始吗？当前这段会先收好，再从零录一段新的。',
    /** 录音中持续检测到零音量（PCM 链路静默）时的一次性提醒 */
    silentAudioWarning: '一直收不到声音，文字不会生成。请检查麦克风或声音来源后重录。',
    finalizingTranscript: (count: number, enhancedCount = 0): string =>
      `实时文字已收下，正在用原声定稿 · ${count} 段${enhancedCount > 0 ? ` · 已优化 ${enhancedCount} 段` : ''}`,
  },

  mobileComposer: {
    placeholder: '发一句想法，贴个链接…',
    attach: '添加文件',
    send: '发送',
    startDictation: '开始语音听写',
    stopDictation: '停止语音听写',
    connecting: '正在连接麦克风…',
    listening: '我在听，说完再点一下',
  },

  mobileHome: {
    commandCenterLabel: '学习控制台',
    eyebrow: '今天，从这里开始',
    contextStatus: (count: number): string => count > 0
      ? `已接上 ${count} 段上下文`
      : '还没有上下文',
    title: '今天，学懂一件事。',
    record: '录一节课',
    recordHint: '实时听懂',
    addMaterial: '放入资料',
    photo: '拍板书',
    search: '问同学',
    livePromise: '课中看见脉络',
    afterClassPromise: '课后继续练习',
    capabilityLabel: '从输入到结果，一条学习链路',
    capabilityFlow: '课堂脉络',
    capabilityQa: '资料问答',
    capabilityFlashcards: '闪卡',
    capabilityQuiz: '测验',
    capabilityMindmap: '思维导图',
    capabilityFeed: '今日发现',
    intelligenceLabel: '今日发现',
    intelligenceFallback: '从最近的学习里，找到一条值得继续的线索',
    intelligenceAction: '查看',
    recentLabel: '最近收下',
    recentEmpty: '还没有收下的内容',
    openProfile: '打开个人菜单',
    emptyRole: '懂你上下文的 AI 同学',
    emptyEyebrow: '先交给我一段真实学习',
    emptyTitle: '陪你听懂每一节课。',
    emptyBody: '录下学习现场，课中理清脉络，课后继续练会。',
    emptyRecordHint: '边听边形成课堂脉络',
    tryDemo: '试听 90 秒',
    demoPlay: '播放声音',
    demoPause: '暂停',
    demoFinished: '试听结束，可以去看课后练习了',
    demoFinish: '结束试听，看课后',
    demoReviewStatus: '试听课',
    demoFailed: '试听还没加载好，再试一次',
    emptyOutcomeTitle: '回来时，你会得到',
    emptyOutcomeFlow: '课堂脉络',
    emptyOutcomeAnswer: '有根解释',
    emptyOutcomePractice: '课后练习',
    emptyBrowse: '先看看完整工作台',
  },

  reviewTutor: {
    wholeLesson: '整节课',
    wholeLessonTitle: '基于整节课内容对话',
    confusion: '困惑点',
    backToWholeLesson: '返回整节课对话',
  },

  echoShare: {
    title: '分享这条笔记',
    open: '分享',
    generating: '正在做图片…',
    error: '图片没做出来，再试一次',
    close: '关闭',
    imageAlt: '课堂笔记分享图',
    saveImage: '保存图片',
    nativeShare: '分享给同学',
    sharing: '分享中…',
    copyText: '复制文案',
    saved: '图片已保存',
    copied: '文案已复制',
    copyFailed: '没复制上，请手动保存图片',
    saveFallback: '没保存上，请长按图片保存',
    hint: '也可以长按图片保存',
  },

  flashcardsShare: {
    title: 'MeetMind 试听课闪卡',
    open: '分享试听成果',
    sharing: '分享中…',
    copied: '成果文案已复制',
    failed: '没分享出去，请手动复制',
    summaryTitle: '这节试听课已经变成闪卡',
    summaryBody: (count: number): string => `MeetMind 已经把它整理成 ${count} 张可练习的闪卡。`,
  },

  apps: {
    inlineSource: '已放进对话',
    classroomFlowArtifact: {
      sectionTitle: '录课时已经整理好',
      name: '课堂脉络',
      ready: '随录课生成',
      open: '打开复习',
      back: '返回应用矩阵',
      timelineTitle: '这节课怎么走过来',
      keepTitle: '留到课后再看的内容',
      cardSummary: (moments: number, keeps: number): string => `${moments} 个课堂节点 · ${keeps} 个课后保留点`,
      reviewSummary: (moments: number, keeps: number): string => `上课时形成的 ${moments} 个推进节点和 ${keeps} 个保留点都在这里。`,
    },
    placeholder: {
      defaultAppName: '应用内容',
      workingElapsed: (seconds: number): string => `同学正在整理 · ${seconds.toString().padStart(2, '0')}s`,
      emptyTitle: (appName: string): string => `还没有${appName}`,
      emptyBody: (appName: string): string => `回到应用目录开始整理${appName}，完成后会直接出现在这里。`,
      remake: '再做一版',
      back: '返回应用',
      failedTitle: (appName: string): string => `${appName}刚才没做好`,
      failedBody: '网络可能有点慢，原课堂内容没有受到影响。',
      retry: '再试一次',
      tryAnother: '看看其他方式',
    },
    matrix: {
      eyebrow: '基于这节课',
      title: '接下来怎么学',
      subtitle: '先选一个当下最需要的动作。同学会在后台做好，你可以留在这里继续看。',
      recommendedTitle: '现在最适合',
      recommendedHint: '根据这节课的内容和你留下的标记排序，不替你做决定。',
      allTitle: '其他学习方式',
      availableTitle: '可以这样继续',
      previewTitle: '其他内容可以这样学',
      readinessLabel: '学习应用判断',
      assessing: '正在判断这段内容适合怎么学',
      recommendedByContent: '这段内容已经足以支撑这个学习动作。',
      insufficientTitle: '先保留这段原话',
      insufficientBody: '内容还太少。继续记录后，合适的学习方式会自然出现。',
      notLearningTitle: '这段内容不用加工',
      notLearningBody: '它更像普通交流，保留原话就够了。',
      unreliableTitle: '先把原话听清',
      unreliableBody: '当前转录还不稳定，暂时不把它整理成学习结论。',
      executeNotReady: '这段内容还不足以形成可靠的学习应用。',
      executeNotSuitable: '这个学习动作不适合当前内容，换一种方式更可靠。',
      executeNeedsMultipleLessons: '至少选择两节属于同一门课的课堂。',
      noContent: '先录下或放入一段课堂内容。',
      generateFailed: '这次没做好，稍后可以再试一次。',
      generated: (appName: string): string => `${appName}做好了`,
      openResult: '打开',
      timeout: '等得有点久，稍后可以再试一次。',
      timeoutFor: (appName: string): string => `${appName}还没做好，稍后可以再试一次`,
      cancelled: '已取消',
      cancelledFor: (appName: string): string => `已取消${appName}`,
      failedFor: (appName: string): string => `${appName}这次没做好`,
      contextBasis: (segments: number, anchors: number, difficulties: number): string => {
        const parts = [`${segments} 段课堂内容`];
        if (anchors > 0) parts.push(`${anchors} 处标记`);
        if (difficulties > 0) parts.push(`${difficulties} 个难点`);
        return parts.join(' · ');
      },
      summary: (total: number, done: number, running: number, failed: number): string => (
        `${total} 种学习方式 · 已做好 ${done}${running > 0 ? ` · 正在做 ${running}` : ''}${failed > 0 ? ` · 待处理 ${failed}` : ''}`
      ),
      recommendedForConfusion: (count: number): string => `你留下了 ${count} 处标记，先检验能不能讲清楚。`,
      recommendedForDifficulty: (count: number): string => `这节课有 ${count} 个难点，先把关键概念练到能回忆。`,
      recommendedForStructure: '这节课内容较长，先看清主干和分支。',
      recommendedDefault: '先把这节课压成一页，最快建立整体印象。',
      start: '先做一版',
      open: '继续使用',
      openImage: '查看图片',
      progress: '查看进度',
      retry: '再试一次',
      tryAnother: '看看其他方式',
      remake: '再做一版',
      ready: '做好了',
      waiting: '待开始',
      notAvailable: '暂不可用',
      failed: '没做好',
      running: '正在做',
      workingOn: (action: string): string => `${action}，可以先返回继续看这节课`,
      failedWithoutLoss: '这次没做好，原课堂内容没有受到影响。',
      recommended: '适合现在',
      taskTray: '学习内容',
      taskPanelTitle: '正在准备与已经做好的内容',
      taskRunning: (count: number): string => `正在做 ${count}`,
      taskDone: (count: number): string => `已做好 ${count}`,
      taskNeedsAttention: (count: number): string => `待处理 ${count}`,
      collapse: '收起',
      cancel: '取消',
      noTasks: '还没有正在准备的内容。',
      infographicPreview: '信息图预览',
      podcastPreview: '播客试听',
      downloadImage: '保存图片',
      closePreview: '关闭',
      imageDownloaded: '图片已保存',
      imageDownloadFailed: '没保存上，请长按图片保存',
      windowUnavailableTitle: '这个学习方式暂时打不开',
      windowUnavailableBody: '回到这节课，其他学习方式仍然可以继续使用。',
      windowLoading: '正在接回这节课',
      windowEmptyTitle: '先选一节课',
      windowEmptyBody: '学习应用需要基于真实课堂内容，才不会生成没有依据的结论。',
      windowBackToClassroom: '回到课堂',
      windowErrorTitle: '这次没有接上',
      windowErrorBody: '课堂原文仍然保留着，回到学习方式后可以再试一次。',
      windowLoadTimeout: '这节课暂时没有接上，请返回后再试一次。',
      windowLoadFailed: '这节课暂时没有接上',
      courseCheatsheetSection: '跨课准备',
      courseCheatsheetTitle: '考试速查表',
      courseCheatsheetBody: '从课程上下文选择多节课堂、考试范围与资料，做成真正能打印和带进考场的速查表。',
      courseCheatsheetAction: '选择课程范围',
      courseCheatsheetRouteTitle: '考试速查表从多节课开始',
      courseCheatsheetRouteBody: '先选择一门课程和至少两节课堂；MeetMind 会把课堂、课件与考试范围合成一份可编辑、可打印的速查表。',
      mobileTitle: '这节课，接下来怎么学',
      mobileSubtitle: '选一种学习动作，同学会直接基于这节课开始。',
      backToMatrix: '所有学习方式',
      workspaceSubtitle: (action: string, bestFor: string): string => `${action} · ${bestFor}`,
      catalogMeta: {
        cheatsheet: { action: '带进考场', bestFor: '多节课已组成单元，或正在准备允许携带资料的考试', time: '排版约 10–20 分钟' },
        quiz: { action: '检验理解', bestFor: '想做题测一测，马上知道哪里没掌握', time: '作答约 5–8 分钟' },
        flashcards: { action: '记住核心', bestFor: '概念、术语和公式需要反复回忆', time: '练习约 5 分钟' },
        mindmap: { action: '看清结构', bestFor: '内容较多，想分清主干、关系和层次', time: '浏览约 2 分钟' },
        'audio-overview': { action: '换种方式再听', bestFor: '通勤或走路时，想用对话重新理解', time: '收听约 6–10 分钟' },
        infographic: { action: '做成一张图', bestFor: '想分享、展示，或用视觉方式记住', time: '查看约 2 分钟' },
        'teach-back': { action: '讲给同桌听', bestFor: '想确认自己是真懂，而不只是看懂了', time: '讲约 5–10 分钟' },
        explainer: {
          name: '板书精讲',
          headline: '黑板上边写边讲，把这节课讲透',
          description: '像坐在教室前排：粉笔字一个个写出来，圈点勾画跟着讲解走。',
          action: '看板书精讲',
          bestFor: '想真正弄懂这节课的核心概念，而不是只留个印象',
          time: '观看约 5–8 分钟',
        },
      },
    },
    infographic: {
      appName: '课堂信息图',
      preparing: '正在把这节课变成一张图',
      preparingHint: '完成后会直接显示成品。',
      finished: '做好了',
      fit: '看全图',
      full: '看细节',
      save: '保存图片',
      adjust: '调整',
      createTitle: '把这节课变成一张图',
      createHint: '选尺寸和感觉，其他交给同学。',
      adjustTitle: '想换一种呈现？',
      adjustHint: '只改你在意的部分，其余交给同学。',
      orientation: '尺寸',
      style: '视觉感觉',
      custom: '还想强调什么',
      customPlaceholder: '例如：突出 3 个结论，适合手机查看',
      generate: '生成信息图',
      regenerate: '按这个方向重做',
      serviceUnavailable: '图片服务暂时不可用',
      serviceUnavailableBody: '课堂内容和草案已经保留，稍后再试即可。',
      downloaded: '图片已保存',
      downloadFailed: '没保存上，请长按图片保存',
      missingContext: '当前内容还不足以生成可靠的信息图。',
      generateFailed: '这次没有生成成功，课堂内容仍然保留着。',
      readableReady: '先给你一张可读版',
      readableHint: '图片还没做好，课堂重点不用跟着等。',
      copyReadable: '复制要点',
      readableCopied: '要点已复制',
      readableCopyFailed: '没复制上，可以长按选择文字。',
      retryImage: '再试一次图片',
    },
    teachBack: {
      appName: '讲给同桌听',
      targetsTitle: '这节课，挑几点讲出来',
      targetsSubtitle: '能讲出来的，才是真的懂。',
      evidenceLabel: '课堂依据',
      startVoice: '走上讲台',
      voiceHint: '同桌安静听你讲，只在跟不上或你有没讲到的点时开口。',
      textTitle: '把这节课讲给同桌',
      speakPlaceholder: '讲一段，或打字补充……',
      submitSegment: '讲给同桌',
      deskmateListening: '同桌在听',
      finishText: '讲完了',
      evaluating: '同桌正在对照课堂原声核对你讲的……',
      evaluatingStage2: '正在逐条核对你讲的和课堂原声……',
      evaluatingStage3: '就快好了，同桌在写核对结论……',
      evalRateLimited: '刚才操作太频繁了，喝口水，等一小会儿再试。',
      reteachPoint: '就这点再讲一次',
      yourTeachingStats: (chars: number): string => `你讲的约 ${chars} 字都还在，不用重讲。`,
      resultTitle: '讲得怎么样',
      quadrantMastery: '讲透了',
      quadrantStruggle: '挣扎着讲通了',
      quadrantGap: '自己知道卡住了',
      quadrantBlindSpot: '盲区',
      quadrantUncovered: '还没讲到',
      blindSpotHint: '讲的时候很顺，但和课堂内容对不上。',
      backToEvidence: '回到课堂原声',
      retry: '再讲一次',
      backToTargets: '回到目标',
      emptyBody: '这节课的内容还太少，等录得更久一点再来讲。',
      callContextLabel: '讲课中',
      endCall: '讲完了',
      switchToText: '改为打字',
      classroomWaiting: '开始讲吧，我们在听。',
      classroomReconnect: '连接断了，点这里重新进教室',
      evalFailed: '这次没能完成核对，你讲的内容还在，可以再试一次。',
      retryEval: '重新核对',
      textHint: '用嘴讲，同桌听得见；他跟不上时会开口问。',
    },
    mindmap: {
      mobileGestureHint: '拖动查看 · 点 + 放大',
      desktopGestureHint: '滚轮缩放 · 拖拽平移',
    },
    flashcards: {
      appName: '闪卡训练',
      completeTitle: '这一轮完成了',
      roundSummary: (count: number): string => `共回忆 ${count} 张`,
      recallRate: '本轮记住',
      got: '记住了',
      missed: '再来一次',
      gotCount: '记住了',
      missedCount: '还要练',
      reviewMissed: (count: number): string => `只练没记住的 ${count} 张`,
      restart: '重练全部',
      reveal: '想好后翻面',
      answer: '参考答案',
      showHint: '看一点提示',
      recallFirst: '先在心里回答，再翻面看答案',
      keyboardHint: '空格翻面 · 方向键切换',
      previous: '上一张',
      next: '下一张',
      evidenceAt: (time: string): string => `来自课堂 ${time}`,
      returnToEvidenceAt: (time: string): string => `回到课堂 ${time}`,
    },
    quiz: {
      appName: '课堂测验',
      keyboardHint: '方向键切换题目',
      previous: '上一题',
      next: '下一题',
      jumpTo: (index: number): string => `跳到第 ${index} 题`,
      answered: (done: number, total: number): string => `${done} / ${total} 已完成`,
      understood: '答稳了',
      revisit: '再看看',
      subjectivePrompt: '先在心里说出答案，再对照参考。',
      referenceAnswer: '参考答案',
      referenceFallback: '回到原片段核对关键内容。',
      selfRate: '对照后，我：',
      selfCorrect: '答到要点',
      selfWrong: '还没答上',
      correct: '答对了',
      wrong: '再看看',
      correctAnswer: (answer: string): string => `答案：${answer}`,
      revealReference: '对照答案',
      confirmAnswer: '确认答案',
      nextQuestion: '下一题',
      viewResult: '看这一轮',
      completeTitle: '这一轮检验完成',
      completeMeta: (count: number, minutes: string): string => `共 ${count} 题 · 用时 ${minutes} 分钟`,
      recallRate: '本轮答稳',
      solidCount: '答稳了',
      revisitCount: '还要回看',
      missedReview: '需要回看的题',
      reviewMissed: (count: number): string => `只练需要回看的 ${count} 题`,
      restart: '重做全部',
      evidenceAt: (time: string): string => `来自课堂 ${time}`,
      returnToEvidenceAt: (time: string): string => `回到课堂 ${time}`,
    },
    explainer: {
      appName: '板书精讲',
      quotesVerified: (count: number): string => `${count} 处老师原话已核对`,
      quotesDowngraded: (count: number): string => `${count} 处引用未对上原话，已改为转述`,
      play: '播放',
      pause: '暂停',
      replay: '重新播放',
      pageLabel: (current: number, total: number): string => `第 ${current} / ${total} 页`,
      checkpointKnow: '我会了',
      checkpointHint: '给我提示',
      checkpointAnswer: '看解析',
      inkStart: '板演',
      inkClear: '擦掉重写',
      inkDone: '写完了',
      inkGrading: '老师正在批改你的板演…',
      inkDemoTitle: '老师示范：',
      preparing: '老师正在备课…',
      awaitingGesture: '点一下黑板，听老师开讲',
      finishedCaption: '这节课讲完了。可以重新播放，或者点「板演」自己试试。',
      photoEntry: '拍题开讲',
      photoPick: '选一张题目照片',
      photoStageReading: '老师正在看题…',
      photoStageSolving: '老师正在解题…',
      photoStagePreparing: '老师正在备课…',
      photoErrorNotProblem: '这张照片里好像没有题目，换一张试试',
      photoErrorGeneric: '这次没讲成，再试一次',
      photoChange: '换一道题',
    },
    teach: {
      appName: 'AI 家教',
      lessonStart: '老师，开始上课吧',
      askPlaceholder: '随时提问，当前句讲完就答你…',
      thinking: '老师在想…',
      quoteAsk: '引用提问',
      removeQuote: '移除引用',
      voiceSoon: '语音提问即将上线',
      soundOn: '讲课声音：开',
      soundOff: '讲课声音：关',
      history: '课程',
      newLesson: '新开一课',
      topicPromptTitle: '今天想学什么？',
      topicPromptPlaceholder: '比如：黎曼猜想、勾股定理、英语过去完成时…',
      topicPromptStart: '开课',
      emptyChat: '课马上开始。听懂听不懂，都可以随时在下方问。',
      restored: '已恢复到上次讲到的地方，可以继续提问。',
      toolChip: {
        write: '板书',
        circle: '圈注',
        underline: '下划线',
        arrow: '连线',
        mark: '批改',
        image: '插图',
        flip_page: '新一页',
        ask: '提问',
      } as Record<string, string>,
    },
    podcast: {
      appName: '课堂播客',
      emptyBody: '开始整理后，会直接得到一版可以播放的课堂播客。',
      scriptCopied: '脚本已复制',
      copyFailed: '复制失败，请手动选择脚本内容',
      details: '脚本与章节',
      script: '播客脚本',
      copyScript: '复制脚本',
      chapter: (index: number): string => `章节 ${index}`,
      chapterEmpty: '这一章暂时没有摘要。',
      seekChapter: '回到课堂片段',
      audioGenerating: '正在准备音频',
      audioRetry: '音频没做好，点这里再试一次',
      audioGeneratingHint: '完成后这里会直接变成播放条。',
      audioRetryHint: '脚本已经保留，不需要重新来过。',
      audioRetryNoScriptHint: '课堂内容仍然保留，稍后可以直接再试。',
      activityAudioReady: '课堂播客已经可以播放，并保留了脚本与章节。',
      activityScriptReady: '音频还没做好，播客脚本与章节已经保留。',
      generating: '正在准备',
      retry: '再试一次',
    },
    cheatsheet: {
      appName: '考试速查表',
      emptyBody: '当前内容还不足以整理成可靠的速查表。继续记录后再回来看看。',
      focus: '重点',
      focusCount: (count: number): string => `重点 ${count}`,
      focusTitle: '课堂、大纲或真题明确强调的内容',
      hideItem: '暂时移除这条',
      expand: '展开',
      collapse: '收起，不放进打印页',
      removedCount: (count: number): string => `已移除 ${count} 条`,
      removedTitle: (count: number): string => `${count} 条已移除`,
      collapsedCount: (count: number): string => `已收起 · ${count} 条`,
      sectionCount: (sections: number, items: number): string => `${sections} 区 · ${items} 条`,
      itemCount: (count: number): string => `${count} 条`,
      sourcesLabel: '来源',
      copied: '已复制',
      pageTotal: (count: number): string => `共 ${count} 页`,
      copyMarkdown: '复制文字',
      print: '打印 / 导出 PDF',
      copyTitle: '复制文字，便于粘贴到笔记或发给同学',
      printTitle: '按 A4 纵向三栏打印或导出 PDF',
      allRemoved: '内容已全部移除，可以恢复后继续整理。',
      pageNumber: (current: number, total: number): string => `${current} / ${total}`,
      page: '页面',
      mono: '黑白',
      color: '彩色',
      editItem: '编辑这条',
      editShort: '编辑',
      hideShort: '不打印',
      itemActions: '调整这条内容',
      mobileCopy: '复制',
      mobilePrint: '打印 / PDF',
      editTerm: '术语',
      editBody: '解释',
      editFormula: '公式（可留空）',
      cancelEdit: '取消',
      saveEdit: '保存',
      syllabusSource: '考试大纲',
      pastPaperSource: (index: number): string => `真题 ${index}`,
    },
  },

  /**
   * 信息流（M15：替换笔记总结）
   * 基于个人上下文的 LLM 驱动信息流——同一节课不同人看到不同的内容。
   */
  feed: {
    /** tab 标签（单课复习态遗留，跨课程信息流改走侧栏抽屉） */
    tabLabel: '信息流',
    /** 侧栏「收集 → 相关信息」子导航文案 */
    relatedInfoLabel: '今日情报',
    /** 抽屉标题——替换原「笔记总结」 */
    drawerTitle: '今日情报',
    drawerSubtitle: '一半照见你正在关心的事，一半把真实的书、论文和新观点带进来。',
    todayBrief: '看见自己',
    internalDiscoveries: '看见自己',
    internalDiscoveriesHint: '从你的收藏、笔记和目标里，找到正在形成的方向。',
    externalDiscoveries: '向外看看',
    externalDiscoveriesHint: '真实来源，可直接打开；既有顺着目标深入，也有不同视角。',
    useful: '有用',
    notRelevant: '不相关',
    feedbackUseful: '已记下，以后多找这类内容',
    feedbackDismissed: '已减少这类推荐',
    refresh: '更新',
    addContext: '补一条线索',
    refreshing: '正在寻找与你有关的新内容',
    notGeneratedYet: '等待第一次发现',
    updatedJustNow: '刚刚更新',
    updatedMinutesAgo: (minutes: number): string => `${minutes} 分钟前更新`,
    updatedAt: (time: string): string => `今日 ${time} 更新`,
    refreshFailedKeepingPrevious: '这次没更新成，先保留上一版。',
    contextBasis: (captures: number, goals: number): string => (
      goals > 0 ? `基于 ${captures} 条收藏 · ${goals} 个当前目标` : `基于 ${captures} 条收藏`
    ),
    sourceCount: (count: number): string => `来自 ${count} 条收藏`,
    goalAlignment: (goal: string): string => `对齐目标「${goal}」`,
    /** 生成中（跨课程） */
    loading: '同学正在查找真实的书、论文和外部资料…',
    /** 空状态（没有收集内容） */
    empty: '还没有收集内容。先去收一节课或一篇文章，同学会自动整理方向。',
    /** 跨课程空态 */
    crossCourseEmptyTitle: '先留下几条你真正关心的内容。',
    crossCourseEmptyBody: '这里会先看见你正在形成的方向，再从外部找到真实可读的书、论文和不同观点。',
    /** 生成失败 */
    error: '没整理出来，再试一次',
    /** 重试按钮 */
    retry: '重新整理',
    /** 条目类型标签 */
    typeSummary: '你最近在意的',
    typeProbeNear: '同主题',
    typeProbeLateral: '相关方向',
    typeProbeBridge: '跨界',
    typeConfusionLink: '你标记的困惑',
    typeWebRecommend: '外部发现',
    typeBiliRecommend: '同学帮你找的',
    typeEcho: '同桌沉淀',
    /** echo 卡分享按钮 */
    shareEcho: '分享',
    /** 动作按钮 */
    actionJumpTimestamp: '跳回去听',
    actionMakeFlashcard: '做成闪卡',
    actionAskTutor: '让同学解释',
    actionReviewPrev: '看上节课',
    actionOpenCapture: '看这条收集',
    actionOpenExternal: '打开原文',
    actionOpenBilibili: '在 B站看',
    /** whyForYou 前缀 */
    whyPrefix: '为什么与你有关',
    differentPerspectivePrefix: '为什么值得换个角度',
    kindWeb: '文章',
    kindPaper: '论文',
    kindBook: '书籍',
    kindReport: '研究报告',
    perspectiveDeepen: '顺着目标深入',
    perspectiveAdjacent: '相邻视角',
    perspectiveCounterpoint: '不同视角',
    unknownAuthor: '作者未标注',
  },

  /**
   * 「聊聊你想要的」—— 用户和 AI 教练对话梳理目标的入口。
   * 是 v3.0 信息流哲学落地的第一个产品入口（替代旧硬编码 LearnerOnboarding 表单）。
   * 设置页常驻 + 首次进入 app 自动弹出。
   */
  intent: {
    /** 主标题（设置页 caption / 首次进入 header） */
    title: '聊聊你想要的',
    /** 副标 */
    subtitle: '不用写好——说就行',
    /** 设置页 description */
    description: '和教练聊一聊，把脑子里的事一起捋清楚',
    /** 设置页：还没聊过的提示 */
    emptyHint: '还没聊过。你最近想做的事 / 想去的方向 / 还在纠结的选择，都可以慢慢说。',
    /** 设置页：开始按钮 */
    actionStart: '和教练聊一聊',
    /** 设置页：再聊一次按钮 */
    actionResume: '和教练再聊一会',
    /**
     * 首次会面：固定开场选择题（成熟产品 onboarding 模式——先拿稳定属性，再拿时间尺度）。
     * 两题稳定属性（身份 → 阶段，点选即进下一题，零 LLM 往返），一题目标时间尺度；
     * 三题答完合成第一条用户消息发给 AI，稳定属性由 AI 沉淀进「我了解到的你」。
     */
    openingStep1Question: '你现在是——',
    openingStep1Options: ['在校学生', '工作中', '自由职业 / gap 中', '还在找方向'] as string[],
    openingStep2StudentQuestion: '读到哪个阶段了？',
    openingStep2StudentOptions: ['中学', '大学', '研究生', '备考中（考研 / 考证 / 考公）'] as string[],
    openingStep2WorkQuestion: '工作多久了？',
    openingStep2WorkOptions: ['还在试用期', '1-3 年', '3 年以上'] as string[],
    openingStep3Question: '最想让 Octo 帮你盯住哪类事？',
    openingStep3Options: [
      '眼前的考试或 DDL',
      '这个学期 / 季度的进步',
      '长期的方向和本事',
    ] as string[],
    /** 顶部步骤条：说说 → 捋一捋 → 记下了 */
    stepChat: '说说',
    stepShape: '捋一捋',
    stepSaved: '记下了',
    /** 完成态 */
    doneTitle: '记下了',
    doneHint: '它已经进入你的上下文，之后的复习和首页都会围着它转。',
    donePrimary: '好了，去主页看看',
    doneSecondary: '再记一件',
    /** 请求失败 / 卡死看门狗触发时的错误条 */
    errorBanner: '刚刚断了一下，这条没收到回复。',
    errorRetry: '重试',
    errorDismiss: '先不管',
    /** AI 没给选项时的兜底快答（保证永远能点选推进） */
    fallbackContinue: '继续说',
    fallbackWrapUp: '帮我捋出来记着',
    /** IntentDialog header：右上角切换通话 */
    switchToCall: '打电话聊',
    /** 通话视图：切回文字 */
    switchToText: '文字',
    /** 通话视图：标题 */
    callTitle: '在听你说',
    /** 通话视图：底部状态行（基于 useOmniRealtimeCall.status） */
    callStatusListening: '我在听你说…',
    callStatusThinking: '我想一下…',
    callStatusResponding: '我在说…',
    callStatusMuted: '已静音 · 我还在',
    callStatusConnected: '直接说就好',
    callStatusConnecting: '正在接通…',
    callStatusAuthorizing: '点下面按钮开始',
    callStatusError: '没接通，点重连',
    callStatusPreparing: '准备中…',
    /** 输入条：占位符 */
    inputPlaceholder: '说说你最近想做的事',
    inputPlaceholderBusy: '同学正在听…',
    /** 首次进入：跳过文案 */
    firstTimeSkip: '先不聊，下次再说',
    /** 开场提示——已有 N 个目标时 */
    greetingWithGoals: (count: number): string =>
      `欢迎回来。你之前留下了 ${count} 件想做的事——是想聊聊新的，还是更新一下旧的？`,
    /** 开场提示——首次 */
    greetingFirstTime:
      '不急。你现在脑子里有什么想做、想去、想搞清楚的事？哪怕还没完全想明白，也可以慢慢说。',
    /** 卡片：标题（"我听到的是"） */
    summaryEyebrow: '我听到的是',
    /** 卡片：先放放 */
    summaryDismiss: '先放放',
    /** 卡片：就是这样（保存） */
    summaryAccept: '就是这样',
    /** 卡片：保存中 */
    summarySaving: '记着…',
    /** 卡片：已保存 */
    summarySaved: '已记下了',
    /** 目标时间尺度角标（horizon） */
    horizonNear: '短期 · 有明确节点',
    horizonTerm: '中期 · 学期 / 季度',
    horizonLong: '长期 · 方向',
  },

  realtime: {
    defaultTitle: '语音同桌',
    defaultContext: '整节课',
    disabled: '先收一条课堂内容',
    reconnect: '没接通，点重连',
    connecting: '正在接通…',
    authorizing: '点下面按钮开始',
    muted: '已静音 · 我还在',
    listening: '我在听你说…',
    thinking: '我想一下…',
    responding: '我在说…',
    connected: '已接通 · 直接说',
    preparing: '准备中…',
    transcriptTitle: '本轮对话文字',
    assistantLabel: '同学',
    userLabel: '你',
    emptyTranscript: '还没有对话内容',
    showText: '查看文字',
    reconnectAction: '重连',
    collapse: '收起',
    dialing: '接通中',
    start: '开始',
    unmute: '开麦',
    mute: '静音',
    endCall: '结束通话',
  },

  mobileJourney: {
    playAudio: '播放原声',
    pauseAudio: '暂停原声',
    finishLesson: '结束这节课',
    photoCapturedAt: (timestamp: string): string => `已拍下板书 · ${timestamp}`,
    collapseClassmate: '收起课堂同桌',
    processingEyebrow: '正在整理',
    processingTitleLead: '把这节课',
    processingTitleAccent: '听懂',
    waitingTranscript: '等待转录完成…',
    readingTranscript: '正在读转录原文…',
    buildingNotes: '正在生成分段笔记…',
    processingDone: '整理完成',
    noSpeechStatus: '没有听到可整理的内容',
    processingEstimate: '约 1 分钟',
    waiting: '等待中…',
    done: '完成',
    leaveWhileProcessing: '先回首页',
    openNotes: '笔记整理好了，去看看 →',
    understood: '已理解',
    originalPreserved: '原声已保留',
    restoringTranscript: '正在恢复这节课的转录内容…',
    noSpeechTitle: '这段录音里没有识别到语音',
    noSpeechBody: '可能是录音太短或声音太小。原声已保留，可以返回首页稍后再看。',
    backHome: '返回首页',
  },

  help: {
    classroomRecordingAnswer: '录课中 MeetMind 会实时展示：\n\n- 实时原话：老师说的内容会跟着出现\n- 课堂脉络：告诉你现在讲到哪里、刚才如何推进、什么值得课后回来\n- 同学：有问题随时可以问，它会带着刚才的课堂上下文回答\n\n这些都会自动完成。思维导图、闪卡和测验会在课后应用中生成，不会在上课时抢走注意力。',
  },

  /**
   * v3.0 SharedAgent —— 分享 Agent 的落地页 / 分享卡 / 创建对话框文案
   * 见 roadmap/v3.0-virality-agent.md。
   */
  share: {
    landing: {
      /** 落地页右下角极淡的访问计数 */
      viewCount: (count: number): string => `已被打开 ${count} 次`,
      /** 没登录访问者点"领取到我的工作台"时的引导 */
      claimNeedsLogin: '领取需要先登录，登录后这份内容就在你的工作台里了',
      claimGo: '去登录',
      /** 已登录领取按钮 */
      claimAction: '领取到我的工作台',
      claiming: '正在领取…',
      claimDone: '已领取，去工作台看看',
      claimRedirecting: '正在打开你的工作台…',
      claimAlready: '你之前已经领过这一份',
      claimSub: '领取后可以在自己的工作台里继续学',
      /** 领取接口异常的兜底文案 */
      claimFailed: '领取失败',
      /** 也分享给别人 */
      reshareAction: '复制链接',
      reshareFailed: '复制失败，请手动复制地址栏',
      /** 分享态对话输入占位符 */
      chatPlaceholder: '问问这节课…',
      /** 分享态对话：等待回答时的输入条占位 */
      chatBusyPlaceholder: '同学在想…',
      /** 分享态对话：空态卡后半句（接在 sharedBy 之后） */
      chatEmptyHint: '可以问我任何关于这节课的事。',
      /** 分享态对话顶栏状态 */
      chatStatusBusy: '在听',
      chatStatusReady: '就绪',
      /** 已撤销 / 已过期 */
      notFoundTitle: '这条分享暂时不可用',
      notFoundBody: '可能已被原作者撤回，或者链接打错了。',
      /** 404 态回首页链接 */
      backHome: '回 MeetMind 首页',
      /** 头部副标题：基于分享者昵称 */
      sharedBy: (nickname: string): string => `${nickname} 听完了这节课，留了一份给你`,
      /** 没有昵称兜底 */
      sharedByAnon: '一个同学听完了这节课，留了一份给你',
      /** 分享者昵称兜底（各处展示用） */
      sharerAnon: '一位同学',
      /** Octo 主图 alt */
      octoAlt: (nickname: string): string => `${nickname} 的学习同桌`,
      /** 凌晨加载态（Octo sleeping） */
      loadingSleeping: '夜深了 · 同学先打个盹',
      /** 转录摘要标题 */
      digestTitle: '这节课讲了什么',
      digestEmpty: '没附转录摘要，可以直接问同学这节课的事。',
      /** 转录摘要折叠提示：还有 N 段未展示 */
      digestMore: (count: number): string => `另 ${count} 段在同学的记忆里。`,
      /** 产物预览块标题（按 artifactKind 切换） */
      artifactTitle: (kind: string): string => {
        const map: Record<string, string> = {
          cheatsheet: '考前速查表',
          mindmap: '思维导图',
          quiz: '课堂测验',
          flashcards: '课堂闪卡',
          infographic: '课堂信息图',
          'audio-overview': '课堂播客',
          notes: '同学版笔记',
          'chat-only': '可以直接聊',
        };
        return map[kind] ?? '一份分享';
      },
    },
    creator: {
      doneCopy: '复制链接',
      doneCopied: '链接已复制',
      doneLinkCreated: '分享链接已生成',
      doneCopyFailed: '复制失败，请手动复制链接',
      doneCopying: '复制中...',
      fallbackTitle: '分享链接已生成',
      fallbackBody: '浏览器没有允许自动复制，可以直接复制下面的链接。',
      loginRequired: '先登录再分享',
      loginAction: '登录后继续',
      createFailed: '创建分享失败',
      currentAction: '分享',
      currentPreparing: '正在生成链接',
    },
  },

  adminAi: {
    managementView: '管理视图',
    managementViewEnabled: '已开启',
    managementViewDisabled: '未开启',
    managementViewHint: '开启后，AI 功能旁会显示本次实际输入与运行配置。普通用户不会看到。',
    inspector: '查看本次 AI',
    inspectorTitle: '查看这次回答接入了什么',
    inspectorPanelTitle: '本次 AI 输入',
    closeInspector: '关闭本次 AI 输入',
    inspecting: '正在重建本次输入…',
    inspectorFailed: '暂时无法读取这次 AI 输入，请进入控制中心重试。',
    requestModel: '请求模型',
    noContextReceived: '这次没有接入额外上下文',
    inspectorPrivacy: '输入只在当前浏览器用于这次检查，不写入运行日志。最终模型可能因服务异常自动切换备用通道。',
    tuneThisRun: '用这次输入去调整',
    settingsCaption: '管理员工具',
    openControlCenter: '打开 AI 控制中心',
    settingsDescription: '统一查看提示词、上下文拼接、模型路由和线上版本',
    title: 'AI 控制中心',
    subtitle: '看清每条 AI 链路的上下文、提示词与模型，并安全地发布调整。',
    back: '返回 MeetMind',
    accessDenied: '这里仅对管理员开放',
    accessDeniedBody: '请先使用管理员账号登录。',
    loading: '正在读取 AI 链路…',
    loadFailed: 'AI 配置读取失败，请稍后重试。',
    surfaces: 'AI 链路',
    online: '线上',
    baseline: '代码默认',
    draft: '草稿',
    version: (version: number): string => `v${version}`,
    noPublishedVersion: '尚未发布调整',
    entryPoints: '出现位置',
    contextMap: '输入上下文',
    sensitive: '含个人信息',
    editTitle: '调整这条链路',
    editBody: '保留代码内的基础提示词，只追加你希望改变的行为。',
    enabled: '启用这版调整',
    enabledHint: '关闭后仍可保存草稿，但发布不会改变线上行为。',
    model: '运行模型',
    modelAuto: '沿用产品默认',
    instructions: '追加指令',
    instructionsPlaceholder: '例如：回答概念问题时，先用一个贴近课堂的小例子，再给定义。',
    note: '版本备注',
    notePlaceholder: '这次为什么调整',
    saveDraft: '保存草稿',
    saving: '保存中…',
    publish: '发布到线上',
    publishing: '发布中…',
    publishConfirm: '确认把这版配置发布给所有用户？发布后仍可从版本记录回滚。',
    saved: '草稿已保存',
    published: '已发布，新请求会使用这版配置',
    rolledBack: '已回滚并生成一个新的线上版本',
    actionFailed: '操作失败，请检查内容后重试。',
    previewTitle: '用一次真实输入预演',
    previewBody: '可以直接编辑这次送给模型的上下文样例，不会触发真实回答，也不会影响线上。',
    liveContext: '来自刚才的产品现场',
    sampleContext: '产品样例',
    contextJson: '上下文 JSON',
    optionsJson: '运行选项',
    invalidJson: '上下文不是有效的 JSON。',
    preview: '生成最终输入',
    previewing: '正在拼接…',
    previewEmpty: '生成预览后，这里会显示模型最终收到的系统输入。',
    finalInput: '最终系统输入',
    promptVersion: '基础提示词版本',
    characterCount: (count: number): string => `${count.toLocaleString('zh-CN')} 字符`,
    contextReceived: '实际接入字段',
    lockedContract: '不可覆盖的产品合同',
    lockedHint: '隐私、引用与场景边界始终放在管理员指令之后。',
    compareTitle: '回答对比',
    compareBody: '用同一份上下文和问题，对比当前线上配置与正在编辑的配置。试跑不会写入用户对话。',
    trialQuery: '测试问题',
    trialQueryPlaceholder: '输入一条真实用户会问的问题',
    trialQueryRequired: '先输入一条测试问题。',
    runCompare: '试跑两版回答',
    comparing: '两版同时生成中…',
    compareFailed: '回答试跑失败，请检查模型配置后重试。',
    currentOnline: '当前线上',
    currentEdit: '正在编辑',
    compareEmpty: '试跑后在这里直接比较用户会看到的回答。',
    duration: (durationMs: number): string => `${(durationMs / 1000).toFixed(1)} 秒`,
    history: '版本记录',
    rollback: '回滚到这版',
    rollbackConfirm: (version: number): string => `确认回滚到 v${version}？系统会生成一个新的线上版本。`,
    emptyHistory: '还没有版本记录。',
  },

  /** 管理员成本视图（积分影子计量 Phase 1） */
  adminCosts: {
    title: '模型成本',
    body: '影子计量期只统计真实成本，不会向用户扣减。',
    range7: '近 7 天',
    range30: '近 30 天',
    colFeature: '功能',
    colModel: '模型',
    colRequests: '请求数',
    colTokens: 'Tokens',
    colCost: '成本',
    total: '合计',
    dailyTitle: '每日趋势',
    empty: '这个时间范围还没有计量数据。',
    loadFailed: '成本数据加载失败。',
    cost: (milliYuan: number): string => `¥${(milliYuan / 1000).toFixed(3)}`,
    tokens: (count: number): string => count.toLocaleString('zh-CN'),
  },

  /** 积分（Phase 2）：余额展示、扣费拦截提示、免费录课额度 */
  points: {
    unit: '积分',
    chipLabel: (balance: number): string => `${balance} 积分`,
    balanceCaption: '当前余额',
    freeMinutesRemaining: (minutes: number): string => `本月免费录课还能用 ${minutes} 分钟`,
    freeMinutesUsedUp: '本月免费录课时长已用完',
    recentRecords: '最近记录',
    recordsEmpty: '还没有积分记录。',
    /** 设置页流水默认只展示最近几条，其余收进展开器——否则每次用 AI 都会把设置页拉长 */
    recordsShowAll: (count: number): string => `查看全部 ${count} 条记录`,
    recordsCollapse: '收起记录',
    loadFailed: '积分信息暂时没接上，稍后再看。',
    /** 402 insufficient_points：余额不足 + 当前余额 + 下月发放说明 */
    blockedInsufficient: (balance: number): string =>
      `积分不够了，现在还剩 ${balance}。每月初会发新的，到时候再来。`,
    blockedInsufficientUnknown: '积分不够了。每月初会发新的，到时候再来。',
    /** 402 monthly_cost_cap：本月成本到顶，下月自动恢复 */
    blockedMonthlyCap: '这个月的 AI 用到上限了，先歇一歇，下个月会自动恢复。',
    /** 402 guest_daily_cap：未登录日试用到顶，引导登录 */
    blockedGuestDailyCap: '今天的试用到这里了。登录后就能继续，每月还有固定额度。',
    /** ── Paywall 付费拦截页（高意向时刻截断：402 / 录课额度用尽） ── */
    paywallTitle: '充点积分，接着学',
    paywallInsufficient: (balance: number, required: number): string =>
      `这次需要 ${required} 积分，你还差 ${Math.max(1, required - balance)}。`,
    paywallInsufficientUnknown: '积分不够这次用了，充一点就好。',
    paywallAsrQuota: '本月免费录课时长用完了，充积分可以按分钟继续录。',
    paywallPackCaption: (points: number): string => `${points} 积分`,
    paywallPackLabel: { starter: '体验包', standard: '标准包', scholar: '学霸包' } as Record<string, string>,
    paywallPackRecommend: '最多人选',
    paywallPayCta: (fen: number): string => `微信支付 ¥${(fen / 100).toFixed(2).replace(/\.00$/, '')}`,
    paywallPayingTitle: '微信扫码完成支付',
    paywallPayingHint: '支付成功后积分自动到账，不用刷新页面。',
    paywallPayExpired: '二维码过期了，重新生成一张。',
    paywallSuccessTitle: '积分到账了',
    paywallSuccessBody: (points: number): string => `+${points} 积分，继续吧。`,
    paywallUnavailable: '在线支付即将开通。着急的话，先在公众号里找我们。',
    paywallDismiss: '再想想',
    /** 微信充值到账的客服消息（recharge-order-service 推送） */
    rechargePaidText: (points: number, balanceAfter: number | null): string =>
      `积分到账：+${points} 积分${typeof balanceAfter === 'number' ? `，当前余额 ${balanceAfter}` : ''}。`,
    /** 录课前预检：免费分钟用完，轻提示不阻断 */
    asrQuotaExhausted: (pricePerMinute: number): string =>
      `本月免费录课时长已用完，继续录会按每分钟 ${pricePerMinute} 积分计。`,
    settingsCaption: '积分',
    settingsDescription: '每月发放的额度、免费录课时长和使用记录',
    monthCostLabel: '本月 AI 成本',
    monthCostValue: (milliYuan: number): string => `¥${(milliYuan / 1000).toFixed(2)}`,
    monthCostCap: (milliYuan: number): string => `上限 ¥${(milliYuan / 1000).toFixed(2)}`,
    freeMinutesLabel: '免费录课时长',
    minutesValue: (minutes: number): string => `${minutes} 分钟`,
    deltaLabel: (delta: number): string => (delta > 0 ? `+${delta}` : `${delta}`),
    /** 流水 reason 枚举 → 人类可读文案 */
    reasonLabels: {
      welcome: '新同学见面礼',
      monthly: '每月发放',
      tutor: 'AI 同桌',
      apps: '学习应用',
      asr: '录课转写',
      'asr:import': '播客视频导入转写',
      'admin-adjust': '管理员调整',
    } as const,
    reasonFallback: '其他',
  },

  /** 订阅会员（Free / Pro / Max）：档位名、权益文案、到账通知 */
  membership: {
    tierName: { free: '免费版', pro: 'Pro', max: 'Max' } as Record<string, string>,
    /** 会员档订单支付到账的客服消息（recharge-order-service 推送） */
    paidText: (tierLabel: string, expiresOn: string): string =>
      `${tierLabel} 已开通，有效期至 ${expiresOn}。录课额度与每月积分已按新档位生效。`,
    /** 402 membership_required：免费档触发会员专属能力 */
    blockedMembershipRequired: (tierLabel: string): string =>
      `这个功能是 ${tierLabel} 会员专属的，开通后就能用。`,
    settingsCaption: '会员',
    expiresOn: (date: string): string => `有效期至 ${date}`,
    renewCta: '续费',
    upgradeCta: '升级',
    freeTierCta: '开通会员',
    /** 一级页面直达入口（桌面侧栏底部 / 积分面板）的副标题——付费不藏在设置里。
        必须够短：168px 侧栏里放得下，宁可少写也不许截断出省略号 */
    upgradeEntryHint: '解锁深度模式',
    /** 一级页面用户菜单里的会员入口：按当前档位给动作 */
    menuCta: { free: '开通会员', pro: '升级会员', max: '续费会员' } as Record<string, string>,
    /** ── Paywall 会员 Tab ── */
    paywallTabMembership: '会员',
    paywallTabPoints: '充积分',
    paywallTitle: '开通会员，放开用',
    /** 主动打开（设置页）时的中性地推文案 */
    paywallMembershipPitch: '更长的录课额度、每月更多积分，还有会员专属能力。',
    paywallPointsPitch: '积分可以录课、向同学提问、生成学习产物。',
    planPriceMonth: (fen: number): string =>
      `¥${(fen / 100).toFixed(2).replace(/\.00$/, '')}/月`,
    planCta: (tierLabel: string, fen: number): string =>
      `开通 ${tierLabel} · ¥${(fen / 100).toFixed(2).replace(/\.00$/, '')}/月`,
    benefitFreeMinutes: (minutes: number): string => `每月 ${minutes} 分钟免费录课`,
    benefitMonthlyGrant: (points: number): string => `每月发 ${points} 积分`,
    benefitDeep: '解锁深度模式',
    benefitDiscount: '学习应用 8 折',
    benefitModel: '优先更快的模型',
    paywallSuccessTitle: (tierLabel: string): string => `${tierLabel} 已开通`,
    paywallSuccessBody: '录课额度和每月积分已按新档位生效。',
  },

  /**
   * "被禁用"的词表——供测试脚本 grep 校验，确保面向用户的字符串不退化。
   */
  /** 设置页（/settings）——2026-08 重设计时从 page.tsx 内联字符串收口至此 */
  settings: {
    title: '设置',
    backAria: '返回',
    toastSaved: '已保存',
    toastSaveFailed: '保存失败',
    toastProfileSaved: '资料已更新',
    toastProfileFailed: '资料保存失败',
    toastLoggedOut: '已退出登录',
    toastLearnerSaved: '学习档案已更新',
    roles: {
      student: '学生',
      admin: '管理员',
    } as Record<string, string>,
    nav: {
      account: '账户',
      about: '关于你',
      prefs: '学习偏好',
      points: '积分',
      import: '导入',
      more: '更多',
    },
    account: {
      caption: '账户',
      descriptionAuthed: '修改你的展示信息和登录方式',
      descriptionGuest: '登录后可同步学习数据',
      nickname: '昵称',
      email: '邮箱',
      phone: '手机',
      unset: '未设置',
      noContact: '尚未填写联系方式',
      saveProfile: '保存资料',
      savingProfile: '保存中…',
      changePassword: '修改密码',
      logout: '退出登录',
      statusLabel: '状态',
      statusGuest: '未登录',
      login: '登录',
      register: '注册',
      guestBody: '登录后，你的课堂、笔记和学习数据会安全地同步到云端，换设备也不丢。',
    },
    about: {
      caption: '关于你',
      description: '你是谁、想去哪——AI 接着这个陪你学',
      profileCardLabel: '学习档案',
      coachCardLabel: '教练画像',
      identityLabel: '身份',
      gradeLabel: '年级',
      majorLabel: '专业',
      directionLabel: '方向',
      industryLabel: '行业',
      goalLabel: '目标',
      alsoLearningLabel: '也在学',
      notSet: '未设置',
      editProfile: '重新填写学习档案',
      fillProfile: '填写学习档案',
      emptyProfile: '告诉同学你的身份背景，让 AI 回答更贴你。',
      coachBioTitle: '教练记下的你',
      coachGoalsTitle: '你想要的',
      coachUpdatedAt: (date: string): string => `上次更新 · ${date}`,
      chatAgain: '和教练再聊聊',
      chatStart: '和教练聊一聊',
      clearBio: '清除画像',
      clearBioConfirm: '确定要清除画像吗？以后回访时会重新认识你。',
      emptyCoach: '还没和教练聊过。你最近想做的事 / 想去的方向 / 还在纠结的选择，都可以慢慢说。',
    },
    prefs: {
      caption: '学习偏好',
      description: '录课、复习和同桌回答的默认行为',
      modelLabel: '回答方式',
      modelAuto: '自动选择',
      modelAutoWithDefault: (name: string): string => `自动选择（${name}）`,
      modelAutoRecommended: '自动选择（推荐）',
      modelRecommendedSuffix: '（推荐）',
      timestampsLabel: '回答里附时间戳',
      timestampsHint: 'AI 引用课堂内容时附 [MM:SS] 标签，点击跳回原片段',
      thinkingLabel: '展示思考过程',
      thinkingHint: '开启后 AI 先展示推理过程再给最终答案；关闭由 AI 自己判断',
      autoSaveLabel: '自动保存',
      autoSaveHint: '录音结束后自动保存到云端',
      classCheckLabel: '随堂检验',
      classCheckHint: '播放视频或音频时 AI 会在合适的节点自动暂停并出题',
    },
    import: {
      caption: '导入',
      description: '从 B 站等平台导入课程时需要的凭证',
      cookieLabel: 'B站 Cookie',
      cookiePlaceholder: '粘贴 SESSDATA、bili_jct、DedeUserID',
      cookieNote: '仅保存在当前浏览器',
      clearCookie: '清除 Cookie',
      helpToggle: '如何获取导入凭证',
      helpSteps: [
        '登录 bilibili.com',
        '按 F12 打开开发者工具',
        '切到「应用 / Application」',
        '找到 Cookie → https://www.bilibili.com',
        '复制 SESSDATA、bili_jct、DedeUserID 并用分号拼接',
      ],
    },
    more: {
      caption: '更多',
      help: '帮助中心',
      feedback: '意见反馈',
    },
    footerVersion: (version: string): string => `MeetMind · 版本 ${version}`,
  },

  // 「请一个分身」线（分身架 / 请分身 / 分身对话 / 账本式进度）
  // 铁律：skill 内容永不出现在用户面；蒸馏过程只以"账本式进展"可见。
  fenshen: {
    entryLabel: '请一个分身',
    entryBody: '把孔子，或你信任的老师，请进你的课堂。',
    entrySectionTitle: '请一位听过这节课的老师',
    shelfTitle: '分身架',
    shelfEmpty: '架上还空着。请一位听过你课的老师，慢慢聊。',
    invite: '请一个分身',
    back: '返回分身架',
    close: '关闭',
    statusLearning: '学习中',
    statusReady: '就绪',
    statusFailed: '没成',
    progressLedger: (count: number): string => `分身在学习 · ${count} 条进展`,
    sourceLabel: (sourceType: 'hall' | 'bilibili' | 'upload'): string =>
      sourceType === 'hall' ? '名人堂' : sourceType === 'bilibili' ? 'B 站课程' : '上传录音',
    onboardTitle: '请一个分身',
    onboardBody: '分身在后台读完语料、备好课，再来和你聊这节课。',
    tabHall: '名人堂',
    tabBilibili: '贴 B 站链接',
    tabUpload: '上传录音',
    hallConfucius: '孔子',
    nameLabel: '称呼',
    namePlaceholder: '怎么称呼这位老师',
    bilibiliLabel: 'B 站链接',
    bilibiliPlaceholder: 'https://www.bilibili.com/video/…',
    uploadLabel: '录音文件',
    uploadPick: '选择录音',
    uploadMissing: '先选一个录音文件。',
    submit: '开始邀请',
    submitting: '正在邀请…',
    createFailed: '这次没请成，稍后再试一次。',
    chatEmptyReady: (name: string): string => `${name}已经就位。问问他这节课里你没跟上的地方。`,
    chatEmptyLearning: (name: string): string => `${name}正在备课。可以先看看他读到了什么。`,
    chatPlaceholder: (name: string): string => `和${name}聊聊…`,
    chatPlaceholderLearning: '分身还在备课，就绪后再聊',
    listenHint: '先试听一段，听听他讲得像不像。',
    listenSuggestion: '让他把这节课最难的地方再讲一遍',
    feedbackPrompt: '听起来像他吗？',
    feedbackLike: '像他',
    feedbackUnlike: '不像他',
    feedbackUnlikeNotePlaceholder: '哪里不像？（可选）',
    feedbackUnlikeSubmit: '请分身再学一轮',
    feedbackThanks: '记下了。',
    feedbackRelearning: '好，分身带着你的意见再去学一轮。',
    sendFailed: '没发出去，稍后再试一次。',
    feedbackFailed: '反馈没记上，稍后再试一次。',
    interrupt: '打住',
    speaking: '分身正在说…',
  },

  // copy-in 的 AI Elements 原语用到的用户面文案（src/components/ai-elements/）
  aiElements: {
    toolStatus: {
      pending: '排队中',
      running: '进行中',
      awaitingApproval: '待确认',
      responded: '已回应',
      completed: '完成',
      error: '出错',
      denied: '已拒绝',
    },
    toolInput: '参数',
    toolResult: '结果',
    toolError: '错误',
    backToLatest: '回到最新',
  },

  bannedWords: ['回声卡', '酿', '预知气泡', '工坊', '研判', '引擎'] as const,
};

export type Copy = typeof COPY;
