/**
 * copy-settings — 设置页的用户面文案
 *
 * 从 copy.ts 拆出来的唯一理由是体积：这一块只有 设置页 用到，却随 COPY 单体进 /app 首屏 JS（≈2.0 KB gzip）。
 * 口吻审查仍是同一个入口：改文案先看 copy.ts，设置页看这里。用法：`import { SETTINGS_COPY } from "@/lib/ui/copy-settings"`。
 */

export const SETTINGS_COPY = {
    title: '设置',
    backAria: '返回',
    toastSaved: '已保存',
    toastSaveFailed: '保存失败',
    toastProfileSaved: '资料已更新',
    toastProfileFailed: '资料保存失败',
    toastLoggedOut: '已退出登录',
    toastLearnerSaved: '学习档案已更新',
    roles: {
      student: '学生',
      admin: '管理员',
    } as Record<string, string>,
    nav: {
      account: '账户',
      about: '关于你',
      prefs: '学习偏好',
      points: '积分',
      import: '导入',
      more: '更多',
    },
    account: {
      caption: '账户',
      descriptionAuthed: '修改你的展示信息和登录方式',
      descriptionGuest: '登录后可同步学习数据',
      nickname: '昵称',
      email: '邮箱',
      phone: '手机',
      unset: '未设置',
      noContact: '尚未填写联系方式',
      saveProfile: '保存资料',
      savingProfile: '保存中…',
      changePassword: '修改密码',
      logout: '退出登录',
      statusLabel: '状态',
      statusGuest: '未登录',
      login: '登录',
      register: '注册',
      guestBody: '登录后，你的课堂、笔记和学习数据会安全地同步到云端，换设备也不丢。',
    },
    about: {
      caption: '关于你',
      description: '你是谁、想去哪——AI 接着这个陪你学',
      profileCardLabel: '学习档案',
      coachCardLabel: '教练画像',
      identityLabel: '身份',
      gradeLabel: '年级',
      majorLabel: '专业',
      directionLabel: '方向',
      industryLabel: '行业',
      goalLabel: '目标',
      alsoLearningLabel: '也在学',
      notSet: '未设置',
      editProfile: '重新填写学习档案',
      fillProfile: '填写学习档案',
      emptyProfile: '告诉同学你的身份背景，让 AI 回答更贴你。',
      coachBioTitle: '教练记下的你',
      coachGoalsTitle: '你想要的',
      coachUpdatedAt: (date: string): string => `上次更新 · ${date}`,
      chatAgain: '和教练再聊聊',
      chatStart: '和教练聊一聊',
      clearBio: '清除画像',
      clearBioConfirm: '确定要清除画像吗？以后回访时会重新认识你。',
      emptyCoach: '还没和教练聊过。你最近想做的事 / 想去的方向 / 还在纠结的选择，都可以慢慢说。',
    },
    prefs: {
      caption: '学习偏好',
      description: '录课、复习和同桌回答的默认行为',
      modelLabel: '回答方式',
      modelAuto: '自动选择',
      modelAutoWithDefault: (name: string): string => `自动选择（${name}）`,
      modelAutoRecommended: '自动选择（推荐）',
      modelRecommendedSuffix: '（推荐）',
      timestampsLabel: '回答里附时间戳',
      timestampsHint: 'AI 引用课堂内容时附 [MM:SS] 标签，点击跳回原片段',
      thinkingLabel: '展示思考过程',
      thinkingHint: '开启后 AI 先展示推理过程再给最终答案；关闭由 AI 自己判断',
      autoSaveLabel: '自动保存',
      autoSaveHint: '录音结束后自动保存到云端',
      classCheckLabel: '随堂检验',
      classCheckHint: '播放视频或音频时 AI 会在合适的节点自动暂停并出题',
    },
    import: {
      caption: '导入',
      description: '从 B 站等平台导入课程时需要的凭证',
      cookieLabel: 'B站 Cookie',
      cookiePlaceholder: '粘贴 SESSDATA、bili_jct、DedeUserID',
      cookieNote: '仅保存在当前浏览器',
      clearCookie: '清除 Cookie',
      helpToggle: '如何获取导入凭证',
      helpSteps: [
        '登录 bilibili.com',
        '按 F12 打开开发者工具',
        '切到「应用 / Application」',
        '找到 Cookie → https://www.bilibili.com',
        '复制 SESSDATA、bili_jct、DedeUserID 并用分号拼接',
      ],
    },
    more: {
      caption: '更多',
      help: '帮助中心',
      feedback: '意见反馈',
    },
    footerVersion: (version: string): string => `MeetMind · 版本 ${version}`,
  } as const;

export type SettingsCopy = typeof SETTINGS_COPY;
