/**
 * copy.ts — 用户面可见文案的单一真相源。
 *
 * 为什么要有这个文件：
 *   过去散在 10+ 个组件里的字符串里夹带了"回声卡 / 酿 / 预知气泡 / 工坊"
 *   这类内部术语，被用户看到时跳戏。把所有用户可见的文案汇总在这里，
 *   才能以"顶级 UI/UX 设计师"的视角一次性审过口吻、去掉行业黑话。
 *
 * 口吻原则（M8-agent-native）：
 *   - 角色：一个叫"同学"的 AI 同桌。像朋友，不像老师，不像客服
 *   - 说话方式：安静、直接、克制
 *   - 禁用词：回声卡 / 酿 / 预知气泡 / 工坊 / 研判 / 引擎 / 引导
 *   - 首选词：收藏 / 整理 / 情报 / 应用 / 同学
 *
 * 使用约定：
 *   - 所有出现在用户界面（非日志/埋点）的字符串必须 import { COPY }
 *   - 新增字符串时先找有没有相近语义的键可以复用，避免二次碎片化
 *   - 复杂占位符用函数而非模板字符串，便于测试
 */

export const COPY = {
  identity: {
    productName: 'MeetMind',
    name: '同学',
    tagline: '真正懂你在学什么的 AI 同学',
    subtagline: '理解你的课堂、资料和目标，陪你学懂当下，也发现下一步值得看的内容。',
  },

  landing: {
    media: {
      realProduct: '真实产品画面',
      videoFallback: '你的浏览器暂时无法播放这段产品录屏。',
    },
    navigation: {
      product: '产品',
      philosophy: '为什么是 MeetMind',
      technology: '技术',
      signIn: '登录',
      openProduct: '进入 MeetMind',
    },
    hero: {
      eyebrow: '真正听过这节课的 AI 同学',
      title: '真正听过这节课，\n才知道你哪里没懂。',
      body: '录下课堂，发来资料。MeetMind 记得老师怎么讲，也知道你在哪里卡住，把每一次学习接成一条不会断的线。',
      primaryAction: '先试听一节课',
      secondaryAction: '看看它怎么工作',
      imageAlt: '大学生在真实课堂中听课并记录笔记',
      videoAlt: 'MeetMind 真实试听课正在展示实时转录、课堂脉络和同学',
      demoLabel: '正在听 · 英语听力',
      demoTime: '18:42',
      demoTranscript: '条件概率不是换一个公式，而是缩小我们正在观察的世界。',
      demoContext: '已接上：上节课的贝叶斯公式',
      demoBoard: '板书已收下',
      demoLive: '课堂脉络正在生长',
      filmLabel: 'MeetMind 产品短片',
      filmDuration: '45 秒 · 真实操作短片',
      filmChapters: ['正在听懂这节课', '把问题练到会', '把每次学习接起来', '从一节课，走向一门课'] as const,
      filmClosingTitle: '从听懂这一节课，\n到学会这一门课。',
      filmClosingBody: '真正懂你在学什么的 AI 同学',
      playFilm: '播放产品短片',
      pauseFilm: '暂停产品短片',
      unmuteFilm: '开启产品短片声音',
      muteFilm: '关闭产品短片声音',
      listenFilm: '听产品介绍',
    },
    belief: {
      eyebrow: '学习不该在下课铃响时断掉',
      title: '模型懂世界，还不够。\n它还得懂正在学习的你。',
      body: '一次回答可以很聪明，真正的学习却发生在一节又一节课之间。MeetMind 保留老师的原话、你的困惑和正在靠近的目标，让下一次帮助从你真正停下的地方继续。',
    },
    manifesto: {
      lineA: '不是笔记工具，也不只是课堂转录。',
      lineB: '它真的听过课，也知道你正在学什么。',
    },
    classroomLine: {
      eyebrow: '课堂线',
      title: '从一节真实的课，\n一直陪到考试。',
      body: '录、问、练、证、考——五个动作发生在同一个现场里，不需要在四个工具之间搬运。',
      previous: '查看上一个阶段',
      next: '查看下一个阶段',
      ariaLabel: '课堂线的五个阶段',
      stages: [
        { step: '01', verb: '录', title: '先录下这节课', body: '麦克风、电脑声音，或两路都录。原声一直在，转录只是开始。' },
        { step: '02', verb: '问', title: '同桌跟上课堂', body: 'AI 同学听着同一段话。卡住时直接问，不用举手，也不用等下课。' },
        { step: '03', verb: '练', title: '从原话出发复习', body: '闪卡、测验、思维导图，都从老师真正讲过的内容里长出来。' },
        { step: '04', verb: '证', title: '每个结论都有根', body: '回答可以跳回 [MM:SS] 的那一刻。不是听起来对，是真的对。' },
        { step: '05', verb: '考', title: '多节课连成考试范围', body: '几节课成单元，一学期压成一张能带进考场的速查表。' },
      ] as const,
    },
    collectionLine: {
      eyebrow: '收集线',
      title: '像发消息一样，\n先把它收下。',
      body: '文字、语音、图片、网页、文件和一闪而过的想法。不用分类，不用打标签。',
      silentNote: '模型在后台判断它属于哪门课、哪个目标、哪个问题，再悄悄回流到课堂和你的长期上下文。',
      types: ['文字', '语音', '图片', '网页', '文件', '想法'] as const,
      sinkLabel: '先收下',
      statusLabel: '都已收下 · 后台正在判断归属',
      samples: [
        { kind: 'text', label: '文字', text: '这个 intuition 比我们老师讲得清楚' },
        { kind: 'voice', label: '语音', text: '0:12' },
        { kind: 'link', label: '网页', text: '贝叶斯定理的直觉解释' },
        { kind: 'image', label: '图片', text: '黑板照片' },
        { kind: 'file', label: '文件', text: '第三章讲义.pdf' },
      ] as const,
    },
    bridge: {
      eyebrow: '两条线，不会成为数据孤岛',
      lead: '好的回答，来自三样东西',
      parts: ['个人上下文', '场景上下文', '模型智能'] as const,
      partNotes: ['目标 · 阶段 · 长期困惑', '这节课 · 这份材料 · 此刻意图', '解释 · 定位 · 验证 · 克制'] as const,
    },
    control: {
      eyebrow: '上下文属于你',
      title: '不让你管理数据库。',
      body: '你不需要维护标签和画像。它记住的东西，你随时看得见，也随时改得动。',
      items: ['查看它记住了什么', '纠正说错的地方', '暂停某条理解', '忘记一段过去'] as const,
    },
    journey: {
      eyebrow: '从现场开始，一直陪到学会',
      title: '把一节真实的课，\n变成一条不会断的学习线。',
      body: '课堂、课后、考试与长期目标，不再是四个互不认识的工具。',
      tabsLabel: '选择学习场景',
      previousScene: '查看上一个学习场景',
      nextScene: '查看下一个学习场景',
      classroomImageAlt: '课堂录音与实时理解',
      scenes: [
        {
          id: 'classroom',
          label: '上课',
          kicker: '听懂现场',
          title: '不只转成文字，还在跟上这节课。',
          body: '原话、板书和课堂脉络按时间排在一起。需要回来的地方先替你留住，听课时不用低头整理。',
          detail: '原话 · 板书 · 课堂脉络',
          metric: '课中',
          imageAlt: '真实试听课中的实时转录、课堂脉络和同学三栏界面',
          proofs: ['实时转录与双语理解', '课堂脉络随音频推进', '卡住时在同一现场直接问同学'] as const,
        },
        {
          id: 'capture',
          label: '放资料',
          kicker: '连起材料',
          title: '课件、网页和随手拍，不再各自孤立。',
          body: '像发消息一样把资料放进来。MeetMind 自动辨认它与哪门课、哪个问题和哪个目标有关。',
          detail: '文件 · 链接 · 图片 · 想法',
          metric: '随手',
          imageAlt: 'MeetMind 真实收集流与文件上传入口',
          proofs: ['文字、链接、图片和文件都能收下', '材料自动接回相关课堂', '需要时直接带着材料问同学'] as const,
        },
        {
          id: 'review',
          label: '课后',
          kicker: '练到会用',
          title: '从老师的原话出发，解释、练习、再验证。',
          body: '闪卡、测验和思维导图不是模板生成，而是从这节课真实讲过的内容里长出来。',
          detail: '解释 · 闪卡 · 测验 · 思维导图',
          metric: '有根',
          imageAlt: '真实课后复习三栏中的原声证据、闪卡训练和 AI 同学',
          proofs: ['左侧保留原声和转录证据', '中间完成闪卡、测验与思维导图', '右侧同学始终知道正在练什么'] as const,
        },
        {
          id: 'exam',
          label: '备考',
          kicker: '跨课整理',
          title: '几节课连成单元，一学期压成考试范围。',
          body: '自由选择课程与课次，生成可编辑、可打印、能真正带进考场的高密度速查表。',
          detail: '多课范围 · 薄弱点 · 可打印速查表',
          metric: '跨课',
          imageAlt: '真实考试速查表跨课程与课堂范围选择界面',
          proofs: ['跨课程勾选真实课堂', '精确选择考试覆盖的课次', '整理成可编辑、可打印的高密度参考表'] as const,
        },
        {
          id: 'context',
          label: '越用越懂',
          kicker: '个人上下文',
          title: '它逐渐知道你会什么，也知道你正在努力什么。',
          body: '客观学习现场与长期理解分开保存。你能看见、纠正、暂停或忘记，掌控权始终在你手里。',
          detail: '目标 · 掌握情况 · 学习方式 · 最近现场',
          metric: '长期',
          imageAlt: 'MeetMind 真实个人上下文中的长期理解、课程考试和最近学习现场',
          proofs: ['最近学习现场保持客观', '长期理解只保留有证据的内容', '随时可以纠正、暂停或忘记'] as const,
        },
      ] as const,
    },
    featureRail: {
      eyebrow: '真实操作 · 连续场景',
      title: '不是功能清单，\n是一条完整的学习路径。',
      body: '左右滑动，每个短片都来自 MeetMind 的真实操作。你看到的不只是结果，还有从课堂现场到理解验证的完整过程。',
      ariaLabel: 'MeetMind 产品功能场景',
      previous: '查看上一个产品场景',
      next: '查看下一个产品场景',
      scenes: [
        {
          id: 'live-class',
          step: '01',
          title: '正在听课',
          body: '原话、课堂脉络和同学一起跟上现场。',
          videoAlt: 'MeetMind 正在实时理解课堂内容',
        },
        {
          id: 'end-class',
          step: '02',
          title: '结束课堂',
          body: '一次点击，把现场收束成可以继续学习的完整证据。',
          videoAlt: '结束 MeetMind 课堂并进入课后整理',
        },
        {
          id: 'evidence-review',
          step: '03',
          title: '从证据开始复习',
          body: '原声和时间点留在左边，练习从老师真正讲过的内容开始。',
          videoAlt: 'MeetMind 课后复习保留原声和转录证据',
        },
        {
          id: 'quiz-submit',
          step: '04',
          title: '选择并提交答案',
          body: '测验不是结果页，而是一次对理解的真实验证。',
          videoAlt: '在 MeetMind 课堂测验中选择并提交答案',
        },
        {
          id: 'evidence-jump',
          step: '05',
          title: '从解释跳回原话',
          body: '每个结论都能回到老师讲过的那一刻。',
          videoAlt: '从测验解释跳回对应的课堂原话',
        },
        {
          id: 'learning-methods',
          step: '06',
          title: '六种学习方式',
          body: '按这节课的内容，继续闪卡、测验、导图或其他练习。',
          videoAlt: 'MeetMind 展示六种基于课堂的学习方式',
        },
        {
          id: 'complete-mindmap',
          step: '07',
          title: '展开完整导图',
          body: '根节点、3 个分支和 9 个节点一次看全，没有裁切。',
          videoAlt: '完整展示根节点、三个分支和九个节点的课堂思维导图',
        },
      ] as const,
    },
    livePreview: {
      status: '可交互试听',
      eyebrow: '一节真的能听、能问、能复习的课',
      title: '现在就坐进这节课里。',
      body: '播放试听课，看看 MeetMind 如何跟着老师往前走；卡住时直接问，下课后继续复习。',
      action: '开始试听',
      frameTitle: 'MeetMind 试听课堂',
    },
    difference: {
      eyebrow: '同一个问题，答案为什么不一样',
      title: '好的回答，来自它知道你为什么现在问。',
      prompt: '“为什么这里可以直接用贝叶斯公式？”',
      genericLabel: '只看见这个问题',
      genericAnswer: '贝叶斯公式描述了条件概率之间的关系。套用公式即可计算后验概率。',
      meetmindLabel: 'MeetMind 还看见',
      contextItems: ['18:42 的老师原话', '刚拍下的板书', '上节课标记的困惑', '两周后的期末目标'],
      meetmindAnswer: '老师这里先把观察范围缩小到了“检测为阳性”的人。你上节课卡住的正是这个条件空间变化，所以这次先不代数，沿着板书把样本空间重新圈一遍。',
    },
    outcomes: {
      eyebrow: '回来时，比发出去的更好',
      title: '一节课、一个单元、一场考试，都有真正能带走的结果。',
      items: [
        {
          number: '01',
          scope: '一节课后',
          title: '知道讲了什么，也知道自己哪里没懂。',
          body: '课堂整理、原话证据、困惑解释和即时练习。',
        },
        {
          number: '02',
          scope: '几节课后',
          title: '零散知识开始连成一个可以调用的结构。',
          body: '单元关系、重复出现的难点和薄弱点复练。',
        },
        {
          number: '03',
          scope: '考试之前',
          title: '把一学期真正压缩成自己带得走的东西。',
          body: '考试范围、复习路线、模拟检验和可打印速查表。',
        },
      ] as const,
    },
    context: {
      eyebrow: '你的学习，不该散落在不同工具里',
      title: '每一次课堂、资料和提问，\n都在养成一套属于你的学习上下文。',
      body: '未来的 AI 会越来越聪明，但认识你仍然需要时间。MeetMind 做的，就是把这些时间留住，让任何一次新的智能都能从真正的你开始。',
      action: '了解我们的技术',
      flow: ['课堂原话', '资料与收藏', '困惑与练习', '目标与进度', '你的学习上下文'] as const,
    },
    finalCta: {
      eyebrow: '从一节真实的课开始',
      title: '下一次下课，\n别再从头整理。',
      body: '先试听一节完整课堂，看看 MeetMind 如何从听课一直陪到复习。',
      primaryAction: '先试听一节课',
      secondaryAction: '登录 MeetMind',
    },
    desktop: {
      eyebrow: '桌面端',
      title: '装到电脑上，\n它就能听见你在上的课。',
      body: '桌面端让 MeetMind 常驻在屏幕角落：录网课时直接收电脑里的声音，不用带机器人入会；任何画面按一下热键，就截图收进你的学习上下文。',
      macAction: '下载 macOS 版',
      macNote: 'Apple Silicon 芯片',
      macIntelNote: 'Intel 芯片版',
      windowsAction: '下载 Windows 版',
      windowsNote: 'Windows 10 及以上 · 64 位',
      hotkeyHint: '截图热键 Ctrl/Cmd + Shift + M',
      unsignedNote: '安装包暂未签名：macOS 请「右键 → 打开」，Windows 请在 SmartScreen 提示中选「仍要运行」。',
    },
    footer: {
      tagline: '真正懂你在学什么的 AI 同学',
      product: '产品',
      technology: '技术',
      login: '登录',
      copyright: '© 2026 MeetMind',
    },
  },

  technology: {
    label: 'Technology',
    imageAlt: '大学课堂中的 MeetMind 技术现场',
    navigation: {
      product: '回到产品',
      architecture: '架构',
      evaluation: '评测',
      questions: '技术问答',
      openProduct: '体验 MeetMind',
    },
    hero: {
      eyebrow: 'MeetMind Technology',
      title: 'AI 越来越聪明，\n但认识一个人，仍然需要时间。',
      body: 'MeetMind 构建的不是另一个聊天窗口，而是一套以学习者为中心、可纠正、可验证、能跨课堂持续积累的个人上下文基础设施。',
      primaryAction: '查看系统架构',
      secondaryAction: '阅读技术问答',
      statusLabel: '当前系统',
      statusValue: '课堂场景 · 持续迭代',
    },
    thesis: {
      eyebrow: '我们的技术判断',
      title: '好的输出 = 个人上下文 + 场景上下文 + 模型智能。',
      body: '大模型提供通用智能，MeetMind 负责持续保留真实学习证据、理解此刻意图，并把正确的上下文交给正确的模型。产品的长期价值不在一次生成，而在每次帮助都比上一次更了解用户。',
    },
    architecture: {
      eyebrow: 'Context Architecture',
      title: '从原始证据，到真正属于这个人的回答。',
      stages: [
        { index: '01', title: '原始学习证据', body: '原声、视频、转录、板书、课件、网页和用户自己的表达。' },
        { index: '02', title: '场景上下文', body: '一节课、一道题或一次讨论中的时间、进度、结构与当前意图。' },
        { index: '03', title: '个人上下文', body: '跨课积累的目标、掌握情况、学习方式、行为与用户确认过的长期理解。' },
        { index: '04', title: '模型智能', body: '根据任务选择模型、工具和渲染方式，当前表达与当前场景始终优先。' },
        { index: '05', title: '学习交付', body: '解释、定位、练习、速查表、复习路线，以及能继续进入下一次学习的结果。' },
      ] as const,
    },
    trace: {
      eyebrow: '一次真实请求里发生了什么',
      title: '上下文不是黑箱。',
      question: '为什么这里可以直接用贝叶斯公式？',
      usedTitle: '这次实际接入',
      usedItems: ['当前课堂 18:42 的原话', '刚拍下的板书', '上节课的同主题困惑', '概率论期末目标'],
      skippedTitle: '这次主动不使用',
      skippedItems: ['无关课程记录', '未被用户确认的推断', '已经过期的学习线索'],
      outputTitle: '模型收到的任务',
      output: '先解释条件空间为什么变化，再沿课堂板书验证；不要只重复公式定义。',
      boundary: '用户此刻的问题拥有最高优先级；长期画像只能补充，不能覆盖。',
    },
    asr: {
      eyebrow: 'Classroom ASR',
      title: '实时要快，课后要准。两个目标不该互相牺牲。',
      body: 'MeetMind 保留完整原声，同时提供低延迟临时字幕。下课后再用完整音频定稿，修正上下文、术语和断句，并按严格的课堂会话边界替换课中字幕。',
      steps: [
        { label: '课中', title: '实时字幕', body: '连续音频、抗重连队列、低延迟渲染与上下文术语提示。' },
        { label: '原件', title: '完整原声', body: '录音在实时通道就绪前已经开始保留，网络波动不等于课堂丢失。' },
        { label: '课后', title: '完整定稿', body: '长音频分段、重叠缝合、低置信片段校对与新旧课堂严格隔离。' },
        { label: '可选', title: '说话人信息', body: '只有证据可靠时才展示匿名说话人；默认不以牺牲准确率和设备兼容性换标签。' },
      ] as const,
    },
    memory: {
      eyebrow: 'Memory With Agency',
      title: '让模型管理复杂度，让用户保留掌控感。',
      objectiveTitle: '客观学习现场',
      objectiveBody: '最近课堂、材料、练习和对话按发生事实记录，用于接续当前任务。',
      longTermTitle: '长期学习理解',
      longTermBody: '只有稳定且有证据的理解才进入长期层；用户随时可以纠正、暂停或忘记。',
      modelTitle: '模型自主选择',
      modelBody: '系统提供候选上下文、来源和边界，模型判断此刻真正需要什么，不依赖脆弱的关键词规则。',
    },
    evaluation: {
      eyebrow: 'Evaluation, not vibes',
      title: '每次模型和链路升级，都必须留下可比较的数字。',
      body: '我们将产品体验拆成可复现的评测：既看模型回答，也看真实链路中的延迟、证据和回归。没有真实基线的数据，不拿来做营销结论。',
      metrics: [
        { code: 'ASR', title: '准确率与延迟', body: 'CER / WER、首字延迟、稳定字幕延迟、噪音场景和长音频定稿改善。' },
        { code: 'CTX', title: '上下文使用', body: '是否找对课堂与材料、是否误用长期画像、是否遗漏用户当前表达。' },
        { code: 'TUTOR', title: '教学回答', body: '课堂引用准确率、解释质量、追问必要性、练习与目标的一致性。' },
        { code: 'REG', title: '持续回归', body: '固定数据集、真实调用、基线门禁与每次变更后的自动比较。' },
      ] as const,
    },
    questions: {
      eyebrow: 'Technical Q&A',
      title: '投资人、研究者和合作伙伴最常问的问题。',
      items: [
        {
          question: '为什么不能只使用大模型越来越长的上下文窗口？',
          answer: '窗口长度解决“能放多少”，不解决“该放什么、谁确认过、是否仍然有效、跨产品如何持续”。MeetMind 的价值是保留证据、组织边界、控制权限，并在每次任务中选择真正相关的上下文。',
        },
        {
          question: '这与 NotebookLM 或普通 AI 笔记有什么不同？',
          answer: '文档问答通常围绕一次上传建立临时知识空间。MeetMind 从真实课堂现场开始，把课中进度、课后练习结果和跨课学习目标同时纳入，并让这些结果继续回写下一次学习。',
        },
        {
          question: '如何避免模型错误地“记住”用户？',
          answer: '客观事件与模型理解分层保存；当前表达优先；长期理解必须有证据与稳定性门槛。用户可以查看来源、纠正、暂停和忘记，模型推断不能伪装成用户事实。',
        },
        {
          question: '为什么不把说话人识别作为默认能力？',
          answer: '单设备远场课堂中的说话人分离容易受到混响、重叠说话和设备差异影响。产品默认先保证内容完整和准确；只有证据达到门槛时才显示匿名说话人，复杂分离作为可选能力而不是主链路依赖。',
        },
        {
          question: '技术壁垒最终会在哪里形成？',
          answer: '不是单一模型，而是长期高质量个人上下文、真实学习反馈、跨模态课堂证据、稳定评测体系，以及把这些能力变成低负担消费体验的系统工程。模型升级会成为增益，而不是把产品价值清零。',
        },
        {
          question: '未来如何与其他 AI 和硬件连接？',
          answer: '个人上下文应当属于用户。长期方向是让用户授权后的上下文可以被其他 AI 即插即用，同时把学习设备、健康硬件和行为数据保持在清晰、可撤回的权限边界内。',
        },
      ] as const,
    },
    finalCta: {
      title: '想看真实链路、评测结果或合作方案？',
      body: '我们愿意讨论技术，而不是只展示一张架构图。',
      productAction: '先体验产品',
      contactAction: '联系 MeetMind',
      contactHref: 'mailto:originedu@meetmind.online',
    },
    footer: {
      label: 'MeetMind Technology',
      product: '产品首页',
      app: '打开产品',
      copyright: '© 2026 MeetMind',
    },
  },

  cta: {
    demo: '看一节示例课',
    record: '开始一节课',
    ask: '问同学',
  },

  navigation: {
    back: '返回',
    classroom: '课堂',
    collection: '收集',
    search: '问同学',
    allCollections: '全部收集',
  },

  globalAsk: {
    title: '问同学',
    subtitle: '相关课堂、资料和你的上下文会自动接上。',
    welcomeEyebrow: '从你正在学的地方继续',
    quickMode: '直接回答',
    deepMode: '陪我学会',
    modeSelectorLabel: '选择问同学的方式',
    quickModeBody: '马上回答，自动接上相关内容',
    deepModeBody: '先理解目标，再陪你走完整过程',
    memoryAction: '我的上下文',
    newConversation: '新对话',
    historyRestored: '已接回上次对话',
    historyLoading: '正在接回上次对话…',
    freshConversation: '新的对话',
    emptyTitle: '此刻，想弄明白什么？',
    emptyBody: '直接说就好。MeetMind 会自己找到相关课堂、材料和你之前留下的线索。',
    deepEmptyTitle: '这次，想真正学会什么？',
    deepEmptyBody: 'MeetMind 会先理解你要达到的结果，再陪你解释、练习和验证；只有必要时才问一个选择。',
    quickExamples: ['帮我解释刚才课堂里最难的概念', '把这份材料和我最近学的内容连起来'] as const,
    deepExamples: ['我想系统学懂这个主题，并检验自己是否真的会了', '围绕期末目标，把相关课堂整理成一条学习路线'] as const,
    composerQuick: '问任何正在学、正在想的事',
    composerDeep: '说说这次想真正学会什么',
    startersTitle: '也可以从这里开始',
    send: '发送',
    stop: '停止',
    preparingIntent: '正在接上相关内容…',
    intentEyebrow: '先对齐一件事',
    intentProgress: (current: number, total: number): string => `${current} / ${total}`,
    intentSingle: '选一个就好',
    intentMultiple: '可以多选',
    intentCancel: '直接开始',
    intentBack: '上一步',
    intentContinue: '继续',
    intentResolve: '继续',
    intentStart: '开始学习',
    intentFirstStep: '先从这里开始',
    approachUnderstand: '理解清楚',
    approachPractice: '练到会用',
    approachSynthesize: '串成体系',
    approachCreate: '做出结果',
    contextPersonal: '用长期上下文',
    contextCurrent: '用当前内容',
    contextMixed: '两边一起看',
    contextStatus: '已接入',
    contextAction: '参考范围',
    contextSummary: (current: number, recent: number, memory: number): string => {
      const parts = [
        current > 0 ? `${current} 份当前内容` : '',
        recent > 0 ? `${recent} 条最近学习` : '',
        memory > 0 ? `${memory} 条长期理解` : '',
      ].filter(Boolean);
      return parts.length > 0 ? `会参考 ${parts.join('、')}` : '这次先从你的问题开始';
    },
    contextCurrentCount: (count: number): string => `${count} 份当前材料`,
    contextRecentCount: (count: number): string => `${count} 条最近学习`,
    contextMemoryCount: (count: number): string => `${count} 条长期记忆`,
    contextEmpty: '这次先从你的问题开始',
    contextRailEyebrow: '上下文已就位',
    contextRailTitle: '这次会用到什么',
    contextRailBody: '只展示实际接入的内容。回答仍以你此刻的问题为准。',
    contextDrawerCurrent: '当前内容',
    contextDrawerRecent: '最近学习现场',
    contextDrawerRecentBody: '用来接续你刚才做到的地方',
    contextDrawerMemory: '长期学习理解',
    contextDrawerMemoryBody: '只使用你已确认或可随时纠正的内容',
    contextConnected: '已接入这次对话',
    contextWaiting: '有内容后自动接入',
    contextActiveThread: '正在继续的学习',
    progressEyebrow: 'MeetMind 更新了对你的理解',
    progressHint: '这些理解会随着之后的学习继续调整。',
    progressDismiss: '这次不记',
    progressSave: '记住确认的',
    progressSaved: '已经记下，也可以随时纠正',
    memoryTitle: '我的上下文',
    memoryBack: '返回',
    contextLibraryNavigation: '浏览上下文',
    contextCoursesOverviewTitle: '课程与考试',
    contextCoursesOverviewBody: '查看课堂如何归入课程、纠正课程边界，或跨课程选择考试范围。',
    memoryUnderstandingTab: '对我的理解',
    memoryCoursesTab: '课堂上下文',
    memoryRecentTab: '客观记录',
    memoryUnderstandingTitle: 'MeetMind 记得的你',
    courseContextTitle: '我的课程',
    courseContextEmpty: '录下一节课后，课程会自动在这里出现。',
    courseContextLessons: (count: number): string => `${count} 节课`,
    courseContextMinutes: (count: number): string => `${count} 分钟`,
    courseContextActive: '正在参考',
    courseContextPaused: '已暂停参考',
    courseContextSuggested: '待确认',
    courseContextUnclassified: '单节课堂',
    courseContextDetached: '已移出',
    courseContextRename: '改课程名',
    courseContextRenameHint: '例如：线性代数',
    courseContextTags: '课程标签',
    courseContextTagsHint: '例如：专业课、期末重点',
    courseContextSave: '确认',
    courseContextCancel: '取消',
    courseContextPause: '暂不参考这门课',
    courseContextResume: '重新参考这门课',
    courseContextDetails: '查看课堂',
    courseContextCollapse: '收起课堂',
    courseContextConfirm: '确认属于同一门课',
    courseContextDetach: '移出',
    courseContextDetachTitle: (title: string): string => `将“${title}”移出这门课`,
    courseContextRestore: '放回原课程',
    courseContextCheatsheet: '单元速查表',
    courseCheatsheetEntryEyebrow: '跨课与考试',
    courseCheatsheetEntryTitle: '考试速查表',
    courseCheatsheetEntryBody: '从多门课程、课堂录音和上传材料中直接勾选考试范围，整理成可编辑、可打印的高密度参考表。',
    courseCheatsheetEntryAction: '选择考试范围',
    courseCheatsheetEntryCourseAction: '从这门课开始',
    courseCheatsheetEntryEmpty: '至少保留两节有原文的课堂后，就可以直接组合考试范围。',
    courseCheatsheetEntryAvailable: (courses: number, lessons: number): string => `${courses} 门课程 · ${lessons} 节课堂可选`,
    courseCheatsheetScopeEyebrow: '多课程范围',
    courseCheatsheetScopeHint: '课程只是帮你快速定位，不是限制。可以跨课程勾选，也可以精确到某一节课堂。',
    courseCheatsheetCoursesLabel: '课程',
    courseCheatsheetClear: '清空',
    courseCheatsheetSelectionSummary: (courses: number, lessons: number): string => `已选 ${courses} 门 · ${lessons} 节`,
    courseCheatsheetCourseSelection: (selected: number, total: number): string => `${selected}/${total} 节已选`,
    courseCheatsheetEmptySelectionTitle: '先选择课程',
    courseCheatsheetEmptySelectionBody: '选中课程后，可以继续精确到具体课堂。',
    courseCheatsheetMinimumHint: '至少选择两节有原文的课堂',
    courseContextCombinedScope: (count: number): string => `${count} 门课程的考试范围`,
    courseContextBackToCourse: '返回课程',
    courseContextCheatsheetNeedsTranscript: (count: number): string => count === 0
      ? '这些课堂还没有可用原文。'
      : `目前只有 ${count} 节课有可用原文，至少需要两节。`,
    courseContextChooseLessons: '这次要带上哪些课？',
    courseContextChooseLessonsHint: '先选同一单元或同一考试范围；最近四节已替你选好。',
    courseContextSelectAll: '全选',
    courseContextBeginCheatsheet: (count: number): string => `用这 ${count} 节课整理`,
    courseContextCheatsheetLoading: '正在把这几节课压成一份纸面速查表',
    courseContextCheatsheetNotReady: '所选内容里还没有足够稳定的学科知识，暂时做不出可靠的考试速查表。课堂原文已经保留，可以返回课程后换一组范围。',
    courseContextRecording: '录音',
    courseContextUpload: '上传',
    courseContextVideo: '视频',
    courseContextUntitled: '待命名课程',
    courseContextRecordingLesson: '课堂录音',
    courseContextUploadLesson: '上传课堂',
    courseContextVideoLesson: '视频课堂',
    courseContextFallbackTitle: (month: number, day: number): string => `${month} 月 ${day} 日的课`,
    courseContextLessonFallbackTitle: (month: number, day: number, time: string): string => `${month} 月 ${day} 日 ${time} 的课`,
    courseContextScheduleTitle: (weekday: string): string => `${weekday}的课`,
    courseContextRecurring: (weekday: string, time: string): string => `常在${weekday} ${time} 上课`,
    courseAssessmentAdd: '这门课有考试',
    courseAssessmentEditTitle: '考试',
    courseAssessmentDefaultName: (courseTitle: string): string => `${courseTitle}考试`,
    courseAssessmentName: '考试名称',
    courseAssessmentNameHint: '例如：期末考试',
    courseAssessmentDate: '考试日期',
    courseAssessmentMode: '考试方式',
    courseAssessmentUnknown: '还不确定',
    courseAssessmentClosedBook: '闭卷',
    courseAssessmentOpenBook: '开卷',
    courseAssessmentScope: '考试范围',
    courseAssessmentScopeHint: '可选：粘贴老师公布的范围或大纲',
    courseAssessmentHasScope: '已有范围',
    courseAssessmentSave: '记下',
    courseAssessmentStop: '不再准备',
    courseAssessmentEdit: '修改考试信息',
    courseAssessmentPrepare: '做速查表',
    courseAssessmentChooseScope: '哪些课在考试范围内？',
    memoryKindPreference: '学习方式',
    memoryKindStrength: '正在形成的能力',
    memoryKindChallenge: '还在弄懂',
    memoryKindTopic: '正在关注',
    memoryKindProgress: '最近进展',
    memorySourceUser: '你告诉 MeetMind 的',
    memorySourceAi: '从你的学习互动中理解到的',
    memoryCorrection: '不太准确',
    memoryAddContext: '补充一下',
    memoryCorrectionHint: '换成更准确的说法',
    memoryCorrectionSave: '改好了',
    memoryCorrectionCancel: '取消',
    memoryMore: '更多操作',
    memoryStopUsing: '暂不参考',
    memoryUseAgain: '重新参考',
    memoryForget: '忘记这条',
    memoryTalkPrompt: '关于我，想补充或纠正的是：',
    memoryEmpty: '还没有形成稳定的理解。先正常学习就好，MeetMind 会从真实过程里慢慢认识你。',
    memoryPaused: '已不再参考',
    recentTitle: '最近学习现场',
    recentEmpty: '最近还没有可恢复的学习活动。',
    recentKindConversation: '一次对话',
    recentKindLesson: '一节课堂',
    recentKindApp: '一次练习',
    recentKindCapture: '一份学习材料',
    recentShowAll: (count: number) => `查看全部 ${count} 条学习现场`,
    recentCollapse: '收起较早记录',
    threadTitle: '上次还在继续',
    threadResume: '接着学',
    threadComplete: '这条学完了',
    preparingError: '这次没理解准，先直接回答你。',
    refiningError: '先按目前的理解开始，之后还可以随时调整。',
    responseError: '刚才没有接上，再发一次就好。',
    sourceContext: '刚刚在看的内容',
    sourceCurrentLesson: '当前课堂转录',
    openSource: '打开原内容',
    close: '关闭问同学',
    assistantLabel: 'MeetMind 回答',
    userLabel: '你的问题',
    thinking: '正在把上下文接起来…',
    recentConversation: '问同学的对话',
    recentDeepSession: '一起学的对话',
    recoveryEyebrow: '接回学习现场',
    recoveryTitle: '不用重新开始',
    recoveryBody: 'MeetMind 留住了上次的脉络，回来可以直接接着走。',
    recoveryResume: '接着上次学',
    recoveryRecent: '最近停在这里',
    appActivity: (name: string) => `完成了「${name}」`,
    appResultSummary: (count: number) => `生成了 ${count} 条可继续使用的学习内容`,
  },

  tutor: {
    emptyAfterName: '在这里。',
    reviewStarters: ['先讲清这节课的主线', '从我标记的地方开始'] as const,
  },

  actionList: {
    title: '今晚行动清单',
    emptyTitle: '还没有行动项',
    emptyBody: '标记一处困惑后，同学会把下一步放在这里。',
    completedTitle: '今天先到这里',
    completedBody: '行动项已经全部完成。',
    closeHint: '按 ESC 或点击空白处关闭',
  },

  collection: {
    askClassmate: '问同学',
    emptyTitle: '想到什么，就留在这里。',
    emptyBody: '不用分类，不用打标签。同学会在后台把它接回相关的课堂、目标和问题。',
    emptyTypes: ['文字', '语音', '图片', '网页', '文件', '想法'] as const,
    emptyWechatHint: '也可以从微信直接发给我。',
    deleteMemoryWarning: '删除后，这条内容不会再进入同学的回答、后续情报和个人上下文。',
    permanentDeleteWarning: '彻底删除后，这条内容不会再进入同学的回答、后续情报和个人上下文。',
    today: '今天',
    selecting: '选择中',
    scrollToLatest: '跳转到最新消息',
    historyTitle: '历史收集',
    menuTitle: '收集菜单',
    statusOrganizing: '正在整理',
    statusOrganizingLesson: '正在整理这节课…',
    statusUnderstood: '已理解',
    statusFailed: '失败',
    videoParsed: (count: number): string => `已解析 · ${count}句`,
    videoParseStale: '解析未完成，换个浏览器再试',
    selectedLabel: '已选',
    transcriptShow: '查看文字',
    transcriptHide: '收起文字',
    playAudio: '播放音频',
    pauseAudio: '暂停音频',
    composerPlaceholder: '发一句想法，贴个链接，或者先把这节课丢进来',
    composerPlaceholderQuotedMulti: '继续顺着这几条内容写...',
    composerPlaceholderQuotedSingle: (typeLabel: string): string => `继续顺着这条${typeLabel}写...`,
    filesReceived: (count: number): string => (count > 1 ? `${count} 个文件已收下` : '文件已收下'),
    confusionNudge: '我现在没懂的是：',
    topBarRecordingVoice: '正在收一段语音',
    topBarReceivingFiles: (count: number): string => `正在收进 ${count} 个文件`,
    voiceRecording: '语音录制中',
    voiceIdleHint: '继续说下去，停下后这段语音会直接留在这里。',
    echoUpdatedHint: '今日情报已根据你的收藏更新',
    // ── 收集菜单面板 ──
    menuSummary: (totalCount: number, activeDays: number): string => `已收 ${totalCount} 条 · 活跃 ${activeDays} 天`,
    menuStreakActive: (days: number): string => `已经连续 ${days} 天在收`,
    menuStreakIdle: '先从今天收一点开始',
    menuTopKinds: (kinds: string): string => `最近收得最多的是：${kinds}`,
    menuIdleHint: '一句困惑、一张图、一份讲义或一段录音，都可以先发进来。',
    menuAllCollectionsDesc: '从以前收进来的课、图和材料里继续接着学。',
    menuEchoActiveHint: '同学正在把你的收藏与目标连起来。',
    menuEchoIdleHint: '先继续收集，有根据的情报会自动出现。',
    activityKind: {
      audio: '录音',
      video: '视频',
      image: '图片',
      document: '材料',
      text: '想法',
    } as Record<string, string>,
    // ── 消息操作菜单 / 多选栏 ──
    actionGoReview: '去复习',
    actionQuote: '引用',
    actionSelect: '选择',
    actionDeselect: '取消选择',
    actionEdit: '编辑',
    actionOpenOriginal: '打开原件',
    actionArchive: '先收起',
    actionCancel: '取消',
    actionConfirmDelete: '确认删除',
    actionDelete: '删除',
    actionRemoveFromFlow: '删除这条',
    multiSelected: '已加入多选',
    selectionCount: (count: number): string => `${count} 条`,
    selectionHint: '已加入这次操作',
    selectionDeleteWarning: '再点一次删除，就会彻底移除这些内容。',
    exitSelection: '退出多选',
    // ── 引用上下文预览 ──
    quotedMulti: (count: number): string => `已引用 ${count} 条内容`,
    quotedAudio: '已引用一段录音',
    quotedSingle: (typeLabel: string): string => `已引用${typeLabel || '内容'}`,
    quotedAutoImport: '发送后自动解析',
    clearQuote: '取消引用',
    uploadFiles: '上传文件',
    dictationTitle: '说一段（备忘录式短录音——完整录一节课请到课堂 Tab）',
    dictationLabel: '说一段',
    sendToCollection: '发送到收集流',
    // ── 整理提示（pulse）：一句话 + 最多两个动作，安静出现在收集流顶部 ──
    pulse: {
      chipAudio: (count: number): string => `${count} 段课堂录音`,
      chipDocument: (count: number): string => `${count} 份材料`,
      chipImage: (count: number): string => `${count} 张图片材料`,
      chipText: (count: number): string => `${count} 条你的想法`,
      chipVideo: (count: number): string => `${count} 个视频来源`,
      recording: {
        title: '正在整理',
        body: '这段语音正在和前面的内容接到同一条学习线索里，你不用先整理它。',
      },
      primaryAndSupport: {
        title: '新的整理提示',
        body: '你已经把课堂录音和补充材料放进了同一条线索。后面不需要总结，继续轻轻往里加就行。',
        actions: [
          { key: 'continue-voice', label: '再录一段' },
          { key: 'capture-confusion', label: '补一句困惑' },
        ],
      },
      audioMany: {
        title: '新的整理提示',
        body: '你已经连续留下了几段课堂录音，这节课的主线开始显出来了。',
        actions: [
          { key: 'capture-confusion', label: '记下没懂的点' },
          { key: 'add-material', label: '贴一份讲义' },
        ],
      },
      audioAndText: {
        title: '新的整理提示',
        body: '你不只是在收课堂内容，也已经留下了自己的理解或困惑，这会让后面的同桌更有抓手。',
        actions: [
          { key: 'continue-voice', label: '继续录音' },
          { key: 'add-material', label: '补充材料' },
        ],
      },
      materialAdded: {
        title: '新的整理提示',
        body: '这份材料已经接进来了。后面再补一句当时没懂的地方，同桌会更容易看出联系。',
        actions: [
          { key: 'capture-confusion', label: '记下没懂的点' },
          { key: 'continue-voice', label: '录一段语音' },
        ],
      },
      audioAdded: {
        title: '新的整理提示',
        body: '这段录音已经留下来了。先别急着整理，继续往里丢材料或困惑，会更有价值。',
        actions: [
          { key: 'capture-confusion', label: '补一句困惑' },
          { key: 'add-material', label: '贴一份材料' },
        ],
      },
      fallback: {
        title: '新的整理提示',
        body: '这条收集流已经开始有自己的形状了。继续轻轻追加，不用一次说完整。',
        actions: [
          { key: 'continue-voice', label: '继续录音' },
          { key: 'capture-confusion', label: '写一句想法' },
        ],
      },
    },
  },

  login: {
    subtitle: '真正懂你在学什么的 AI 同学',
    guestCta: '先试听一节课',
    accountTab: '账号登录',
    emailLabel: '邮箱地址',
    emailPlaceholder: '请输入邮箱地址',
    passwordIdentifierLabel: '邮箱或管理员用户名',
    passwordIdentifierPlaceholder: '请输入邮箱或管理员用户名',
  },

  wechatAgent: {
    rateLimited: '今天聊得够多了，明天再接着聊。',
    failed: '这边卡了一下，稍后再跟我说一次。',
  },
  player: {
    loadingAudio: '加载音频',
    preparingWaveform: '原声已收下，正在准备波形…',
    loadFailed: '音频加载失败',
    loadFailedHint: '这段原声暂时无法播放，刷新页面或重新进入试试',
  },
  wechatQr: {
    loginAction: '微信扫码登录',
    inWechatAction: '微信登录',
    bindAction: '绑定微信',
    loginTitle: '微信扫码登录',
    bindTitle: '绑定微信账号',
    loginBody: '打开微信扫一扫，确认后这里会自动登录。',
    bindBody: '用要绑定的微信扫码，之后也可以直接用它登录。',
    loading: '正在准备二维码…',
    pending: '等待扫码',
    scanned: '已扫码，正在确认…',
    processing: '正在接上你的账号…',
    loginDone: '登录成功，正在进入 MeetMind…',
    bindDone: '微信已经绑定',
    expiresHint: '二维码 5 分钟内有效',
    expired: '二维码已过期，请刷新后再扫。',
    failed: '这次没有接上，请刷新后重试。',
    retry: '刷新二维码',
    close: '关闭',
    imageAlt: '微信扫码登录二维码',
    bindImageAlt: '微信账号绑定二维码',
    boundToast: '微信账号已绑定',
    mpConfirmed: '已确认，请回到电脑继续。',
    mpExpired: '二维码已过期，请回到电脑刷新后再试。',
    unavailable: '微信扫码登录暂时不可用',
    bindRequiresLogin: '请先登录再绑定微信',
    createFailed: '二维码没有生成，请稍后重试',
    tooManyRequests: '二维码刷新太频繁，请稍后再试',
    sessionMissing: '二维码会话不存在',
    pollFailed: '扫码状态没有接上，请重试',
    identityLinkFailed: '微信账号连接失败',
    identityConflict: '该微信已绑定其他账户',
    identityCreateFailed: '创建用户失败',
    bindFailed: '绑定失败，请重试',
    loginFailed: '登录失败，请重试',
  },

  loading: {
    preparing: '正在准备课堂空间',
    restoring: '正在接回你的学习现场',
    entering: '马上进入',
    fallback: '正在准备学习空间',
  },

  hero: {
    eyebrow: 'MEETMIND · AI 同学',
    title: '陪你听懂每一节课。',
    subtitle: '老师讲到哪，我就听到哪。卡住时当场问；下课后，每个答案都能回到原话。',
    sideHint: '先听 90 秒示例课',
    evidencePromise: '回答有依据，点击时间就能回到老师原话。',
    proofStatus: '正在一起听',
    proofQuote: 'The exact timing is still up in the air.',
    proofTime: '00:31',
    proofLabel: '同学听懂了',
    proofAnswer: '这里不是“在空中”，而是“具体时间还没有决定”。',
    proofAction: '进入这节示例课',
  },

  lesson: {
    summaryReady: '笔记总结',
    keyPoints: '重点',
    reviewed: '已复习',
    materials: (count: number): string => `${count} 份材料`,
    actionReady: '继续复习',
    actionReviewed: '再看一遍',
    actionProcessing: '整理中',
    actionFailed: '原声已保留',
    actionUpcoming: '准备上课',
  },

  classroomHome: {
    commandEyebrow: '今天',
    title: '今天，继续学懂一件事。',
    outcomeTitle: '内容进来之后',
    outcomeHint: '不只保存，还会继续变成能用的学习结果。',
    today: '今天',
    yesterday: '昨天',
    active: '正在上课',
    launchpadTitle: '补充学习上下文',
    launchpadHint: '材料和问题会自动接到相关课堂',
    actionRecordTitle: '开始一节课',
    actionRecordBody: '录线下课、网课或讨论，边听边形成课堂脉络。',
    actionRecordLabel: '选择声音开始',
    actionMaterialTitle: '放入材料',
    actionMaterialBody: '文档、网页、音视频会自动接到相关课堂和目标。',
    actionMaterialLabel: '选择文件或链接',
    actionSearchTitle: '问课堂和资料',
    actionSearchBody: '带上课堂、资料和目标，直接说你想弄懂什么。',
    actionSearchLabel: '搜索我的内容',
  },

  sourceType: {
    audio: '录音',
    video: '视频',
    image: '图片',
    document: '文章',
    text: '笔记',
  },

  sourceOrigin: {
    quickNote: '速记',
    wechat: '从微信发来',
    wechatArticle: '微信公众号',
    bilibili: '哔哩哔哩',
    youtube: 'YouTube',
  },

  sourceState: {
    extracting: '正在读取正文',
    complete: '正文完整',
    partial: '仅取得摘要',
    linkOnly: '已保存原链接',
    failed: '读取失败，原链接已保留',
  },

  sourceReader: {
    saved: '已收下',
    untitled: '未命名内容',
    openOriginal: '查看原文',
    noBody: '正文暂时没有读取出来，原始内容仍然保留。',
  },

  listening: {
    idle: '我在。',
    hearing: '我在听。',
  },

  classroomFlow: {
    eyebrow: '课堂脉络',
    listeningTitle: '等老师进入正题。',
    understanding: '正在接住刚才这段。',
    refreshing: '正在接住刚才这段',
    now: '正在讲',
    recent: '刚才怎么走到这里',
    recentHint: '只留与当前有关的推进',
    keep: '留到课后',
    mobileFlow: '脉络',
    mobileTranscript: '原话',
    kindDefinition: '定义',
    kindFormula: '公式',
    kindExample: '例子',
    kindQuestion: '待弄清',
    kindContrast: '对比',
    kindConclusion: '结论',
    kindOther: '值得回来',
  },

  stages: {
    /** v3.0：放弃假分阶段叙事，改为 Octo Buddy 听课的诚实表达
     *  app loading 文案根据 appName 动态拼，用 listening 系列 */
    reading: '正在读你的课堂',
    selecting: '正在挑核心',
    composing: '正在排版',
    slow: '稍等一下——内容多的时候我也要再想想',
    /** v3.0 新版 loading 文案 */
    listenStart: (appName: string): string => `在听这节课，给你${appName}`,
    listenSlow: '内容有点多，我多听一会儿',
    listenVerySlow: '还在听——再给我一点时间',
  },

  stop: {
    heard: '这节课我听完了。',
    /**
     * 停止后的总结一句话。
     * 例："共 47 句，标了 2 处你标的困惑。"
     */
    summary: (sentences: number, confusions: number): string => {
      if (sentences <= 0) return '这次只录到很少内容。';
      const base = `共 ${sentences} 句`;
      if (confusions > 0) return `${base}，标了 ${confusions} 处你标的困惑。`;
      return `${base}。`;
    },
    suggestCheatsheet: '要不要我整一张速查表？',
    actionMakeCheatsheet: '整速查表',
    actionViewTranscript: '看文字',
  },

  octoBuddy: {
    idle: '同学在这',
    listening: '陪你听课',
    thinking: '我想一下',
    happy: '接住了',
    surprised: '哎？',
    love: '我在',
    angry: '别一直戳我',
    sleeping: '待命中',
    openHint: '点开一起听',
    openPanel: '打开同学面板',
    dragHint: '单击逗我 · 双击打开同学 · 可拖动',
    hoverLine: '我看到你啦',
    patHappy: '嘿嘿，我在',
    patLove: '今天也一起学',
    patSurprised: '哎？轻一点',
    patAngry: '别一直戳我',
    wakeLine: '醒啦醒啦',
  },

  companion: {
    placeholderIdle: '问问同学…',
    placeholderListening: '老师刚说的那个啥意思？',
    shortcutHint: '有问题？⌘K 问同学',
    newCourseGreet: '我在这里。等你录第一节课，我就开始陪你。',
    defaultLightPrompts: ['刚才那句我没跟上', '这段在讲什么？', '帮我抓一下题眼'] as const,
    quickRecap: '刚才那段',
    quickRecapQuestion: '刚才那段讲了什么？',
    quickCatchUp: '我没跟上',
    quickCatchUpQuestion: '我没跟上，帮我接一下主线。',
    quickMark: '记一下',
    idleStatus: '待命中',
    afterClassStatus: '听完了',
    listeningStarter: '卡住直接问。',
    afterClassStarter: '听完了，换我带你练一下。',
    pending: '正在想…',
    emptyListeningPrimary: '我在听，有问题随时问我。',
    emptyListeningSecondary: '我会把刚才那段记住，你不用急着整理。',
    emptyIdlePrimary: '把第一节课录下来，我们就认识了。',
    actionPrompt: '也可以让我直接整理',
    contentPrompt: '已经有内容？试试',
    foresightCount: (count: number): string => `${count} 个预感`,
    foresightDismiss: '划掉',
    foresightAccept: '就这个 · 问下去',
    errorTitle: '同学刚刚没接上',
    errorBody: '只影响这次对话，你的课堂和复习内容都还在。',
    errorRetry: '重新连接',
  },

  recording: {
    sourcePrompt: '这节课的声音从哪里来？',
    backToLessons: '返回课程列表',
    sourceMic: '麦克风',
    sourceSystem: '电脑声音',
    sourceMixed: '两路都录',
    sourceMicHint: '线下课',
    sourceSystemShortHint: '在线课程',
    sourceMixedHint: '网课＋自己提问',
    sourceSystemHint: '开始后，在系统窗口勾选“分享音频”。',
    activeStatus: (source: string): string => `正在听 · ${source} · 点开看实时文字`,
    /** mixed 模式系统音频采集失败、降级为纯麦克风时提示 */
    downgradeFromMixed: '电脑声音没录到，只用麦克风在录',
    startFailedFallback: '没有接上录音设备，请检查麦克风权限后再试。',
    recorderNotReady: '录音组件还没准备好，请再点一次。',
    startFailed: (reason: string): string => `还没有开始录音。${reason}`,
    finished: '这节课收好了',
    finalizingTranscript: (count: number, enhancedCount = 0): string =>
      `实时文字已收下，正在用原声定稿 · ${count} 段${enhancedCount > 0 ? ` · 已优化 ${enhancedCount} 段` : ''}`,
  },

  mobileComposer: {
    placeholder: '发一句想法，贴个链接…',
    attach: '添加文件',
    send: '发送',
    startDictation: '开始语音听写',
    stopDictation: '停止语音听写',
    connecting: '正在连接麦克风…',
    listening: '我在听，说完再点一下',
  },

  mobileHome: {
    commandCenterLabel: '学习控制台',
    eyebrow: '今天，从这里开始',
    contextStatus: (count: number): string => count > 0
      ? `已接上 ${count} 段上下文`
      : '还没有上下文',
    title: '今天，学懂一件事。',
    record: '录一节课',
    recordHint: '实时听懂',
    addMaterial: '放入资料',
    photo: '拍板书',
    search: '问同学',
    livePromise: '课中看见脉络',
    afterClassPromise: '课后继续练习',
    capabilityLabel: '从输入到结果，一条学习链路',
    capabilityFlow: '课堂脉络',
    capabilityQa: '资料问答',
    capabilityFlashcards: '闪卡',
    capabilityQuiz: '测验',
    capabilityMindmap: '思维导图',
    capabilityFeed: '今日发现',
    intelligenceLabel: '今日发现',
    intelligenceFallback: '从最近的学习里，找到一条值得继续的线索',
    intelligenceAction: '查看',
    recentLabel: '最近收下',
    recentEmpty: '还没有收下的内容',
    openProfile: '打开个人菜单',
    emptyRole: '懂你上下文的 AI 同学',
    emptyEyebrow: '先交给我一段真实学习',
    emptyTitle: '陪你听懂每一节课。',
    emptyBody: '录下学习现场，课中理清脉络，课后继续练会。',
    emptyRecordHint: '边听边形成课堂脉络',
    tryDemo: '试听 90 秒',
    demoPlay: '播放声音',
    demoPause: '暂停',
    demoFinished: '试听结束，可以去看课后练习了',
    demoFinish: '结束试听，看课后',
    demoReviewStatus: '试听课',
    demoFailed: '试听还没加载好，再试一次',
    emptyOutcomeTitle: '回来时，你会得到',
    emptyOutcomeFlow: '课堂脉络',
    emptyOutcomeAnswer: '有根解释',
    emptyOutcomePractice: '课后练习',
    emptyBrowse: '先看看完整工作台',
  },

  reviewTutor: {
    wholeLesson: '整节课',
    wholeLessonTitle: '基于整节课内容对话',
    confusion: '困惑点',
    backToWholeLesson: '返回整节课对话',
  },

  echoShare: {
    title: '分享这条笔记',
    open: '分享',
    generating: '正在做图片…',
    error: '图片没做出来，再试一次',
    close: '关闭',
    imageAlt: '课堂笔记分享图',
    saveImage: '保存图片',
    nativeShare: '分享给同学',
    sharing: '分享中…',
    copyText: '复制文案',
    saved: '图片已保存',
    copied: '文案已复制',
    copyFailed: '没复制上，请手动保存图片',
    saveFallback: '没保存上，请长按图片保存',
    hint: '也可以长按图片保存',
  },

  flashcardsShare: {
    title: 'MeetMind 试听课闪卡',
    open: '分享试听成果',
    sharing: '分享中…',
    copied: '成果文案已复制',
    failed: '没分享出去，请手动复制',
    summaryTitle: '这节试听课已经变成闪卡',
    summaryBody: (count: number): string => `MeetMind 已经把它整理成 ${count} 张可练习的闪卡。`,
  },

  apps: {
    inlineSource: '已放进对话',
    placeholder: {
      defaultAppName: '应用内容',
      workingElapsed: (seconds: number): string => `同学正在整理 · ${seconds.toString().padStart(2, '0')}s`,
      emptyTitle: (appName: string): string => `还没有${appName}`,
      emptyBody: (appName: string): string => `回到应用目录开始整理${appName}，完成后会直接出现在这里。`,
      remake: '再做一版',
      back: '返回应用',
      failedTitle: (appName: string): string => `${appName}刚才没做好`,
      failedBody: '网络可能有点慢，原课堂内容没有受到影响。',
      retry: '再试一次',
      tryAnother: '看看其他方式',
    },
    matrix: {
      eyebrow: '基于这节课',
      title: '接下来怎么学',
      subtitle: '先选一个当下最需要的动作。同学会在后台做好，你可以留在这里继续看。',
      recommendedTitle: '现在最适合',
      recommendedHint: '根据这节课的内容和你留下的标记排序，不替你做决定。',
      allTitle: '其他学习方式',
      availableTitle: '可以这样继续',
      previewTitle: '其他内容可以这样学',
      readinessLabel: '学习应用判断',
      assessing: '正在判断这段内容适合怎么学',
      recommendedByContent: '这段内容已经足以支撑这个学习动作。',
      insufficientTitle: '先保留这段原话',
      insufficientBody: '内容还太少。继续记录后，合适的学习方式会自然出现。',
      notLearningTitle: '这段内容不用加工',
      notLearningBody: '它更像普通交流，保留原话就够了。',
      unreliableTitle: '先把原话听清',
      unreliableBody: '当前转录还不稳定，暂时不把它整理成学习结论。',
      executeNotReady: '这段内容还不足以形成可靠的学习应用。',
      executeNotSuitable: '这个学习动作不适合当前内容，换一种方式更可靠。',
      executeNeedsMultipleLessons: '至少选择两节属于同一门课的课堂。',
      noContent: '先录下或放入一段课堂内容。',
      generateFailed: '这次没做好，稍后可以再试一次。',
      generated: (appName: string): string => `${appName}做好了`,
      openResult: '打开',
      timeout: '等得有点久，稍后可以再试一次。',
      timeoutFor: (appName: string): string => `${appName}还没做好，稍后可以再试一次`,
      cancelled: '已取消',
      cancelledFor: (appName: string): string => `已取消${appName}`,
      failedFor: (appName: string): string => `${appName}这次没做好`,
      contextBasis: (segments: number, anchors: number, difficulties: number): string => {
        const parts = [`${segments} 段课堂内容`];
        if (anchors > 0) parts.push(`${anchors} 处标记`);
        if (difficulties > 0) parts.push(`${difficulties} 个难点`);
        return parts.join(' · ');
      },
      summary: (total: number, done: number, running: number, failed: number): string => (
        `${total} 种学习方式 · 已做好 ${done}${running > 0 ? ` · 正在做 ${running}` : ''}${failed > 0 ? ` · 待处理 ${failed}` : ''}`
      ),
      recommendedForConfusion: (count: number): string => `你留下了 ${count} 处标记，先检验能不能讲清楚。`,
      recommendedForDifficulty: (count: number): string => `这节课有 ${count} 个难点，先把关键概念练到能回忆。`,
      recommendedForStructure: '这节课内容较长，先看清主干和分支。',
      recommendedDefault: '先把这节课压成一页，最快建立整体印象。',
      start: '先做一版',
      open: '继续使用',
      openImage: '查看图片',
      progress: '查看进度',
      retry: '再试一次',
      tryAnother: '看看其他方式',
      remake: '再做一版',
      ready: '做好了',
      waiting: '待开始',
      notAvailable: '暂不可用',
      failed: '没做好',
      running: '正在做',
      workingOn: (action: string): string => `${action}，可以先返回继续看这节课`,
      failedWithoutLoss: '这次没做好，原课堂内容没有受到影响。',
      recommended: '适合现在',
      taskTray: '学习内容',
      taskPanelTitle: '正在准备与已经做好的内容',
      taskRunning: (count: number): string => `正在做 ${count}`,
      taskDone: (count: number): string => `已做好 ${count}`,
      taskNeedsAttention: (count: number): string => `待处理 ${count}`,
      collapse: '收起',
      cancel: '取消',
      noTasks: '还没有正在准备的内容。',
      infographicPreview: '信息图预览',
      downloadImage: '保存图片',
      closePreview: '关闭',
      imageDownloaded: '图片已保存',
      imageDownloadFailed: '没保存上，请长按图片保存',
      windowUnavailableTitle: '这个学习方式暂时打不开',
      windowUnavailableBody: '回到这节课，其他学习方式仍然可以继续使用。',
      windowLoading: '正在接回这节课',
      windowEmptyTitle: '先选一节课',
      windowEmptyBody: '学习应用需要基于真实课堂内容，才不会生成没有依据的结论。',
      windowBackToClassroom: '回到课堂',
      windowErrorTitle: '这次没有接上',
      windowErrorBody: '课堂原文仍然保留着，回到学习方式后可以再试一次。',
      windowLoadTimeout: '这节课暂时没有接上，请返回后再试一次。',
      windowLoadFailed: '这节课暂时没有接上',
      courseCheatsheetSection: '跨课准备',
      courseCheatsheetTitle: '考试速查表',
      courseCheatsheetBody: '从课程上下文选择多节课堂、考试范围与资料，做成真正能打印和带进考场的速查表。',
      courseCheatsheetAction: '选择课程范围',
      courseCheatsheetRouteTitle: '考试速查表从多节课开始',
      courseCheatsheetRouteBody: '先选择一门课程和至少两节课堂；MeetMind 会把课堂、课件与考试范围合成一份可编辑、可打印的速查表。',
      mobileTitle: '这节课，接下来怎么学',
      mobileSubtitle: '选一种学习动作，同学会直接基于这节课开始。',
      backToMatrix: '所有学习方式',
      workspaceSubtitle: (action: string, bestFor: string): string => `${action} · ${bestFor}`,
      catalogMeta: {
        cheatsheet: { action: '带进考场', bestFor: '多节课已组成单元，或正在准备允许携带资料的考试', time: '排版约 10–20 分钟' },
        quiz: { action: '检验理解', bestFor: '想知道自己是真懂，还是只是看懂了', time: '作答约 5–8 分钟' },
        flashcards: { action: '记住核心', bestFor: '概念、术语和公式需要反复回忆', time: '练习约 5 分钟' },
        mindmap: { action: '看清结构', bestFor: '内容较多，想分清主干、关系和层次', time: '浏览约 2 分钟' },
        'audio-overview': { action: '换种方式再听', bestFor: '通勤或走路时，想用对话重新理解', time: '收听约 6–10 分钟' },
        infographic: { action: '做成一张图', bestFor: '想分享、展示，或用视觉方式记住', time: '查看约 2 分钟' },
        'teach-back': { action: '讲给同桌听', bestFor: '想确认自己是真懂，而不只是看懂了', time: '讲约 5–10 分钟' },
      },
    },
    infographic: {
      appName: '课堂信息图',
      preparing: '正在把这节课变成一张图',
      preparingHint: '完成后会直接显示成品。',
      finished: '做好了',
      fit: '看全图',
      full: '看细节',
      save: '保存图片',
      adjust: '调整',
      createTitle: '把这节课变成一张图',
      createHint: '选尺寸和感觉，其他交给同学。',
      adjustTitle: '想换一种呈现？',
      adjustHint: '只改你在意的部分，其余交给同学。',
      orientation: '尺寸',
      style: '视觉感觉',
      custom: '还想强调什么',
      customPlaceholder: '例如：突出 3 个结论，适合手机查看',
      generate: '生成信息图',
      regenerate: '按这个方向重做',
      serviceUnavailable: '图片服务暂时不可用',
      serviceUnavailableBody: '课堂内容和草案已经保留，稍后再试即可。',
      downloaded: '图片已保存',
      downloadFailed: '没保存上，请长按图片保存',
      missingContext: '当前内容还不足以生成可靠的信息图。',
      generateFailed: '这次没有生成成功，课堂内容仍然保留着。',
      readableReady: '先给你一张可读版',
      readableHint: '图片还没做好，课堂重点不用跟着等。',
      copyReadable: '复制要点',
      readableCopied: '要点已复制',
      readableCopyFailed: '没复制上，可以长按选择文字。',
      retryImage: '再试一次图片',
    },
    teachBack: {
      appName: '讲给同桌听',
      targetsTitle: '这节课，挑几点讲出来',
      targetsSubtitle: '能讲出来的，才是真的懂。',
      evidenceLabel: '课堂依据',
      startVoice: '走上讲台',
      startText: '打字讲',
      voiceHint: '同桌安静听你讲，只在跟不上或你有没讲到的点时开口。',
      textTitle: '用自己的话讲一遍',
      textPlaceholder: '就像讲给一个没听过这节课的同学……',
      finishText: '讲完了',
      evaluating: '同桌正在对照课堂原声核对你讲的……',
      evaluatingStage2: '正在逐条核对你讲的和课堂原声……',
      evaluatingStage3: '就快好了，同桌在写核对结论……',
      evalRateLimited: '刚才操作太频繁了，喝口水，等一小会儿再试。',
      reteachPoint: '就这点再讲一次',
      yourTeachingStats: (chars: number): string => `你讲的约 ${chars} 字都还在，不用重讲。`,
      resultTitle: '讲得怎么样',
      quadrantMastery: '讲透了',
      quadrantStruggle: '挣扎着讲通了',
      quadrantGap: '自己知道卡住了',
      quadrantBlindSpot: '盲区',
      quadrantUncovered: '还没讲到',
      blindSpotHint: '讲的时候很顺，但和课堂内容对不上。',
      backToEvidence: '回到课堂原声',
      retry: '再讲一次',
      backToTargets: '回到目标',
      emptyBody: '这节课的内容还太少，等录得更久一点再来讲。',
      callContextLabel: '讲课中',
      endCall: '讲完了',
      switchToText: '改为打字',
      classroomWaiting: '开始讲吧，我们在听。',
      classroomReconnect: '连接断了，点这里重新进教室',
      evalFailed: '这次没能完成核对，你讲的内容还在，可以再试一次。',
      retryEval: '重新核对',
    },
    mindmap: {
      mobileGestureHint: '拖动查看 · 点 + 放大',
      desktopGestureHint: '滚轮缩放 · 拖拽平移',
    },
    flashcards: {
      appName: '闪卡训练',
      completeTitle: '这一轮完成了',
      roundSummary: (count: number): string => `共回忆 ${count} 张`,
      recallRate: '本轮记住',
      got: '记住了',
      missed: '再来一次',
      gotCount: '记住了',
      missedCount: '还要练',
      reviewMissed: (count: number): string => `只练没记住的 ${count} 张`,
      restart: '重练全部',
      reveal: '想好后翻面',
      answer: '参考答案',
      showHint: '看一点提示',
      recallFirst: '先在心里回答，再翻面看答案',
      keyboardHint: '空格翻面 · 方向键切换',
      previous: '上一张',
      next: '下一张',
      evidenceAt: (time: string): string => `来自课堂 ${time}`,
      returnToEvidenceAt: (time: string): string => `回到课堂 ${time}`,
    },
    quiz: {
      appName: '课堂测验',
      keyboardHint: '方向键切换题目',
      previous: '上一题',
      next: '下一题',
      jumpTo: (index: number): string => `跳到第 ${index} 题`,
      answered: (done: number, total: number): string => `${done} / ${total} 已完成`,
      understood: '答稳了',
      revisit: '再看看',
      subjectivePrompt: '先在心里说出答案，再对照参考。',
      referenceAnswer: '参考答案',
      referenceFallback: '回到原片段核对关键内容。',
      selfRate: '对照后，我：',
      selfCorrect: '答到要点',
      selfWrong: '还没答上',
      correct: '答对了',
      wrong: '再看看',
      correctAnswer: (answer: string): string => `答案：${answer}`,
      revealReference: '对照答案',
      confirmAnswer: '确认答案',
      nextQuestion: '下一题',
      viewResult: '看这一轮',
      completeTitle: '这一轮检验完成',
      completeMeta: (count: number, minutes: string): string => `共 ${count} 题 · 用时 ${minutes} 分钟`,
      recallRate: '本轮答稳',
      solidCount: '答稳了',
      revisitCount: '还要回看',
      missedReview: '需要回看的题',
      reviewMissed: (count: number): string => `只练需要回看的 ${count} 题`,
      restart: '重做全部',
      evidenceAt: (time: string): string => `来自课堂 ${time}`,
      returnToEvidenceAt: (time: string): string => `回到课堂 ${time}`,
    },
    podcast: {
      appName: '课堂播客',
      emptyBody: '开始整理后，会直接得到一版可以播放的课堂播客。',
      scriptCopied: '脚本已复制',
      copyFailed: '复制失败，请手动选择脚本内容',
      details: '脚本与章节',
      script: '播客脚本',
      copyScript: '复制脚本',
      chapter: (index: number): string => `章节 ${index}`,
      chapterEmpty: '这一章暂时没有摘要。',
      seekChapter: '回到课堂片段',
      audioGenerating: '正在准备音频',
      audioRetry: '音频没做好，点这里再试一次',
      audioGeneratingHint: '完成后这里会直接变成播放条。',
      audioRetryHint: '脚本已经保留，不需要重新来过。',
      audioRetryNoScriptHint: '课堂内容仍然保留，稍后可以直接再试。',
      activityAudioReady: '课堂播客已经可以播放，并保留了脚本与章节。',
      activityScriptReady: '音频还没做好，播客脚本与章节已经保留。',
      generating: '正在准备',
      retry: '再试一次',
    },
    cheatsheet: {
      appName: '考试速查表',
      emptyBody: '当前内容还不足以整理成可靠的速查表。继续记录后再回来看看。',
      focus: '重点',
      focusCount: (count: number): string => `重点 ${count}`,
      focusTitle: '课堂、大纲或真题明确强调的内容',
      hideItem: '暂时移除这条',
      expand: '展开',
      collapse: '收起，不放进打印页',
      removedCount: (count: number): string => `已移除 ${count} 条`,
      removedTitle: (count: number): string => `${count} 条已移除`,
      collapsedCount: (count: number): string => `已收起 · ${count} 条`,
      sectionCount: (sections: number, items: number): string => `${sections} 区 · ${items} 条`,
      itemCount: (count: number): string => `${count} 条`,
      sourcesLabel: '来源',
      copied: '已复制',
      pageTotal: (count: number): string => `共 ${count} 页`,
      copyMarkdown: '复制文字',
      print: '打印 / 导出 PDF',
      copyTitle: '复制文字，便于粘贴到笔记或发给同学',
      printTitle: '按 A4 纵向三栏打印或导出 PDF',
      allRemoved: '内容已全部移除，可以恢复后继续整理。',
      pageNumber: (current: number, total: number): string => `${current} / ${total}`,
      page: '页面',
      mono: '黑白',
      color: '彩色',
      editItem: '编辑这条',
      editShort: '编辑',
      hideShort: '不打印',
      itemActions: '调整这条内容',
      mobileCopy: '复制',
      mobilePrint: '打印 / PDF',
      editTerm: '术语',
      editBody: '解释',
      editFormula: '公式（可留空）',
      cancelEdit: '取消',
      saveEdit: '保存',
      syllabusSource: '考试大纲',
      pastPaperSource: (index: number): string => `真题 ${index}`,
    },
  },

  /**
   * 信息流（M15：替换笔记总结）
   * 基于个人上下文的 LLM 驱动信息流——同一节课不同人看到不同的内容。
   */
  feed: {
    /** tab 标签（单课复习态遗留，跨课程信息流改走侧栏抽屉） */
    tabLabel: '信息流',
    /** 侧栏「收集 → 相关信息」子导航文案 */
    relatedInfoLabel: '今日情报',
    /** 抽屉标题——替换原「笔记总结」 */
    drawerTitle: '今日情报',
    drawerSubtitle: '一半照见你正在关心的事，一半把真实的书、论文和新观点带进来。',
    todayBrief: '看见自己',
    internalDiscoveries: '看见自己',
    internalDiscoveriesHint: '从你的收藏、笔记和目标里，找到正在形成的方向。',
    externalDiscoveries: '向外看看',
    externalDiscoveriesHint: '真实来源，可直接打开；既有顺着目标深入，也有不同视角。',
    useful: '有用',
    notRelevant: '不相关',
    feedbackUseful: '已记下，以后多找这类内容',
    feedbackDismissed: '已减少这类推荐',
    refresh: '更新',
    addContext: '补一条线索',
    refreshing: '正在寻找与你有关的新内容',
    notGeneratedYet: '等待第一次发现',
    updatedJustNow: '刚刚更新',
    updatedMinutesAgo: (minutes: number): string => `${minutes} 分钟前更新`,
    updatedAt: (time: string): string => `今日 ${time} 更新`,
    refreshFailedKeepingPrevious: '这次没更新成，先保留上一版。',
    contextBasis: (captures: number, goals: number): string => (
      goals > 0 ? `基于 ${captures} 条收藏 · ${goals} 个当前目标` : `基于 ${captures} 条收藏`
    ),
    sourceCount: (count: number): string => `来自 ${count} 条收藏`,
    goalAlignment: (goal: string): string => `对齐目标「${goal}」`,
    /** 生成中（跨课程） */
    loading: '同学正在查找真实的书、论文和外部资料…',
    /** 空状态（没有收集内容） */
    empty: '还没有收集内容。先去收一节课或一篇文章，同学会自动整理方向。',
    /** 跨课程空态 */
    crossCourseEmptyTitle: '先留下几条你真正关心的内容。',
    crossCourseEmptyBody: '这里会先看见你正在形成的方向，再从外部找到真实可读的书、论文和不同观点。',
    /** 生成失败 */
    error: '没整理出来，再试一次',
    /** 重试按钮 */
    retry: '重新整理',
    /** 条目类型标签 */
    typeSummary: '你最近在意的',
    typeProbeNear: '同主题',
    typeProbeLateral: '相关方向',
    typeProbeBridge: '跨界',
    typeConfusionLink: '你标记的困惑',
    typeWebRecommend: '外部发现',
    typeBiliRecommend: '同学帮你找的',
    typeEcho: '同桌沉淀',
    /** echo 卡分享按钮 */
    shareEcho: '分享',
    /** 动作按钮 */
    actionJumpTimestamp: '跳回去听',
    actionMakeFlashcard: '做成闪卡',
    actionAskTutor: '让同学解释',
    actionReviewPrev: '看上节课',
    actionOpenCapture: '看这条收集',
    actionOpenExternal: '打开原文',
    actionOpenBilibili: '在 B站看',
    /** whyForYou 前缀 */
    whyPrefix: '为什么与你有关',
    differentPerspectivePrefix: '为什么值得换个角度',
    kindWeb: '文章',
    kindPaper: '论文',
    kindBook: '书籍',
    kindReport: '研究报告',
    perspectiveDeepen: '顺着目标深入',
    perspectiveAdjacent: '相邻视角',
    perspectiveCounterpoint: '不同视角',
    unknownAuthor: '作者未标注',
  },

  /**
   * 「聊聊你想要的」—— 用户和 AI 教练对话梳理目标的入口。
   * 是 v3.0 信息流哲学落地的第一个产品入口（替代旧硬编码 LearnerOnboarding 表单）。
   * 设置页常驻 + 首次进入 app 自动弹出。
   */
  intent: {
    /** 主标题（设置页 caption / 首次进入 header） */
    title: '聊聊你想要的',
    /** 副标 */
    subtitle: '不用写好——说就行',
    /** 设置页 description */
    description: '和教练聊一聊，把脑子里的事一起捋清楚——也可以打电话语音聊',
    /** 设置页：还没聊过的提示 */
    emptyHint: '还没聊过。你最近想做的事 / 想去的方向 / 还在纠结的选择，都可以慢慢说。',
    /** 设置页：开始按钮 */
    actionStart: '和教练聊一聊',
    /** 设置页：再聊一次按钮 */
    actionResume: '和教练再聊一会',
    /** IntentDialog header：右上角切换通话 */
    switchToCall: '打电话聊',
    /** 通话视图：切回文字 */
    switchToText: '文字',
    /** 通话视图：标题 */
    callTitle: '在听你说',
    /** 通话视图：底部状态行（基于 useOmniRealtimeCall.status） */
    callStatusListening: '我在听你说…',
    callStatusThinking: '我想一下…',
    callStatusResponding: '我在说…',
    callStatusMuted: '已静音 · 我还在',
    callStatusConnected: '直接说就好',
    callStatusConnecting: '正在接通…',
    callStatusAuthorizing: '点下面按钮开始',
    callStatusError: '没接通，点重连',
    callStatusPreparing: '准备中…',
    /** 输入条：占位符 */
    inputPlaceholder: '说说你最近想做的事',
    inputPlaceholderBusy: '同学正在听…',
    /** 首次进入：跳过文案 */
    firstTimeSkip: '先不聊，下次再说',
    /** 开场提示——已有 N 个目标时 */
    greetingWithGoals: (count: number): string =>
      `欢迎回来。你之前留下了 ${count} 件想做的事——是想聊聊新的，还是更新一下旧的？`,
    /** 开场提示——首次 */
    greetingFirstTime:
      '不急。你现在脑子里有什么想做、想去、想搞清楚的事？哪怕还没完全想明白，也可以慢慢说。',
    /** 卡片：标题（"我听到的是"） */
    summaryEyebrow: '我听到的是',
    /** 卡片：先放放 */
    summaryDismiss: '先放放',
    /** 卡片：就是这样（保存） */
    summaryAccept: '就是这样',
    /** 卡片：保存中 */
    summarySaving: '记着…',
    /** 卡片：已保存 */
    summarySaved: '已记下了',
  },

  realtime: {
    defaultTitle: '语音同桌',
    defaultContext: '整节课',
    disabled: '先收一条课堂内容',
    reconnect: '没接通，点重连',
    connecting: '正在接通…',
    authorizing: '点下面按钮开始',
    muted: '已静音 · 我还在',
    listening: '我在听你说…',
    thinking: '我想一下…',
    responding: '我在说…',
    connected: '已接通 · 直接说',
    preparing: '准备中…',
    transcriptTitle: '本轮对话文字',
    assistantLabel: '同学',
    userLabel: '你',
    emptyTranscript: '还没有对话内容',
    showText: '查看文字',
    reconnectAction: '重连',
    collapse: '收起',
    dialing: '接通中',
    start: '开始',
    unmute: '开麦',
    mute: '静音',
    endCall: '结束通话',
  },

  mobileJourney: {
    playAudio: '播放原声',
    pauseAudio: '暂停原声',
    finishLesson: '结束这节课',
    photoCapturedAt: (timestamp: string): string => `已拍下板书 · ${timestamp}`,
    collapseClassmate: '收起课堂同桌',
    processingEyebrow: '正在整理',
    processingTitleLead: '把这节课',
    processingTitleAccent: '听懂',
    waitingTranscript: '等待转录完成…',
    readingTranscript: '正在读转录原文…',
    buildingNotes: '正在生成分段笔记…',
    processingDone: '整理完成',
    noSpeechStatus: '没有听到可整理的内容',
    processingEstimate: '约 1 分钟',
    waiting: '等待中…',
    done: '完成',
    leaveWhileProcessing: '先回首页',
    openNotes: '笔记整理好了，去看看 →',
    understood: '已理解',
    originalPreserved: '原声已保留',
    restoringTranscript: '正在恢复这节课的转录内容…',
    noSpeechTitle: '这段录音里没有识别到语音',
    noSpeechBody: '可能是录音太短或声音太小。原声已保留，可以返回首页稍后再看。',
    backHome: '返回首页',
  },

  help: {
    classroomRecordingAnswer: '录课中 MeetMind 会实时展示：\n\n- 实时原话：老师说的内容会跟着出现\n- 课堂脉络：告诉你现在讲到哪里、刚才如何推进、什么值得课后回来\n- 同学：有问题随时可以问，它会带着刚才的课堂上下文回答\n\n这些都会自动完成。思维导图、闪卡和测验会在课后应用中生成，不会在上课时抢走注意力。',
  },

  /**
   * v3.0 SharedAgent —— 分享 Agent 的落地页 / 分享卡 / 创建对话框文案
   * 见 roadmap/v3.0-virality-agent.md。
   */
  share: {
    landing: {
      /** 落地页右下角极淡的访问计数 */
      viewCount: (count: number): string => `已被打开 ${count} 次`,
      /** 没登录访问者点"领取到我的工作台"时的引导 */
      claimNeedsLogin: '领取需要先登录，登录后这份内容就在你的工作台里了',
      claimGo: '去登录',
      /** 已登录领取按钮 */
      claimAction: '领取到我的工作台',
      claiming: '正在领取…',
      claimDone: '已领取，去工作台看看',
      claimRedirecting: '正在打开你的工作台…',
      claimAlready: '你之前已经领过这一份',
      claimSub: '领取后可以在自己的工作台里继续学',
      /** 领取接口异常的兜底文案 */
      claimFailed: '领取失败',
      /** 也分享给别人 */
      reshareAction: '复制链接',
      reshareFailed: '复制失败，请手动复制地址栏',
      /** 分享态对话输入占位符 */
      chatPlaceholder: '问问这节课…',
      /** 分享态对话：等待回答时的输入条占位 */
      chatBusyPlaceholder: '同学在想…',
      /** 分享态对话：空态卡后半句（接在 sharedBy 之后） */
      chatEmptyHint: '可以问我任何关于这节课的事。',
      /** 分享态对话顶栏状态 */
      chatStatusBusy: '在听',
      chatStatusReady: '就绪',
      /** 已撤销 / 已过期 */
      notFoundTitle: '这条分享暂时不可用',
      notFoundBody: '可能已被原作者撤回，或者链接打错了。',
      /** 404 态回首页链接 */
      backHome: '回 MeetMind 首页',
      /** 头部副标题：基于分享者昵称 */
      sharedBy: (nickname: string): string => `${nickname} 听完了这节课，留了一份给你`,
      /** 没有昵称兜底 */
      sharedByAnon: '一个同学听完了这节课，留了一份给你',
      /** 分享者昵称兜底（各处展示用） */
      sharerAnon: '一位同学',
      /** Octo 主图 alt */
      octoAlt: (nickname: string): string => `${nickname} 的学习同桌`,
      /** 凌晨加载态（Octo sleeping） */
      loadingSleeping: '夜深了 · 同学先打个盹',
      /** 转录摘要标题 */
      digestTitle: '这节课讲了什么',
      digestEmpty: '没附转录摘要，可以直接问同学这节课的事。',
      /** 转录摘要折叠提示：还有 N 段未展示 */
      digestMore: (count: number): string => `另 ${count} 段在同学的记忆里。`,
      /** 产物预览块标题（按 artifactKind 切换） */
      artifactTitle: (kind: string): string => {
        const map: Record<string, string> = {
          cheatsheet: '考前速查表',
          mindmap: '思维导图',
          quiz: '课堂测验',
          flashcards: '课堂闪卡',
          infographic: '课堂信息图',
          'audio-overview': '课堂播客',
          notes: '同学版笔记',
          'chat-only': '可以直接聊',
        };
        return map[kind] ?? '一份分享';
      },
    },
    creator: {
      doneCopy: '复制链接',
      doneCopied: '链接已复制',
      doneLinkCreated: '分享链接已生成',
      doneCopyFailed: '复制失败，请手动复制链接',
      doneCopying: '复制中...',
      fallbackTitle: '分享链接已生成',
      fallbackBody: '浏览器没有允许自动复制，可以直接复制下面的链接。',
      loginRequired: '先登录再分享',
      loginAction: '登录后继续',
      createFailed: '创建分享失败',
      currentAction: '分享',
      currentPreparing: '正在生成链接',
    },
  },

  adminAi: {
    managementView: '管理视图',
    managementViewEnabled: '已开启',
    managementViewDisabled: '未开启',
    managementViewHint: '开启后，AI 功能旁会显示本次实际输入与运行配置。普通用户不会看到。',
    inspector: '查看本次 AI',
    inspectorTitle: '查看这次回答接入了什么',
    inspectorPanelTitle: '本次 AI 输入',
    closeInspector: '关闭本次 AI 输入',
    inspecting: '正在重建本次输入…',
    inspectorFailed: '暂时无法读取这次 AI 输入，请进入控制中心重试。',
    requestModel: '请求模型',
    noContextReceived: '这次没有接入额外上下文',
    inspectorPrivacy: '输入只在当前浏览器用于这次检查，不写入运行日志。最终模型可能因服务异常自动切换备用通道。',
    tuneThisRun: '用这次输入去调整',
    settingsCaption: '管理员工具',
    openControlCenter: '打开 AI 控制中心',
    settingsDescription: '统一查看提示词、上下文拼接、模型路由和线上版本',
    title: 'AI 控制中心',
    subtitle: '看清每条 AI 链路的上下文、提示词与模型，并安全地发布调整。',
    back: '返回 MeetMind',
    accessDenied: '这里仅对管理员开放',
    accessDeniedBody: '请先使用管理员账号登录。',
    loading: '正在读取 AI 链路…',
    loadFailed: 'AI 配置读取失败，请稍后重试。',
    surfaces: 'AI 链路',
    online: '线上',
    baseline: '代码默认',
    draft: '草稿',
    version: (version: number): string => `v${version}`,
    noPublishedVersion: '尚未发布调整',
    entryPoints: '出现位置',
    contextMap: '输入上下文',
    sensitive: '含个人信息',
    editTitle: '调整这条链路',
    editBody: '保留代码内的基础提示词，只追加你希望改变的行为。',
    enabled: '启用这版调整',
    enabledHint: '关闭后仍可保存草稿，但发布不会改变线上行为。',
    model: '运行模型',
    modelAuto: '沿用产品默认',
    instructions: '追加指令',
    instructionsPlaceholder: '例如：回答概念问题时，先用一个贴近课堂的小例子，再给定义。',
    note: '版本备注',
    notePlaceholder: '这次为什么调整',
    saveDraft: '保存草稿',
    saving: '保存中…',
    publish: '发布到线上',
    publishing: '发布中…',
    publishConfirm: '确认把这版配置发布给所有用户？发布后仍可从版本记录回滚。',
    saved: '草稿已保存',
    published: '已发布，新请求会使用这版配置',
    rolledBack: '已回滚并生成一个新的线上版本',
    actionFailed: '操作失败，请检查内容后重试。',
    previewTitle: '用一次真实输入预演',
    previewBody: '可以直接编辑这次送给模型的上下文样例，不会触发真实回答，也不会影响线上。',
    liveContext: '来自刚才的产品现场',
    sampleContext: '产品样例',
    contextJson: '上下文 JSON',
    optionsJson: '运行选项',
    invalidJson: '上下文不是有效的 JSON。',
    preview: '生成最终输入',
    previewing: '正在拼接…',
    previewEmpty: '生成预览后，这里会显示模型最终收到的系统输入。',
    finalInput: '最终系统输入',
    promptVersion: '基础提示词版本',
    characterCount: (count: number): string => `${count.toLocaleString('zh-CN')} 字符`,
    contextReceived: '实际接入字段',
    lockedContract: '不可覆盖的产品合同',
    lockedHint: '隐私、引用与场景边界始终放在管理员指令之后。',
    compareTitle: '回答对比',
    compareBody: '用同一份上下文和问题，对比当前线上配置与正在编辑的配置。试跑不会写入用户对话。',
    trialQuery: '测试问题',
    trialQueryPlaceholder: '输入一条真实用户会问的问题',
    trialQueryRequired: '先输入一条测试问题。',
    runCompare: '试跑两版回答',
    comparing: '两版同时生成中…',
    compareFailed: '回答试跑失败，请检查模型配置后重试。',
    currentOnline: '当前线上',
    currentEdit: '正在编辑',
    compareEmpty: '试跑后在这里直接比较用户会看到的回答。',
    duration: (durationMs: number): string => `${(durationMs / 1000).toFixed(1)} 秒`,
    history: '版本记录',
    rollback: '回滚到这版',
    rollbackConfirm: (version: number): string => `确认回滚到 v${version}？系统会生成一个新的线上版本。`,
    emptyHistory: '还没有版本记录。',
  },

  /**
   * "被禁用"的词表——供测试脚本 grep 校验，确保面向用户的字符串不退化。
   */
  bannedWords: ['回声卡', '酿', '预知气泡', '工坊', '研判', '引擎'] as const,
};

export type Copy = typeof COPY;
