export const sharedContextCopy = {
    title: '学习留下的你', subtitle: '我的共享上下文',
    intro: '每一段经历，都让下一次学习更了解你。这里的理解会变化，依据始终可以打开。',
    portraitHeading: '此刻，对你的理解', portraitHint: '从获准经历中检索的当前视图，并非对你的完整判断。',
    portraitEmpty: '我们还在认识你', portraitEmptyBody: '留下第一段经历，或继续在应用里学习。有了可追溯的理解，它会出现在这里。',
    portraitLoading: '正在连接你的学习经历…', portraitUnavailable: '暂时读不到理解，已保存的经历仍在下方。',
    portraitPending: '新的经历还在整理，稍后刷新可以查看。',
    connections: '理解来自这些经历', timelineHint: '按时间保留变化，点开查看完整原文。',
    moreUnderstanding: (count: number) => `展开另外 ${count} 条理解`, memoryDetail: '完整表述与附注',
    latestUnderstanding: '最近的经历带来的理解', earlierUnderstanding: '此前经历中的理解',
    settings: '空间与应用连接', inspect: '打开原文', supplement: '补充或更新我的情况',
    supplementHint: '新情况会作为一段自述保存，不会直接覆盖旧理解；明确不再适用的旧经历，可以暂停参考。',
    spaceApply: '切换空间', originalHint: '原始记录，尚不等于模型的理解',
    back: '回到学习', login: '登录后查看自己的上下文', guestDemo: '还没有账号？先试听一节课 →',
    guestTryBody: '带着这次想做的事来，系统先翻出可参考的经历与理解，再动手。', loading: '正在读取…', refresh: '刷新',
    portraitTitle: '你的学习现场，正在这里连起来', portraitBody: '这些是应用实际收下的经历，不是给你贴上的标签。你可以查看依据，也可以随时暂停或忘记。',
    portraitEvents: '段经历', portraitActive: '仍可参考', portraitApps: '个应用', portraitTrail: '最近留下的轨迹', portraitNoTrail: '还没有跨应用轨迹。',
    addTitle: '补充一段经历', addBody: '告诉系统一件真实发生的事，之后的应用才有机会接着它工作。',
    space: '上下文空间', note: '记下一段经历', notePlaceholder: '最近在学什么，哪里卡住了，或者你希望下次记住的事。',
    save: '收下这段经历', history: '你的学习轨迹', empty: '还没有经历。可以先补充一件真实发生的事。',
    pause: '暂停参考', resume: '恢复参考', forget: '忘记', forgotten: '这段经历的原文已移除。',
    forgetQuestion: '忘记这段经历？原文会移除，依赖它的理解会停止被参考。',
    more: '更早的经历', status: {
      queued: '已收下，等待整理', submitted: '正在整理', completed: '处理完成', retrying: '稍后重试', failed: '整理未完成',
      active: '可以参考', paused: '已暂停参考', forgotten: '已忘记',
    },
    tryTitle: '下一次，系统能用上什么', task: '这次想做的事', taskPlaceholder: '例如：帮我安排一次条件概率练习',
    prepare: '看看可参考的上下文', memories: '从经历中形成的理解', originals: '可参考的原始观察',
    cleaning: '已停止参考，后台正在清理关联记录。', closeSource: '收起原文',
    noMemories: '这次没有检索到有完整来源的理解。',
    degraded: '记忆服务暂未就绪。下面只显示已保存的原始观察。',
    sources: '查看依据', developers: '应用连接', developerIntro: '把指定空间授权给另一个应用。默认只读，有效期为 7 天；随时可以撤销。',
    appId: '应用标识', allowWrite: '也允许这个应用写入经历', createGrant: '创建应用凭证',
    tokenNotice: '凭证只显示这一次。交给你信任的应用服务端保存。', dismiss: '我已保存',
    revoke: '撤销授权', revoked: '已撤销', expires: '到期', noGrants: '还没有连接其他应用。',
    errors: {
      cleanup_in_progress: '后台正在移除旧的引用，完成后就能恢复。请稍后刷新。',
      idempotency_conflict: '这次记录与先前的请求不一致，请重新发起。',
      unauthorized: '登录已失效，请重新登录。', invalid_input: '请检查内容和空间标识是否完整。',
      scope_denied: '当前应用没有这个空间的访问权限。',
    } as Record<string, string>,
    error: '这次操作没有完成，内容仍在输入框里，可以重试。',
  };
