export type ServiceActionAtomType = 'perception' | 'judgment' | 'interaction' | 'action' | 'evaluation';
export type ServiceActionAtomStatus = 'live' | 'internal' | 'planned';
export type ServiceActionCapabilityType = 'agent-tool' | 'ui-tool' | 'platform-service' | 'skill-pattern';

export interface ServiceActionAtom {
  id: string;
  name: string;
  toolName?: string;
  atomType: ServiceActionAtomType;
  status: ServiceActionAtomStatus;
  capabilityType: ServiceActionCapabilityType;
  serviceAction: string;
  description: string;
  owner: string;
  inputState: string;
  outputArtifact: string;
  userVisibleResult: string;
  evalCriteria: string[];
}

export const ATOM_TYPE_ORDER: ServiceActionAtomType[] = ['perception', 'judgment', 'interaction', 'action', 'evaluation'];

export const ATOM_TYPE_META: Record<ServiceActionAtomType, { label: string; loopLabel: string; principle: string }> = {
  perception: { label: '感知', loopLabel: '看见发生了什么', principle: '把外部信息变成 agent 可理解的上下文。' },
  judgment: { label: '判断', loopLabel: '理解现在该做什么', principle: '形成意图、阶段、风险和下一步判断。' },
  interaction: { label: '交互', loopLabel: '让用户参与决策', principle: '让用户确认、选择、上传、授权或接入语音。' },
  action: { label: '行动', loopLabel: '改变状态或产生交付', principle: '生成 artifact、写状态、创建 lead 或推进服务。' },
  evaluation: { label: '评测', loopLabel: '判断系统有没有做好', principle: '检查事实、体验、转化时机和 tool 组合质量。' },
};

export const SERVICE_ACTION_ATOMS: ServiceActionAtom[] = [
  {
    id: 'load-skill-playbook',
    name: 'loadSkillPlaybook',
    toolName: 'useSkill',
    atomType: 'perception',
    status: 'live',
    capabilityType: 'agent-tool',
    serviceAction: '按需读取机构服务方法论',
    description: '把机构 skill 从目录加载进上下文，让 agent 在需要深任务时才使用完整 playbook。',
    owner: 'Platform',
    inputState: '学生意图已落入某个服务场景，或需要切换方法论',
    outputArtifact: 'Skill context',
    userVisibleResult: '学生感知到顾问开始按专业方法推进，而不是套模板',
    evalCriteria: ['skill 选择是否匹配真实意图', '是否避免把开放问题硬塞进 workflow'],
  },
  {
    id: 'read-student-profile',
    name: 'readStudentProfile',
    toolName: 'readProfile',
    atomType: 'perception',
    status: 'live',
    capabilityType: 'agent-tool',
    serviceAction: '读取学生长期上下文',
    description: '读取目标、材料、历史候选、CV 和偏好，避免重复问用户。',
    owner: 'Platform',
    inputState: '需要判断学生背景、目标、材料是否已知',
    outputArtifact: 'Profile context',
    userVisibleResult: '顾问能自然接住用户已经说过的信息',
    evalCriteria: ['是否先读再问', '是否只读取必要字段', '是否避免把临时探索当稳定事实'],
  },
  {
    id: 'parse-student-document',
    name: 'requestAndParseDocument',
    toolName: 'fileUpload',
    atomType: 'perception',
    status: 'live',
    capabilityType: 'ui-tool',
    serviceAction: '请求并解析学生材料',
    description: '让学生上传 CV、成绩单、文书等材料，并把文件解析成可用上下文。',
    owner: 'Generative UI',
    inputState: '缺少关键材料，且该材料会改变判断',
    outputArtifact: 'Parsed document context',
    userVisibleResult: '上传卡和解析完成状态',
    evalCriteria: ['是否只在材料真正必要时请求上传', '解析结果是否写入正确画像字段'],
  },
  {
    id: 'search-grounded-evidence',
    name: 'searchGroundedEvidence',
    toolName: 'webSearch',
    atomType: 'perception',
    status: 'live',
    capabilityType: 'agent-tool',
    serviceAction: '检索实时事实与来源',
    description: '查导师近期论文、招生动态、项目截止日期等时效性信息。',
    owner: 'Platform',
    inputState: '任务依赖外部事实或最近变化',
    outputArtifact: 'Cited evidence set',
    userVisibleResult: '工作台中出现来源、证据缺口和可信度',
    evalCriteria: ['query 是否拆小且具体', '是否引用真实 citation', '是否把缺失证据暴露给用户'],
  },
  {
    id: 'search-program-requirements',
    name: 'searchProgramRequirements',
    toolName: 'searchProgramRequirements',
    atomType: 'perception',
    status: 'live',
    capabilityType: 'agent-tool',
    serviceAction: '检索项目官方要求',
    description: '查学校/项目的申请要求、DDL、材料、funding、课程结构和项目事实，用于定位和短名单。',
    owner: 'Platform',
    inputState: '申请策略依赖项目事实，而不是只靠顾问经验',
    outputArtifact: 'Program evidence set',
    userVisibleResult: '短名单或方案里出现官方来源、证据缺口和申请约束',
    evalCriteria: ['是否优先查官方来源', '是否区分要求/DDL/funding 等 focus', '是否没有把未查实项目写成确定事实'],
  },
  {
    id: 'surface-consultant-judgment',
    name: 'surfaceConsultantJudgment',
    toolName: 'showConsultantMove',
    atomType: 'judgment',
    status: 'live',
    capabilityType: 'ui-tool',
    serviceAction: '展示顾问式判断',
    description: '把真实意图、依据和下一步动作显性化，替代冷冰冰的流程入口。',
    owner: 'Generative UI',
    inputState: '用户开放、摇摆、焦虑或需要被接住',
    outputArtifact: 'Consultant move',
    userVisibleResult: '一张顾问判断卡，说明我听懂了什么和准备怎么帮你动',
    evalCriteria: ['是否先判断意图', '是否只问一个关键问题', '动作是否推进真实目标'],
  },
  {
    id: 'discover-advisor-options',
    name: 'discoverAdvisorOptions',
    toolName: 'showAdvisorDiscovery',
    atomType: 'judgment',
    status: 'live',
    capabilityType: 'ui-tool',
    serviceAction: '收窄导师/方向探索',
    description: '在用户还没确定导师时展示候选、证据、风险和下一步验证策略。',
    owner: 'Generative UI',
    inputState: '导师、学校或方向仍在探索',
    outputArtifact: 'Advisor discovery workspace',
    userVisibleResult: '导师探索工作台，而不是直接套磁草稿',
    evalCriteria: ['是否保留探索状态', '是否没有锁死候选', '是否给出证据缺口'],
  },
  {
    id: 'ask-low-friction-choice',
    name: 'askLowFrictionChoice',
    toolName: 'askOptions',
    atomType: 'interaction',
    status: 'live',
    capabilityType: 'ui-tool',
    serviceAction: '让用户低成本表态',
    description: '在信息不足但不值得长问答时，用 2-6 个选项让用户参与决策。',
    owner: 'Generative UI',
    inputState: '一个选择会显著改变下一步',
    outputArtifact: 'User choice event',
    userVisibleResult: '选择卡',
    evalCriteria: ['问题是否高杠杆', '选项是否互斥且少量', '选择后是否立即闭环推进'],
  },
  {
    id: 'start-inline-voice',
    name: 'startInlineVoice',
    toolName: 'startVoiceCall',
    atomType: 'interaction',
    status: 'live',
    capabilityType: 'ui-tool',
    serviceAction: '把文字咨询升级到语音',
    description: '当语气、信心、故事线或面试练习用文字说不透时，在对话流内发起语音。',
    owner: 'Voice',
    inputState: '文字交互信息密度过高，或用户明确想语音聊',
    outputArtifact: 'Realtime voice session',
    userVisibleResult: '对话内语音卡，接听后继续服务',
    evalCriteria: ['是否有明确语音理由', '是否避免单独页面打断上下文', '通话后是否回写摘要'],
  },
  {
    id: 'produce-living-artifact',
    name: 'produceLivingArtifact',
    toolName: 'showDraft',
    atomType: 'action',
    status: 'live',
    capabilityType: 'ui-tool',
    serviceAction: '生成可迭代交付物',
    description: '生成 CV 诊断、套磁草稿、申请计划等 artifact，并把旧版本折叠成历史。',
    owner: 'Generative UI',
    inputState: '判断已足够，需要给用户一个可行动交付',
    outputArtifact: 'Living artifact',
    userVisibleResult: '一张可展开、可迭代、可继续推进的交付物',
    evalCriteria: ['是否避免重复刷屏', '是否有下一步出口', '内容是否引用用户真实材料'],
  },
  {
    id: 'create-service-plan',
    name: 'createServicePlan',
    toolName: 'showServicePlan',
    atomType: 'action',
    status: 'live',
    capabilityType: 'ui-tool',
    serviceAction: '生成全周期服务方案',
    description: '把服务前准备、导师匹配、材料、面试和接力组织成一张渐进展开的方案板。',
    owner: 'Generative UI',
    inputState: '用户需要知道机构如何帮他走完整链路',
    outputArtifact: 'Service plan board',
    userVisibleResult: '当前 2-3 个关键模块，细节折叠',
    evalCriteria: ['是否低信息负荷', '是否有当前目标', '模块是否能继续触发闭环动作'],
  },
  {
    id: 'build-outreach-workspace',
    name: 'buildOutreachWorkspace',
    toolName: 'showOutreachWorkspace',
    atomType: 'action',
    status: 'live',
    capabilityType: 'ui-tool',
    serviceAction: '构建导师外联工作台',
    description: '把导师档案、来源、fit map、邮件策略和风险放在一个可继续推进的工作台里。',
    owner: 'Generative UI',
    inputState: '用户已明确某位导师或外联对象',
    outputArtifact: 'Outreach workspace',
    userVisibleResult: '外联工作台',
    evalCriteria: ['导师事实是否有来源', 'fit map 是否绑定学生材料', '风险是否明确'],
  },
  {
    id: 'persist-stable-profile-fact',
    name: 'persistStableProfileFact',
    toolName: 'writeProfile',
    atomType: 'action',
    status: 'live',
    capabilityType: 'agent-tool',
    serviceAction: '沉淀稳定画像事实',
    description: '只把学生明确确认或工具验证过的事实写入画像，临时探索留在 artifact。',
    owner: 'Platform',
    inputState: '产生了稳定事实或材料解析结果',
    outputArtifact: 'Updated student profile',
    userVisibleResult: '后续对话更懂用户，不重复问',
    evalCriteria: ['是否只写稳定事实', 'advisor 状态是否区分 mentioned/exploring/shortlisted'],
  },
  {
    id: 'handoff-human-advisor',
    name: 'handoffHumanAdvisor',
    toolName: 'ctaWechat',
    atomType: 'action',
    status: 'live',
    capabilityType: 'ui-tool',
    serviceAction: '高意向时转真人顾问',
    description: '在学生已经拿到实质价值后，收集联系方式并把上下文交给真人顾问。',
    owner: 'Growth',
    inputState: 'Aha 时刻已出现，且需要真人判断或成交接力',
    outputArtifact: 'Consult lead',
    userVisibleResult: '顾问接力卡',
    evalCriteria: ['是否过早 CTA', 'reason 是否引用具体用户事实', 'lead 是否带完整 replay'],
  },
  {
    id: 'evaluate-agent-trace',
    name: 'evaluateAgentTrace',
    atomType: 'evaluation',
    status: 'live',
    capabilityType: 'platform-service',
    serviceAction: '评测 agent 轨迹质量',
    description: '用 Agent Arena 检查意图理解、tool 组合、来源、画像纪律和转化时机。',
    owner: 'Platform',
    inputState: '一次真实或模拟咨询 session',
    outputArtifact: 'Arena scorecard',
    userVisibleResult: '机构后台的评测分和失败原因',
    evalCriteria: ['是否可复现', '是否能定位失败原子', '是否能作为 skill 发布门槛'],
  },
  {
    id: 'evaluate-experience-trace',
    name: 'evaluateExperienceTrace',
    atomType: 'evaluation',
    status: 'live',
    capabilityType: 'platform-service',
    serviceAction: '评测用户体验轨迹',
    description: '把截图/视频/DOM 变化压缩成语义化 Experience Trace，检查等待、重复、内部噪音、目标假设和信息负荷。',
    owner: 'Platform',
    inputState: '一次真实或模拟用户操作轨迹，包含关键帧、动作和页面文本',
    outputArtifact: 'UX Replay scorecard',
    userVisibleResult: '机构和平台看到这名数字员工的真实体验堵点',
    evalCriteria: ['是否抓到长静默期', '是否能发现 UI 重复刷屏', '是否能指向具体组件改进'],
  },
  {
    id: 'compare-artifact-version',
    name: 'compareArtifactVersion',
    atomType: 'evaluation',
    status: 'planned',
    capabilityType: 'platform-service',
    serviceAction: '比较 artifact 版本是否变好',
    description: '比较 CV 诊断、套磁草稿、申请方案的版本差异，判断改动是否真的提升质量。',
    owner: 'Platform',
    inputState: '同一 artifact 的两个版本',
    outputArtifact: 'Artifact diff evaluation',
    userVisibleResult: '机构看到每次迭代的质量变化',
    evalCriteria: ['是否减少幻觉', '是否提升具体性', '是否保留用户意图'],
  },
];

export function getServiceActionAtomSummary(atoms: ServiceActionAtom[] = SERVICE_ACTION_ATOMS) {
  return atoms.reduce(
    (summary, atom) => {
      summary.total += 1;
      summary.byType[atom.atomType] = (summary.byType[atom.atomType] ?? 0) + 1;
      summary.byStatus[atom.status] = (summary.byStatus[atom.status] ?? 0) + 1;
      return summary;
    },
    {
      total: 0,
      byType: {} as Record<ServiceActionAtomType, number>,
      byStatus: {} as Record<ServiceActionAtomStatus, number>,
    },
  );
}
